### ISSUE TITLE
Menu eventos/tryhards

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#10]
Um administrador com direitos de acesso que utiliza o comando abre um menu com 2 opções:
1. Ativar modo evento
2. Desativar modo evento

Ao ativar o modo evento, todos os jogadores presentes irão ter um menu aberto em sua tela sobre as regras adicionais do evento, assim como jogadores que irão conectar tbm. Este menu possuirá as informações básicas adicionais (Como RTV está desativado, regras mais severas de mutes, etc) assim como 2 inputs:
1. Concordo, irei seguir as regras.
2. Discordo, irei voltar no servidor outra hora.

Jogadores que recusam serão kickados do servidor com uma mensagem explicativa. Isso tbm deve ocorrer pra jogadores que não responderam no tempo limite este menu.

Obs: Ao ativar o modo evento já desativar RTV e qualquer outros comandos que possam ser anexados em um só.

Opcional: fazer que esse comando fique ativo mesmo na mudança de mapas ou que tenha um contador da quantidade de mapas que ele continuará ativo.

**Comment by gabrielacms** [comment]
Acho interessante isso. 
O único porém seria em relação a esses comandos que poderiam ser ativados junto com o modo evento. 
Porque tem alguns comandos que dependem do estilo do evento. 
Tryhard geralmente roda 1 hora. E tryhard nao tem zshop
Evento roda 2 horas ou 45 minutos se for combo. E ode ser que futuramente tenha zshop em evento. 

Não daria para tipo esses comandos que seriam ativados junto com o modo evento, o próprio adm definir eles? 

1. Ativar modo evento
2. Desativar modo evento. 

Admin escolheu o 1. Dai tem outro menu 
Definir tempo do mapa
1. 2 horas
2. 1 hora
3. 45 minutos

Dai vem sobre zshop
1. Desativar zshop
2. Ativar zshop. 
Talvez o único comando que não precisaria do adm configurar ali seria o tempo do AFK.

**Comment by hcjordao** [comment]
Pode ser mas não vejo o pq de deixar o tempo de mapa que é algo bem variável como parte do menu. Acho que se o adm tem controle pleno é melhor. RTV sempre vai estar desativado então acho mais seguro e zshop nesse meio tempo tbm entao acho valido tbm.

**Comment by quasemago** [comment]
Soon!

**Comment by hcjordao** [comment]
When? :thanossmile:

**Comment by hcjordao** [comment]
Ainda acham relevante esse tópico?

**Comment by lucaslinha** [comment]
Não tem mais o que discutir, so aguardar mesmo.

**Comment by hcjordao** [comment]
Definição de pronto:

[ ] Arquivo event_display.txt, em algum path.
[ ] Caso haja dados no arquivo, abrir display de eventos.
[ ]Display deve durar em torno de 8s - 15s (de preferência configurável)
[ ] Ao expirar o timer dar displays na regras caso o jogador não tenha colocado a opção de não ler mais as regras no client prefs.
[ ] Caso não haja dados no arquivo, não exibir o menu.
[ ] Arquivo no final deve estar no repositório do github

**Comment by quasemago** [comment]
Menu de regras agora é obrigatório para mostrar a config ativa. Sobre os outros pontos farei de outra forma.

Sugiro fechar esse issue e abrir um novo apenas requisitando um menu de eventos/tryhard.

**Comment by hcjordao** [comment]
Isso está implementado, novos reports de bugs e tweaks melhor abrir em outro issue
