### ISSUE TITLE
[TTT] Lag ao fim do round

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#100]
Todo final de round a partir de ontem começou a dar um freeze no server. Apesar de não afetar o gameplay em si é bem ruim de ficar ocorrendo todo round.

**Comment by quasemago** [comment]
Acontece sempre ou apenas depois de determinada quantidade de jogadores?

**Comment by quasemago** [comment]
Joguei por alguns minutos (servidor estava praticamente cheio) e não apresentou o problema reportado.

**Comment by quasemago** [comment]
Issue fechado visto que o problema não aconteceu novamente.
