### ISSUE TITLE
[TTT] Inserir no sm_log o kos ao ser utilizado pelo sm_kos

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#102]
Facilitar a depuração dos logs pelos nossos caros admins.

**Comment by quasemago** [comment]
Done. `[RADIO]-> [Fulano [STEAMID] (Inocente) deu KOS no jogador Siclano [STEAMID] (Traitor)]`

**Comment by lhsatsuma** [comment]
Testado e aprovado!

![image](https://user-images.githubusercontent.com/44283104/76910859-ee8b3780-688d-11ea-9a68-cc619a5e5343.png)
