### ISSUE TITLE
[ZE] Player Stats

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#103]
Essa sugestão não tem nenhuma feature visível relacionada mas já adicionando isso ao server já fica mais fácil caso queiramos usar no futuro para algo.

Ao start/end round dos mapas começar a escutar os dados dos jogadores:
- Média de top defender: <Média atual DB> + <Dano do Round> / 2.
- Ao entrar no server: <Número de mapas jogador DB> + 1
- Ao zerar o mapa, caso o jogador tenha zerado: <Número de mapas zerados DB> + 1
- Caso tenha um dos top defenders: <Nro de top defenders obtidos> + 1
- Tempo online: <Tempo online no server> + <T final - T inicial> (Creio eu que já exista)

**Comment by danielhidalgojunior** [comment]
Isso daí daria no mínimo umas 4 tabelas

**Comment by hcjordao** [comment]
Eta nao manjo de DB entao se tu diz

**Comment by danielhidalgojunior** [comment]
Da pra aproveitar muita info se montar isso seguindo algumas boas práticas de DB. Talvez até um futuro analytics depois que tivermos uma boa base de dados

**Comment by hcjordao** [comment]
Seria interessante ja aplicar esses conceitos junto com o #97

**Comment by hcjordao** [comment]
Seria massa mas não vai ser implementado agora :pepehands:. Boa sugestão @hcjordao
