### ISSUE TITLE
[ZE] Map Stats

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#104]
Tabela com a lista de mapas do servidor. Mesma coisa que o issue #103 , no momento apenas para analise:

- Ao start mapa de um mapa: <Nro Atual DB> + 1 
- Ao map win: <Nro de vezes zerado DB> + 1 (Apenas conta uma vez para mapas com level único)
- Recorde de defesa do mapa no round da vitória, se <Max Def DB> for menor que atual atualiza a mesma.

**Comment by danielhidalgojunior** [comment]
Muito campo calculado, isso daí daria pra quebrar em pedaços menores

**Comment by hcjordao** [comment]
Como assim calculado? Seria calculado no fim do mapa e no start do mapa

**Comment by danielhidalgojunior** [comment]
Toda vez tem que atualizar o registro. Cada win de mapa deveria ser um novo registro, como te mostrei há uns dias. Do jeito q tu falou, tu perde muita info, não dá pra saber quando zeraram, quantas vezes em tal período... São informações que tu perde dependendo de como tu estrutura esses dados

**Comment by hcjordao** [comment]
Seria interessante ja aplicar esses conceitos junto com o #97

**Comment by hcjordao** [comment]
Seria massa mas não vai ser implementado agora :pepehands:. Boa sugestão @hcjordao
