### ISSUE TITLE
[ZE] Alteração no comando !nominate Nome do Mapa (quando possuir +de 1 versão) 

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#107]
Sugestão feita por: Matsu - https://steamcommunity.com/profiles/76561198130540435

Permitir a escolha do mapa correto por meio de um menu quando houver mais de uma versão de um mesmo mapa ou mais de um mapa com o mesmo prefixo, 
Ao invés do servidor nominar sozinho o mapa, disponibilizar um menu para que o jogador possa escolher a versão que ele queira nominar. 

Ex: !nominate surf - Aparecer um menu com todos os mapas de surf.
!nominate mako - Aparecer um menu com as 2 versões que existem no servidor. 

- Aparentemente quando se nomina um mapa pelo chat, o servidor seleciona o mapa seguindo a ordem alfabética. Sendo assim, mapas que possuem mais de uma versão, a primeira versão será sempre nominada e se caso estiver em cooldown, o servidor não dá opção para o jogador escolher a outra versão existente.

**Comment by lucaslinha** [comment]
Acho desnecessario demais, pouquissimas pessoas nominam digitando o nome e essas tem capacidade suficiente para pegar o nome no map ou listmaps.

**Comment by hcjordao** [comment]
Também acho desnecessário. Da pra de boas selecionar as versões dos mapas direto pelo nominate:

!nominate dreamin_v1, !nominate dreamin_v2, !nominate westersand_v7, !nominate westersand_v8, !nominate westersand_v2, !nominate surf_sahok, !nominate surf_vortex. Concordo com o infused que muitas poucas pessoam fazem nominate pelo chat.

**Comment by alminha021** [comment]
acho desnecessário, BUT , existe um comando que vc coloca no console "listmaps" ele lista todos os mapas do servidor ,ams ele é incompleto, acredito que pelo numero de linhas ja que sao muitos mapas, o que podemos fazer eh retrabalahr esse comando para listar TODOS , mesmo que use "paginas" exemplo:
listmaps
ze._2...
...
...
ze_mako...
para mais mapas
digite listmaps 2

listmaps 2:
ze_minecraft..
...
...
ze_portroyo
para continuar
digite listmaps 3

listmaps 3:
ze_put...
ze_z..
fim.

como o sm_help funciona , la vai do sm_help 1 ate o 25 eu acho, mostrando todos os comandos
a ideia eh que um listmaps colocque o maximo possivel de mapas no console , para nao termos muitas paginas

**Comment by alminha021** [comment]
ai eh so dar um ctrl c ctrl v no nome do mapa pelo console , e nomear, rapidao, eu pelo menos faço isso em mapas que aparecem no listmaps

**Comment by danielhidalgojunior** [comment]
como já dito, é desnecessário. É um recurso que não será usado por 99% dos jogadores.

E apoio a ideia do alma, também fico triste quando não acho o mapa no listmaps, um rework seria interessante.

**Comment by quasemago** [comment]
Pode não ser utilizado por muitos jogadores, mas gostei da ideia e farei.

**Comment by quasemago** [comment]
Já está no servidor em fase de teste, qualquer bug pode ser reportado aqui no issue.

**Comment by quasemago** [comment]
Fiz vários testes e parece estar tudo funcional, irei portar as edições para o nominate padrão (utilizado no servidor TTT).
