### ISSUE TITLE
Aumento de Cooldown dos mapas de ZE

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#11]
Com o aumento dos mapas de ZE que estão no servidor o cooldown tem que ser aumentado levemente para abrir novos mapas de serem jogados.

**Comment by quasemago** [comment]
Quanto você acha um bom valor? o atual já está em **100**

**Comment by hcjordao** [comment]
Bem tem cerca de 279 mapas no servidor para serem jogados. acho que pelo menos metade 140 mapas por ai. 279 mapas são muito mapas jesus. Como tinham sugerido talvez pode manter um cooldown menor se restringir quais mapas podem ser jogados com mapcycles especificos para cada dia da semana

**Comment by lucaslinha** [comment]
279 ? Pelo que vi tem 290 aqui e ainda vai entrar mais uns 15 mais tarde, ou seja vai ficar 304/305 por ai.

**Comment by alminha021** [comment]
Bom, eu mudaria, mas nao mudaria o global..
Tipo, vcs fizeram a lista la dos mapas, zerados e a dificuldade.
considerando 300 maps
Um mapa que tem 1,2 ou 3 estrelas toma 120 de cd.
Mapa 4 , 5 toma 100 de cd.
Mapa 6 estrelas 80.
Nao sei como vai ficar na pratica , mapa com cd menor entrando na frente dos outros , porem os mapa extremamente faceis iriam demorar mais mesmo, 120 mapas de cd + mapas com cd menor entrando na frente, o que pra mim esta ok, o nivel do servido tem que aumenta uma hora. E se ficar zoado, so reduzir os cd dos mapa com maior dificuldade, mantem 100 nos estrela 1,2,3 e o 4,5,6 reduz pra 70 ou 80.
menos zé farms , querem farmar, joguem mapas diferentes pelo menos.

**Comment by hcjordao** [comment]
Pra mim ao inves de mudar o CD, podiamos botar em pratica rotações de mapa no servidor. E alterar quais mapas estão no servidor de modo mensal, semanal, etc. Assim o CD permanece o mesmo mas ainda tem um monte de mapa para ser jogado. Já que tem uma quantidade enorme de mapas no servidor podemos dividir em 2 batches de 170-150 mapas, onde apenas alguns mapas se repetiriam

**Comment by quasemago** [comment]
@alminha021 Não da pra especificar isso por mapas, é um valor global.

@hcjordao @lucaslinha Recomendo revisar os mapas e remover os que quase nunca são jogados (nunca mesmo) e os que realmente não fazem falta.

Quanto a rotação por dias, isso teria que ser setado manualmente.

**Comment by lucaslinha** [comment]
Não seria possivel fazer revezamento nesse mapcycle não ? gfl mesmo muda rotação de mes em mes em alguns mapas.

**Comment by hcjordao** [comment]
Sim dá mas isso tem que ser feito de modo manual. Basta ter os .txt prontos e só substituir ele no mapcycle.txt atual que tu tem isso salvo. Isso pode ser mantido no repositório principal como mapcycle_1.txt, mapcycle_2.txt... E todo mes podemos trocar eles. 

Só precisa ser lembrado de manter atualizado em uma lista todos os mapas no nominate por causa dos eventos mas vc @lucaslinha já fez isso no discord então ta sereno essa parte. Só falta separar em mapcycles para fazermos isso.

**Comment by lucaslinha** [comment]
300 mapas no server atualmente, aumenta pra uns 140.

**Comment by quasemago** [comment]
Como eu disse antes, primeiro acho melhor revisar os mapas e remover os que quase nunca são jogados (nunca mesmo) e os que realmente não fazem falta seja por ser ruim ou qualquer outro motivo.

**Comment by hcjordao** [comment]
Mas existem mapas que são bons e não são jogados nunca mesmo sendo mapas faceis/médios. Exemplos do topo da minha cabeça:
ze_aepp_nano_grid2_b2
ze_aztec_temple_go_v2
ze_breakable_p3
ze_colorlicouspilar_p4
ze_colors_p3
ze_interception_p2
ze_noir_p1

São mapas de qualidade bons mas raramente são jogados. Ao meu ver precisamos capar em um limite X de mapas por exemplo -> 200 mapas no nominate. Os que sobrarem deixa um .txt e vai alternando mensalmente ou semanalmente.

**Comment by hcjordao** [comment]
Manter como está no momento, no futuro abrir o issue novamente
