### ISSUE TITLE
[TTT] Adição de regra para traidor

### ISSUE THREAD

**Issue by danielhidalgojunior** [quasemago/zrageservers#111]
1. Um traidor não pode, de nenhuma maneira, inocentar a si mesmo ou outros jogadores.

Com essa regra, ficam claros os casos como, por exemplo: quando um inocente testa outro inocente, ambos podem ser inocentados publicamente.

E como apontado pelo alma, para impedir buracos, precisaria garantir que testar ou ser testado com a taser removeria qualquer possibilidade de virar T na roleta. 

OBS.: não tenho certeza, mas creio que o @quasemago corrigiu essa questão de ser testado removeria suas chances de virar T, porém, com essa regra, seria necessário que ao testar algúem vc tbm perdesse a chance de virar T.

@edit

Ao matar um traidor, vc tbm deve perder as chances de virar T na roleta.

**Comment by alminha021** [comment]
como ja falado, pode acabar inocentando um cara que testou e virou t depois. Precisando mudar mais coisas a toa

-Prejudica a roleta do cara , pra que?
-Inutiliza mais aind a taser do traitor ( pq vai ter isso pra comprar? se nem roleplay pode fazer)
- o cara pode tomar balas no mesmo instante que um traitor testa ele, o cara nao percebe que tambem levou dano da taser , ACHISMO NAO PROVA , e o t pode acabar inocentado erroneamente
- deve ter mais buracos, estou com preguiça agora de ir atras.

ENFIM , pra mim ja basta
-  PROIBIDO MENTIR O RESULTADO
- inocentado apenas quem levou a taser.
se querem colocar isso nas regras, para alertar os caras, ok
+ Apenas o atingido do taser esta provado inocente no teste.

**Comment by danielhidalgojunior** [comment]
1. não conheço um único ser que compra taser na roleta sendo T, afinal, se vc acertar, vc ganha uma bala na testa de graça já que teste de T dá dano no testado.

2. De qualquer maneira, com essa regra, traidor não poderia dizer que o cara é inocente, então não faria diferença se desse dano e o ino não percebesse, pois o que conta é o cara dizer no chat ou no voice que fulano foi testado e é inocente, coisa que T não poderia fazer.

**Comment by hcjordao** [comment]
Isso resolve todas as possiveis ambiguidades:

1. Remove a taser do shop do traidor. 
2. Taser de inocente em inocente impossibilita o inocente testado de virar T na roleta assim como o do detetive.
3. Jogador que testou um outro jogador na roleta também perde seu direito de ser traidor na roleta.
4. Ambos os jogadores (o testado e o que testou) podem ser considerados como inocentes, caso necessário aumentar o preço da taser já que provem essa imunidade.
5. Traidor não pode se inocentar fingindo usar uma taser em outro T e/ou outro inocente. 


No fim do dia essas regras não vão alterar em nada/ quase nada o jeito que o modo é jogado mas vai definir uma linha do que é antijogo ou não e podemos verificar algo nos logs facilmente quem praticou antijogo

**Comment by danielhidalgojunior** [comment]
@hcjordao só corrigindo um dos itens q vc falou, ambos testado e testador devem perder o direito da roleta, senão sobra espaço pra se aproveitar de buraco na regra.

**Comment by hcjordao** [comment]
Ta explicado ali o jumento, nos itens 2 e 3.

**Comment by danielhidalgojunior** [comment]
ata, é q vc teve a incapacidade de botar tudo num item só, sinto muito por nao lembrar q tu é especial

**Comment by nil209** [comment]
to com o alma no processo, o que alterar menos no game, é só adicionar nas regras e acabou.

Afinal como não tem como provar que o cara acertou a taser, não tem como inocentar o "cara da taser"

**Comment by hcjordao** [comment]
Daria para provar caso aparecesse no tab vivo -> inocente, mas ai acho que talvez vcs achem meio nutella isso. Usou taser, o fulano e o beltrano ficam com inocente na tag.

**Comment by lhsatsuma** [comment]
Nas regras já tem algo parecido:

> Pertencendo a classe TRAIDOR, é PROIBIDO:
> 1. Dizer que outro traidor é inocente. 

Sobre a sugestão do Haru:

> 1. Remove a taser do shop do traidor.

Ok, nada contra

> 2. Taser de inocente em inocente impossibilita o inocente testado de virar T na roleta assim como o do detetive.

Acho que não, pq mesmo q o cara vire T na roleta dps de testado, é legal pq dá aquele lag mental no pessoal e vc se diverte com isso.

> 3, Jogador que testou um outro jogador na roleta também perde seu direito de ser traidor na roleta.

Na minha visão não tem o pq bloquear isso.

> 4. Ambos os jogadores (o testado e o que testou) podem ser considerados como inocentes, caso necessário aumentar o preço da taser já que provem essa imunidade.

Concordo!

> 5. Traidor não pode se inocentar fingindo usar uma taser em outro T e/ou outro inocente.

Concordo!

**Comment by danielhidalgojunior** [comment]
> 3, Jogador que testou um outro jogador na roleta também perde seu direito de ser traidor na roleta.

> Na minha visão não tem o pq bloquear isso.

Na verdade é necessário bloquear, visto que a taser agora irá inocentar testador e testado. Senão eu posso usar o taser antes da roleta, inocentar a mim e a mais um colega e então virar T na roleta.

**Comment by quasemago** [comment]
Formulem melhor o que deve ou não ser adicionado.

**Comment by alminha021** [comment]
Pra mim, basta reescrever as regras:
Como traitor ja sabe o role de todos, cabe a ele o roleplay, se ele quer fingir que acertou taser e inocentar alguem, ok. Eh um a menos pro inocentes desconfiarem , e mais perigo pra ele.

O que mudar, pra mim:

- Deixar claro que vc sendo detetive ou inocente , nao pode mentir no resultado da taser , se nao acertou , nao chute um resultado!
- traitors nao podem inocentar outros traitors , mas podem inocentar inocentes, pra mim isso eh roleplay e tem suas desvantagens.

- deixar claro que apenas quem levou a taser eh inocente. ( Pra mim sempre foi assim, se jogam diferente disso ta errado, ja ta cheio de buracos ai como demosntrei a muito tempo , cara nao eh inocente se tomar taser , e ainda pode pegar na roleta)


Mas se querem add essa regra proposta, tem q ver todos os buracos, continuo contra, acho muito trabalho a toa e ta matando roleplay.

**Comment by quasemago** [comment]
Deixar como o @alminha021 sugeriu?

**Comment by danielhidalgojunior** [comment]
Ainda prefiro a minha ideia original. Achei mais simples e bem mais assertiva. Podemos deixar o pessoal da staff do ttt votar e deixar a democracia levar essa.

**Comment by lhsatsuma** [comment]
Concordo com o @alminha021

**Comment by quasemago** [comment]
Regras/mecânicas sugeridas pelo @alminha021 adicionadas ao servidor.

**Comment by hcjordao** [comment]
Visto que há um novo issue de pauta de regras irei fechar esse issue #122
