### ISSUE TITLE
[TTT] Adição de regra para inocentes

### ISSUE THREAD

**Issue by danielhidalgojunior** [quasemago/zrageservers#112]
1. Inocentes serão publicamente inocentados caso digam/escrevam "matei traidor/matei T" após matar um traidor.

Como explicado pelo Spawn, é meio que uma regras criada pelos players, creio que seja justo inserir na lista de regras para que novos jogadores estejam cientes desse direito de inocente.

**Comment by quasemago** [comment]
Regra 3 dos traidores:
- Anunciar que você matou um traidor visto que isso é utilizado como prova de inocência.

Então isso acaba ficando implícito, acha mesmo necessário colocar?

**Comment by hcjordao** [comment]
Melhor deixar explicito pq ai não volta para morder a nossa bunda no futuro. "Ain mas eu não achei isso nas regras não"

**Comment by danielhidalgojunior** [comment]
> Regra 3 dos traidores:
> 
> * Não anunciar que você matou um traidor visto que isso é utilizado como prova de inocência.
> 
> Então isso acaba ficando implícito, acha mesmo necessário colocar?

nego gosta de procurar buraco na regra, então o quanto mais explicito estiver, melhor.

Até pra quem for ler as regras ver que inocentes podem fazer isso sem medo.

**Comment by quasemago** [comment]
Regra aceita!
