### ISSUE TITLE
[TTT] Traidores ganham se matarem todos os inocentes

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#113]
Aproveitando essas regras acho que essa é uma das mais essenciais do TTT que falta ainda. 

Traidores ganham se materem todos os inocentes. Não necessariamente matando todos os jogadores. Não há necessidade de matar um detetive, é apenas um bonus.

**Comment by alminha021** [comment]
Modo eh pra ser jogado dessa maneira. Apoio.

**Comment by nil209** [comment]
+rep

**Comment by quasemago** [comment]
Foi alterado, agora só testar.

**Comment by lhsatsuma** [comment]
Eu esqueci de tirar print.

Mas ta aparecendo "Detectives Wins"

Não deveria ser Traitors Wins? Já q foi o detetive que não cumpriu o objetivo.

**Comment by lhsatsuma** [comment]
E outra, tem que desativar isso nos VTS...

![image](https://user-images.githubusercontent.com/44283104/77829106-96123080-70fe-11ea-99cc-514d7851b388.png)

**Comment by quasemago** [comment]
Alterações feitas, irei enviar para o servidor outra hora.

**Comment by quasemago** [comment]
Tudo certo!
