### ISSUE TITLE
[TTT] Bug ao spawnar no mapa

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#114]
Hoje, no mapa ttt_terrortrain_v1_2_2_csgo, presenciei um bug que ocorreu 2 vezes tanto cmg quanto com o tardigrada de nascermos e tomarmos kill aleatoriamente.

Alguem tem mais informações sobre isso?

**Comment by danielhidalgojunior** [comment]
Acontece algumas vezes no meu primeiro round quando entro no sv

**Comment by alminha021** [comment]
Fanzack ao entrar no mapa, sempre aperte ESC , esse bug eh normal qnd muda de mapa ou vc acabou de entrar.

**Comment by alminha021** [comment]
se as mortes aleatorias foi por vcs terem acabado de entrar ou o mapa ter sido mudado, foi por isso, ele mata mesmo qnd vc pega a pistola por exemplo, por isso eh sempre bom  apertar esc ao entrar

**Comment by quasemago** [comment]
Um hotfix está sendo testado.

**Comment by quasemago** [comment]
Hotfix funcionando perfeitamente, issue resolvido.
