### ISSUE TITLE
[ZE] Lider mark 

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#116]
Vi esse video e achei muito massa o jeito que é montado o esquema de marks no chao. Muito melhor do que o atual. Permite você adicionar multiplas marcas. 

- O comando sempre incrementa uma marca até acho que 4/5 ta bom. 
- Um comando que reseta e volta para o número 1.

Video de referência: https://youtu.be/eSKRo7vwhqw?t=450

**Comment by danielhidalgojunior** [comment]
não vejo problema desde que se possa esconder isso através do hidelider.

**Comment by lucaslinha** [comment]
Por mim um verde e um vermelho ta de boa, vermelho pra marcar tds os lugares que o zm vem é claro.

**Comment by hcjordao** [comment]
Acho melhor ser indicado pela letra como fazem. Assim tu pode indicar o que tu quer que o cara faça. indicar holds de zumib, indicar triggers, indicar posicionamento de itens, ou de posicionamento de boss.

**Comment by alminha021** [comment]
Tem muitas marcaçoes que podem ter , jogava em um server de jailbrak que a marcaçao eh 10x melhor que a que usamos.
la podemos:
- colocar mais de uma marca 
- marcaçoes com cores dferentes
- delimitar uma area ( utilizando um outro tipo de marcaçao ele colocava 3 ou mais pontos no chao e essas marcaçoes eram ligadas automaticamente, formando uma área no chao).

Dar a liberdade do lider aprender a manusear e ter varias maneiras de serem utilizada eh daora tbm , melhor q usar a mesma marcaçao pra tudo

**Comment by hcjordao** [comment]
Que massa esse de área, desconhecia

**Comment by alminha021** [comment]
Nao lembro qual server achei, mas procurei an net, o da area naoa chei um igual, mas da pra ter uma ideia, o que queria era um menor ligando as marcaçoes por lasers pra delimtar uma area
 eh masi ou menos isso -> 
![image](https://user-images.githubusercontent.com/24982217/78078369-6d996900-7380-11ea-9647-5cebdc3d0ef2.png)

![image](https://user-images.githubusercontent.com/24982217/78078422-899d0a80-7380-11ea-8621-9a97ea5ef87e.png)

![image](https://user-images.githubusercontent.com/24982217/78078434-8f92eb80-7380-11ea-8d4b-abdd2106234e.png)


td de jailbreak links das marks e fences que achei mais parecido
- https://github.com/PremyslTalich/TeamGames/wiki/Marks
- https://github.com/PremyslTalich/TeamGames/wiki/MoreMarks
- https://github.com/PremyslTalich/TeamGames/wiki/Permanent-fences

tem esse que cria area, ams eh apenas areas circulares
https://www.youtube.com/watch?v=tp6k_Q6K37c

**Comment by hcjordao** [comment]
Eu acho que se tiver uma forma de colocar marcações simples e mais bonitas como a indicadas no vídeo e botar uma marcação de área que seja marca o centro e o raio e desenhar um círculo o suficiente.

**Comment by gabrielacms** [comment]
Eu tinha mandado uma vez isso ai em um post aqui no git sobre Rework no plugin do líder, cheguei a testar no dedicado é bem simples de colocar, o único problema é que esse da marcação azul, esse negocinho branco no meio, continua visível depois que a marcação some

**Comment by hcjordao** [comment]
Eu gostei bastante da marcação do Vip. Uma letra e uma cor diferente. Talvez isso já baste. Comando de inserir e um de limpar as existentes.

**Comment by alminha021** [comment]
sim, o que acho interessante eh a possibilidade do lider usar mais de um marcador, e um de criar área como no video, nada muito elaborado. Com isso ja  da pra fazer altas calls top

**Comment by alminha021** [comment]
vou gravar um video no server de jailbreak, la as marcaçoes sao parecias com essas , ams acho q nao fica o begocinho branco, e da pra usar mais de uma

**Comment by hcjordao** [comment]
movido para #143
