### ISSUE TITLE
[ZE] Nerf de dano no top defender gerados pela NEGEV e TECO

### ISSUE THREAD

**Issue by danielhidalgojunior** [quasemago/zrageservers#117]
Como vemos percebendo no servidor, o top defender está sendo praticamente farmado (zombie spawns, foco em zombies presos no canto da parede, etc) pelo pessoal que joga apenas de negev e teco, deixando o povo que realmente defende e que ajuda o time com poucas chances de aparecer no top defender e ganhar as bonificações dele (bonificação é pra quem ajuda, não pra quem farma). Não tenho nada contra o uso dessas armas, aliás sempre fui a favor de liberar todas as armas dentro do servidor, mas acho um pouco de sacanagem usar isso pra se sobressair sobre o pessoal que está realmente ajudando o time.

Sugiro diminuir o dano da negev em uns 30% e o da teco em uns 40%.

Outros valores ou alternativas são bem vindas.

**Comment by alminha021** [comment]
negev tem q ser mais nerfada que a  teco, teco so eh roubada dando hs e requer o mira +-, e muitos mapas eh complicado jogar de teco, fora que tem pouca bala, negev qualque zm vc atira e  prende na parede.
reduz 20 da teco e 30 da negev.

So o que tem, quase todo mapa

top mais comum
negevplayer - 25k
sub player - 12k
subplayer2 - 11k

**Comment by quasemago** [comment]
Só pra frisar: redução do dano será apenas no topdefender e não na arma em geral.

**Comment by danielhidalgojunior** [comment]
acabou de terminar o mapa aqui e o top era isso basicamente:
65k
40k
15k

os 2 primeiros jogaram só de negev.

A redução precisa ser grande ao ponto de não valer a pena farmar de negev e até com uma smg vc faria mais ponto. Tem nego dando rebuy de negev pra farmar mais, são basicamente 2 hes que o cara joga fora pra poder farmar.

**Comment by hcjordao** [comment]
Nerfa bastante a negev, 30% não vai ser o suficiente, tenta fazer a equivalencia da negev com as subs. 50% de nerf em negev e 50% de nerf em teco-teco. Visto que o knockback e o dinheiro vão ser recebidos corretamente, ainda é validas armas a serem usadas.

**Comment by hcjordao** [comment]
Vi que o ronning já fez a alteração no plugin que nerfa por 35% o dano de todas as armas. Já já se não agora está no server então prestem atenção para fazer a validação

**Comment by quasemago** [comment]
Já está no servidor. Dano da negev e teco no topdefender foram nerfadas em 35%.
