### ISSUE TITLE
[ZE] Cmd de hud para lider 

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#121]
Motivo desse issue é basicamente fazer o povinho que joga sem som ou os que estão surdos por causa de gemido de zm + musica entenderem o que precisa ser feito durante uma ordem do lider. Sem contar que eu acho bem inutil aquele overlay que fica na cabeça do lider, maioria do servidor não sabe nem o que é um hello. 

A um tempo atras eu ja tinha pensado em overlay na tela mas ele acabaria sobrepondo overlay dos mapas em algum momento. 

Pensei também no hsay (mensagem que aparece no alerta) mas o dmg hit padrão é justamente um que usa o hint e logo acabaria sobrepondo e isso ficaria inutil também. 

Então a unica coisa que eu penso é uma mensagem de hud parecido com o zsay, so que um pouco acima do hint para ser utilizado com mensagens como Defenda com o lider ou Recue todo o caminho e por ai vai... 

Um dos melhores exemplos que se pode ter, o lider da Pse: https://imgur.com/a/YtkdB0P

**Comment by danielhidalgojunior** [comment]
quanto mais recurso pra guiar a batatada, melhor. Só peço que, caso isso seja de fato implementado, colocar para desativar pelo hideleader.

**Comment by hcjordao** [comment]
Concordo com o que o fanzack disse. Quanto mais recurso melhor. Se facilita para o batata sem estragar a User Experience com poluição super válido.

**Comment by alminha021** [comment]
Concordo que seria interesante, e concordo com o fanzack em conseguir esconder com o hideleader.

**Comment by gabrielacms** [comment]
Essa mensagem no HUD ficaria ativa até o líder remover ou seria de fato igual ao zsay (que aparece por alguns segundos e depois some) ?

**Comment by hcjordao** [comment]
Acho que nem o zsay, com uma cor chamativa na parte debaixo da tela

**Comment by alminha021** [comment]
entao seria como o zcsay/czsay que vc pode colocar cores na msg , seria interessante.

**Comment by hcjordao** [comment]
Movido para #143
