### ISSUE TITLE
[TTT] Pauta reformulação das regras

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#122]
### Pontos discutidos na reunião: (caso tenha ficado algo de fora, adicionar aos comentários.)
**Objetivos:**
- [x] - TRAIDOR não precisa mais matar os detetives.

**Gerais:**
- [x] - Dar KOS em outro jogador por estar utilizando armas silenciadas (estes serão suspeitos no máximo). (Mudar para armas não existentes ou que sejam restritas á salas de traidores)
- [x] - Ficar em uma área por mais de 30 segundos. (Observação: não tomar anti-afk não garante que você não esteja quebrando essa regra)
- [x] - Utilizar nomes difíceis de serem lidos, utilizar nomes que sonoramente parecem com outros jogadores. Preferência aos jogadores conectados anteriormente e a moderação do servidor.

**Detetives:**
- [x] - Dar uma ordem sem ter um taser (zeus) ou revolver no inventário.
- [ ] - Repetir o nome do jogador a cada contagem

**Atos de traição:**
- [x] - Ver o jogador utilizando o missil. (Observação: ver o jogador girando a camera é apenas um ato suspeito, salvo em casos que você veja a origem do missil e o mesmo contenha apenas uma rota de fuga.)

**Mecânicas:**
- [x] - Morrer falando o nome do jogador é apenas um ato suspeito.

**Comment by lhsatsuma** [comment]
> * [ ]  - TRAIDOR não precisa mais matar os detetives.

Concordo!

> 
> **Gerais:**
> 
> * [ ]  - Dar KOS em outro jogador por estar utilizando armas silenciadas (estes serão suspeitos no máximo). (Mudar para armas não existentes ou que sejam restritas á salas de traidores)

Concordo!

> * [ ]  - Ficar em uma área por mais de 30 segundos. (Observação: não tomar anti-afk não garante que você não esteja quebrando essa regra)

Concordo!

> * [ ]  - Utilizar nomes difíceis de serem lidos, utilizar nomes que sonoramente parecem com outros jogadores. Preferência aos jogadores conectados anteriormente e a moderação do servidor.

Concordo!

> 
> **Detetives:**
> 
> * [ ]  - Dar uma ordem sem ter um taser (zeus) ou revolver no inventário.

Pra deixar claro, é PROIBIDO dar a ordem sem taser certo?

> * [ ]  - Repetir o nome do jogador a cada contagem

Discordo! Acredito que fica melhor se vc apenas falar o nick da pessoa na primeira ordem ou até a pessoa entender que a ordem é pra ela. Do tipo:
Big para 1, Big para 2, Big para 3. Dropa 1, Dropa 2, Dropa 3.
Falar o nick da pessoa completa toda contagem fica muito longo, por exemplo o nick "Tardigrada".

> 
> **Atos de traição:**
> 
> * [ ]  - Ver o jogador utilizando o missil. (Observação: ver o jogador girando a camera é apenas um ato suspeito, salvo em casos que você veja a origem do missil e o mesmo contenha apenas uma rota de fuga.)

Concordo!

> 
> **Mecânicas:**
> 
> * [ ]  - Morrer falando o nome do jogador é apenas um ato suspeito.

Mas se o cara completar o KOS antes de morrer ainda continua sendo válido certo? Se sim, eu concordo!


Acréscimo de regra:
**Gerais:**
> Proibido perseguir na faca um jogador por mais de 1 minuto (dar um aviso antes de matar).

Acho isto necessário, já que temos dois problemas:
- Inocente ficar seguindo na faca acaba não cumprindo objetivo.
- Se tiver 1 INO e 1 T vivo, e o T ficar seguindo na faca, eu sei q é por causa da hit knife, isso anteciparia e daria melhor dinâmica.

**Comment by lhsatsuma** [comment]
Considerar como anti-jogo: Ficar dando KOS incompletos afim de atrapalhar o game.

**Comment by quasemago** [comment]
Escopo foi atualizado com as regras que já foram introduzidas ao servidor.

**Comment by lhsatsuma** [comment]
>Considerar como anti-jogo: Se matar propositalmente afim de não dar chances aos oponentes cumprir o objetivo deles.

Já vi muito cara dando kill no console só pra fazer graça ou pra não deixar alguém matar ele.

**Comment by danielhidalgojunior** [comment]
> - Dar uma ordem sem ter um taser (zeus) ou revolver no inventário.

não concordo, creio que apenas ter a taser deveria permitir dar ordens, afinal vc n está indo testar ninguém com revolver, só ficaria mais fácil pro detetive pedir pra ele parar e meter o tirão de r8 de longe.

**Comment by nil209** [comment]
> > * Dar uma ordem sem ter um taser (zeus) ou revolver no inventário.
> 
> não concordo, creio que apenas ter a taser deveria permitir dar ordens, afinal vc n está indo testar ninguém com revolver, só ficaria mais fácil pro detetive pedir pra ele parar e meter o tirão de r8 de longe.

Detetive ficar dando ordem, somente com taser no inventario.
entao precisa criar um log onde de para ver que o dtt esta cm taser, para isso ser monitorado!?

**Comment by danielhidalgojunior** [comment]
Podemos avaliar com o @quasemago  a possibilidade de deixar explicito e claro que o detetive tem Taser, mas creio até o momento isso está sendo levado pelo bom senso. R8 não é item de teste, logo não substitui o taser. Detetive pode inclusive pegar uma R8 do chão e pedir pro cara parar, como vão saber que se é o item mesmo ou não?

**Comment by nil209** [comment]
O que estou querendo deixar claro aqui, é que se for dtt só puder dar ordem com taser, teremos que ter uma validação, para ajudar no controle.

O intuito é para não ter no game, jogadores questionando o detetive se ele tem taser ou não.

**Comment by danielhidalgojunior** [comment]
Então, mas adicionar revolver como item de ordem não ia resolver esse problema.

Talvez um sprite diferente pro dtt quando ele tem taser? o D fica verde, ou alguma coisa nesse sentido.

**Comment by lhsatsuma** [comment]
Alguém pode opinar nas regras adicionais que eu sugeri?

Regras Gerais:

>Proibido perseguir na faca um jogador por mais de 1 minuto (dar um aviso antes de matar).

Acho isto necessário, já que temos dois problemas:

-  Inocente ficar seguindo na faca acaba não cumprindo objetivo.
- Se tiver 1 INO e 1 T vivo, e o T ficar seguindo na faca, eu sei q é por causa da hit knife, isso anteciparia e daria melhor dinâmica.

Considerar como anti-jogo:
> Ficar dando KOS incompletos afim de atrapalhar o game.

>Se matar propositalmente afim de não dar chances aos oponentes cumprir o objetivo deles.

**Comment by quasemago** [comment]
As duas últimas acho válido, mas a primeira acredito que faça parte da gameplay o T querer trolar seguindo o inocente para encher o saco dele.

**Comment by danielhidalgojunior** [comment]
também concordo com as duas últimas. Sobre kos por seguir de faca, creio que nego ia usar errado e causar os rdm em massa pq matou inocente. Eu tbm n gosto de T que fica seguindo na faca, mesmo quando sabemos que ta vindo com hit knife, mas não acho que essa seria a melhor solução.

**Comment by nil209** [comment]
Basta aplicar punições em jogadores inocentes que ficam seguindo outros jogadores com o intuito de se passar por traitores.

a punição seria por anti-jogo

**Comment by danielhidalgojunior** [comment]
creio que isso já é considerado anti jogo, visto que o inocente não está cumprindo seu objetivo e sim tentando atrapalhar o proprio time.

**Comment by lhsatsuma** [comment]
Bom já que os que comentaram concordam com as minhas duas primeiras sugestões, poderia colocar nas regras para deixar explícito?

**Comment by lhsatsuma** [comment]
Poderia fechar essa issue, visto que não há mais nada a se fazer aqui.
