### ISSUE TITLE
Votemute bugado ?

### ISSUE THREAD

**Issue by lhsatsuma** [quasemago/zrageservers#124]
Hoje dei um votemute num rapaz, a votação foi aprovada e quando trocou de mapa, ele estava conseguindo falar no VoIP tranquilamente.

https://steamcommunity.com/id/NaFloyd/
![image](https://user-images.githubusercontent.com/44283104/77936037-b1a94280-7288-11ea-8ae2-bde0b039ab98.png)

Prevejo dois cenários:
1. O votemute dá um mute temporário. Se for isso, no SB aparece como 30 minutos.
2. O votemute dá um mute de 30 minutos. Se for isso, parece q no jogo ele considera como temporário.

**Comment by alminha021** [comment]
Deve ser o mesmo problema de mutes palicados diretamente pela staff, por algum motivo os mutes estao saindo, 
-  tlvs por conta do admin aplicar "sm_mute alma 30" sem um motivo, entao no server logs aparece mute de 30 min sem um motivo , but pro server foi um mute temporario com motivo "30" , nao sei, teria que testar, ja vi acontecer varias vezes , tem q testar.

**Comment by kobe-hcjordao** [comment]
Isso deve ser problema ao salvar no banco de dados ou no banco de dados em geral, por algum motivo não está sendo carregado o mute.

**Comment by quasemago** [comment]
Isso não começou acontecer depois que os mute dos sv foram separados?

**Comment by alminha021** [comment]
pra mim começou quando mudou as parada do mute , agora mute temporario tem q ser -1 , os mute tem q ter um motivo , e agora mostra no sourcebans . Messa epoca que começou.

Se foi nesse periodo que os sv foram separados, entao pra mim , sim começaram ai

**Comment by quasemago** [comment]
Esqueci de atualizar esse issue. Problema já foi fixado.
