### ISSUE TITLE
[ZE] Bloquear skins ze_FFXII_Westersand_v7_z9

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#127]
Com update recente do plugin de facas é necessário matar as facas do mapa. O bug delas ficarem inviseis ainda acontece. Criando o issue para não me esquecer.

**Comment by gabrielacms** [comment]
Vi o infused comentando ali de outro mapa que era bloqueado na EW e estava dando para pegar também por conta da faca. Será que o melhor não seria remover via stripper esses casos?

**Comment by hcjordao** [comment]
Sim criem os issues dos mapas que eu vou remover via stripper

**Comment by hcjordao** [comment]
Ja abri um PR para remover essas skins. Só mergear e fazer o update no server.

**Comment by quasemago** [comment]
Já foi dado merge no server.

**Comment by hcjordao** [comment]
Testado e ja foi resolvido
