### ISSUE TITLE
[ZE] Bug - ze_infiltration_final_r1

### ISSUE THREAD

**Issue by Matsucake** [quasemago/zrageservers#131]
Estávamos jogando o mapa e foi descoberto que a parte inferior do helicóptero pode ser varada por ZM, e como o helicóptero e voa baixo fica bem difícil de dar um over pra evitar isso.
https://i.imgur.com/Ux7i1H5.jpg

**Comment by lucaslinha** [comment]
Infelizmente não tem o que fazer, clip(famosa parede invisivel) não pode ser adicionada sem recompilar o mapa, esse tmb não é o unico mapa com isso, na maioria a solução é encostar na parte de tras do helicoptero e atirar.

**Comment by quasemago** [comment]
Da para adicionar sim um playerclip via stripper, basta reaproveitar uma geometria existente.

**Comment by lucaslinha** [comment]
Serio ? pra mim stripper so conseguia adicionar entidades.

**Comment by hcjordao** [comment]
Consegue adicionar qualquer coisa, mas tem que pegar o tamanho de uma parede ja existente, o tamanho vai ficar igual. É meio chato de testar isso dai só. Consideraria isso dai a mesma coisa que é como no elevador do surf sahok, existe paciencia mas da pra ganhar como humano de boas, pq da pra entrar no heli depois que ele sobe

**Comment by lucaslinha** [comment]
Eu ainda tenho minha duvidas disso ai, clip é uma textura, nunca vi na minha vida alguem falar que pode adicionar uma textura com stripper, mas se tiver como, so passar um exemplo que eu faço.

**Comment by quasemago** [comment]
Como eu disse anteriormente, você ira precisar reaproveitar uma geometria existente visto que nao é possivel definir isso via stripper.

Basta olhar os nossos strippers contendo o parâmetro "model".
E.g:
```
add:
{
     "classname" "trigger_once"
     "model" "*134"
}
```

**Comment by quasemago** [comment]
Mas precisa ver se clip é possível mesmo, de qualquer forma dá para adicionar uma wall que resolve o problema.

**Comment by lucaslinha** [comment]
Esse é o problema, é um world brush + textura, como que se adquire o parametro model de um world brush ?

**Comment by quasemago** [comment]
Você precisa fazer um dump com o stripper, no meu mako ex3 eu criei varios brushs desse jeito.

**Comment by hcjordao** [comment]
Cara ao meu ver isso aqui é parte dos humanos de def antes de entrarem no helicoptero. Esse tipo de bug sempre existem em coisas se movimentam incluindo elevadores.

Exemplo surf sahok onde tu consegue varar o pé do humano quando elevador  e/ou random que tu consegue varar o humano por trás do ele tbm.
