### ISSUE TITLE
[ZE] Melhorias líder

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#133]
Minha proposta

- [ ] Melhorias no lider marks issue: #116 

- [ ] Reduzir o número necessário para o jogador se tornar líder. Atualmente 6, reduzir para 3 ou 4.

- [ ] Remover todos os jogadores da whitelist de lideres atualmente, adicionar um canal em nosso discord onde um jogador pode dar um +rep a um jogador e com um minímo a ser decidido liberamos essa feature. Similar ao report.

- [ ] Dar a opção a staff de event managers para entregar a tag do mapa em caso assim aprovarem.

- [ ] Adição de um item na pontuação de mapas (assim podemos controlar quais mapas isso é valido e não qualquer um) onde caso haja um lider (acho que o mesmo pode ser feito para mapas level 4* para cima, para top defenders, para top defenders apenas uma porcentagem especificada na .cfg) e o round for ganho o lider ganhará uma porcentagem extra de pontos do mapa. Incentivo aos jogadores a tentarem liderar e zerar outros mapas. Para isso é necessário que haja propaganda para o servidor para que os jogadores tomem conhecimento disso.

- [ ] Adicionar o comando -rep, caso o jogador receba um número X de reps negativos, que seja adicionado a blacklist de lideres. 

PS: Acharia interessante se esse sistema de rep fosse salvo para privar jogadores de votarem nos mesmos jogadores. Caso o jogador tentasse votar em um mesmo jogador apareceria uma mensagem no servidor falando que o mesmo ja opiniou sobre X jogador.

Edit 1: Atualizado com as revisões do alma e sunshine

**Comment by gabrielacms** [comment]
Gostei da 1° 2° 3° e 5° sugestão. Teve algumas coisas da questão da tag para líder que eu não concordei mt. 
* "Não será uma obrigação ser entregue [...]" Eu particularmente não curto isso. Para mim ou entrega em tudo ou não entrega em nada. Isso ai é praticamente desfazer das lideranças em mapas mais fáceis. Ex: Insensible. Vi muita gente falando "ah o mapa é fácil etc etc"mas ninguém ali conhecia o mapa. Se não fosse o líder com certeza teria demorado bem mais para zerar ou nem teria zerado. 
* "Necessidade de um event manager [...]" Ta
* "Lider não pode ser tóxico [...]" Concordo
* "Deve ter sido destaque no mapa [...]" Isso depende. Muitas vezes alguém está dando a call vira zm e outra pessoa assume a liderança ou tenta guiar o time. Se isso ocorrer, a pessoa vai perder a chance de ganhar a tag? E também teria que liberar o !spec com isso. Porque dar call como zm é praticamente dar uma call torta já que voce não terá noção do que o time CT está fazendo.
* "Call impecável é o mínimo [...]" Para mim isso não deve entrar como condição. Concordo que uma ótima liderança é a que o líder sabe o tempo de tp, call do mapa etc. Mas pode ocorrer do cara confundir ou esquecer algo. Tem que levar em consideração que o servidor só joga mapa difícil em evento. Se o cara ver que vai cair mapa X e tentar aprender antes, isso para mim já é ótimo. Isso me lembra frostdrake. Pessoal dando uma ótima call no mapa mas só pq erraram a direção de 1 dos ataques do boss, povo caiu em cima. Ó já perdeu a tag.

**Comment by hcjordao** [comment]
Podemos deixar tudo desse item como subjetivo tudo e deixar a decisão a prol da staff de event manager, se a maioria decidir em entregar a 1/2/3 jogadores que deram a call em evento pronto. Acho até melhor mesmo pq adicionar regra vai fazer o jogador ficar cobrando depois.

**Comment by alminha021** [comment]
concordo com 1, 2, 3

a 4 nao ficou claro.
considerando a "tag do mapa " ser a mesma que vc ganha ao zerar o mapa:
não concordo com a 4 , pra mim para ganhar a tag tem q ganhar o mapa.
na realidade sou contra a 4 em todas as hipóteses. 
Se querem dar tag, que seja uma tag de leader e q ela vai upando de acordo com a +rep do lider
[ Leader 1✪ ] 
chega em um rep ele vira [ LEader 2✪] ... [ LEader 5✪] ... [ LEader 4✪]
agora tag do mapa? se perdeu, perdeu. 
simples

considerando "tag do mapa" ser diferente da de vc ganahr o mapa:
Concordo com a gabi, ou entrega ou nao entrega , ha casos e casos. 


no caso da 5 , como esta envolvendo pontos , tem passar a ser rigoroso com o os ladrao de leader. Se tem um cara dando call certa mas o time morre,  e ja no inicio do round seguinte alguem pega o !leader pra dar call e pegar ponto, eu ja sou contra.
Se tem um cara liderando eu naoq uero outros babano pra pegar leader.

**Comment by kobe-hcjordao** [comment]
o !leader só seria recebido com o +rep do servidor, se for observado é so dar blacklist, vou botar a reformulação dos itens com um edit.

**Comment by gabrielacms** [comment]
É ou talvez não dar a tag como o alma citou. Para mim isso da tag pode dar mais dor de cabeça para a gente do que incentivar. Pq tem muito porém nisso ai. E como sabemos que há muito fagger de tag no servidor isso ai pode gerar tretinha se alguém pegar o líder de outro. E sobre os pontos eu não tinha pensado por esse lado. @alminha021

**Comment by hcjordao** [comment]
Sobre isso de roubar lider de outro, adicionei uma opção de -rep para jogadores tbm para os mesmos serem adicionados a blacklist, além do que o jogadores que não estão na whitelist tem que ser votados para serem lideres, acho meio dificíl de roubar pontos. Pode ser adicionado uma condição para caso o lider morra os pontos não serão mais entregues além de uma outra verificação que o jogador deve virar lider no primeiro minuto do mapa caso contrário também não ganha pontuação

**Comment by alminha021** [comment]
Resumindo, pra mim,  envolver Tag e ponto so vai dar dor de cabeça.

essa Tag que o lider ganha ser igual a tag que o time ganha ao ganhar um mapa = Sou contra.

essa Tag de leader ser , por exemplo, [ Leader 2✪] , e ela ser upada somente por +Rep, ai dah pra pensar, se eu vejo um cara pegando leader na frente de um cara que ta liderando , ja vai tomar um -Rep gigante + addblacklist.


> Sobre isso de roubar lider de outro, adicionei uma opção de -rep para jogadores tbm para os mesmos serem adicionados a blacklist, além do que o jogadores que não estão na whitelist tem que ser votados para serem lideres, acho meio dificíl de roubar pontos. Pode ser adicionado uma condição para caso o lider morra os pontos não serão mais entregues além de uma outra verificação que o jogador deve virar lider no primeiro minuto do mapa caso contrário também não ganha pontuação

Problema eh que tem um cara dando call certinha mas o time morre a toa, e no inicio do round seguinte um terceito da !leader e pega começa a liderar, isso ja eh roubar ponto, ta ligado? Cara correu pra pegar leader na frente do outro que estava passando call certinha.

Por ponto e tag os caras acabam até as amizades, pra mim eh inviavel ponto e tag se nao for totalmente controlado e rigoroso,

**Comment by hcjordao** [comment]
Mas ai pra isso que tem o report + demo + admin. Só vai ter que ter essa função extra por nossa parte de verificar isso, sobre a tag de lider pode ser, mas ao invés de ser por +rep que pode ser farmado por gente falando pra novato escrever isso no chat, melhor a staff de eventos adicionar isso manualmente, se o cara merecer upa a tag de lider algo do genero acho melhor mesmo ao inves de dar tag do mapa

**Comment by danielhidalgojunior** [comment]
tirando a parte de dar tag, gostei da ideia no geral.

Prefiro que esse rep seja ingame e ocultar o nome dos que votaram pra evitar picuinhas sobre quem votou positivo ou negativo em quem.

**Comment by lucaslinha** [comment]
Gostei das tags por reputação, os outros de ponto e tal so alimenta os ratos de lider. E @hcjordao ja tem uns 40 issue de lider, seria bom juntar tudo não ?

**Comment by lpcorrea** [comment]
Curti a ideia da reputação pra ter mais pessoas com o comando próprio, sempre que tem alguém liderando eu pergunto se quer que coloque de líder mas sempre negam, talvez com isso eles se animem.

Por parte de tag acredito que vai dar problema, apesar de ter poucas pessoas que liderem atualmente pode causar intrigas, por mim para manter deve ser contabilizado apenas reputação.

"Remover todos os jogadores da whitelist de lideres atualmente [...]" sem exceções? Ex: Pastor, está sempre online e lidera quase todos os mapas (apesar de ser um pouco tóxico as vezes temos que concordar que é um bom líder)

**Comment by hcjordao** [comment]
Movido para #143
