### ISSUE TITLE
[ZE] Tag Rework - Sugestão v1.2

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#134]
## Tags: 
- Jogadores ganhariam sua tag/evolução de tag automaticamente:
  - Ao ganhar o último level o jogador teria seu progresso no mapa upado (+1).
  - Cada mapa teria seu número de mapas para essa tag ser evoluída ao chegar no limite jogador recebe a tag automaticamente. 
  - Ao passar no limite, uma mensagem + um som seria tocado:
    -  **[Tags] Fulano recebeu a tag [Fapescape Elite]!**
    - **[Tags] Fulano upou sua tag para [Fapescape Veteran]!**

**__Exemplo de Definição__**
Mapa | Elite | Veteran | Pro | Legend | God
--- | --- | --- | --- | --- | --- |
Fapescape | 1 | 3 | 6 | 12 | 24 |
Skyrim | 3 | 6 | 12 | 24 | 48 |
Jurassic Park (Exemplo p/ mapas super fáceis) | 1000 | - | - | - | - |
Aesthetic | 1 | 2 | 3 | 4 | 5| 

## Comandos necessários para o rework ficar interessante:
- **!helptags**
  - Menu informativo de como funciona o sistema de up de tags.

- **!maptags**
  - Menu informativo com as tags do mapa junto com o quanto é necessário para receber a tag de acordo com a tabela definida acima.

- **!mytags** 
  - Menu informativo que possui as seguintes informações
    - Informação do número de tags que o jogador possui
    - All Tags - Abre um menu com a listagem de todos os mapas em que o usuário possui uma tag, ao clicar em um dos mapas exibe no chat seu nível atual de tag, o próximo nível da tag e quantas vezes é necessário para chegar a esse nível.
    - Current Map progression - Faz a mesma coisa do que foi falado em cima mas do mapa atual.
    - Automatically equip map tags - Config que permite que a tag do mapa atual do usuário seja equipada automatica ao entrar/trocar de mapa

- **!tags \<nome do jogador\>**
  - Mesma funcionalidade do comando !mytags mas para ver as tags de um outro jogador conectado no server atualmente.

- **!toptags**
  - Abre um menu com 3 opções:
    - Top 20 Global -  jogadores com tags global
    - Top 20 Online - jogadores com tags local (no server online no momento)
    - Top 20 Growth - jogadores que mais ganharam tags nos últimos 30 dias

- **!bettag \<número de tags a serem apostadas (número par)\>** (Vip only e Cooldown de uma vez ao dia - Apenas em mapas difíceis)
  - Inicio do round do último level jogador tem 20 segundos para usar o comando.
  - Aposta um número par do seu progresso de tags para caso o jogador ganhe o level ele ganhe metade do valor, entretanto perder resulta no mesmo perdendo o número apostado, podendo retroceder o nível de tags. Exemplos:
    - !bettag 2 - Caso jogador ganhe o mapa ele vai ganhar 1 (ganho normal) + 1 (pela aposta), caso perca ele irá perder 2 no progresso de sua tag.
    - !bettag 10 - Caso jogador ganhe o mapa ele vai ganhar 1 (ganho normal) + 5 (pela aposta), caso perca ele irá perder 10 no progresso de sua tag.
  - Caso o jogador ganhe aparecerá no chat um display avisando o quanto ele ganhou no progresso. **[Tags] Fulano apostou 4 de progresso para zerar o mapa e ganhou! Fulano recebeu +3 de progresso em sua tag**
  - Caso o jogador perca aparecerá. **[Tags] Fulano apostou 10 de progresso para zerar o mapa e se fudeu! Fukano perdeu tudo! Boa sorte próxima vez**
  - Essas mensagens acima devem aparecer apenas no fim do round e não no início para o time não trolar para ferrar com o jogador que apostou.

- **!tagstatus**
  - Consulta se o mesmo está banido de obter tags

## Admin Commands

- **!bantags \<nome do jogador\> \<tempo\> <\motivo\>**
  - Remove o jogador de obter tags no servidor por um tempo dentro do server.
  - Útil se temos jogadores que tão sendo pesados e não ajudando o time em evento 🤣 

- **!tagmultiplier \<multiplicador inteiro\>**
  - Admin seta quanto uma vitória no mapa vai valer. O default seria um mas em eventos poderiamos setar x2 x3 x4 x5 dependendo da configuração do evento.

- **!disabletags**
  - Desativa a contagem de vitórias caso o admin queira fazer algo para skippar o mapa ou ensinar o mapa.

## Cvars Commands

- **zrage_tag_minimum_players**
  - Diferente do rank onde podiamos ter 6 jogadores, tags ao meu ver só fazem sentidor entregar com no mínimo 20 jogadores no servidor

- **zrage_enable_event_tags**
  - Ao ativar a cvar de evento o jogador irá upar automaticamente para o próximo nível de tag, mantendo seu número de vitórias atuais.
    - Exemplo 1: Jogador com tag Elite (11/20), ao zerar o mapa o progresso da tag do jogador irá para 31. 20 para a Tag Veteran + 11 do progresso atual do mapa.
    - Exemplo 2: Jogador com tag Veteran (125/250), ao zerar o mapa o jogador irá para 375. 200 para a Tag Pro + 125 do progresso atual.

## Mudanças no server necessárias para que isso ocorra:
- Combos de Mapa:
  - Tags de combo de mapas serão entregues por fora.
- Rank não existirá mais já que não faria mais sentido isso.
- Remover benefício do vip de criar tags customs. A tag do server tem que ser valorizada e o beneficio do vip quebra muito isso. Prefiro vender tags cosméticas.

## Pontos negativos do plugin:
- Trabalhoso para montar devido escopo:
  - Escopo de código @quasemago
  - Escopo de arquitetura do banco de dados @danielhidalgojunior
  - Escopo de criação de tags e configs @hcjordao , @gabrielacms e @lucaslinha
- Transferência das tags atuais existentes para o novo sistema. @hcjordao e @gabrielacms

## Futuro que pode ser usado se esse plugin for feito:
- Integração com o Discord, já que podemos conectar com o webservice e acessar o banco de dados.
- Com o banco de dados de jogadores e mapas feitos poderiamos criar outros tipos de tags como por exemplo número de mapas já ganhos. Se sabemos o número atual de mapas existentes e sabemos quantas tags o jogador possui podemos saber a porcentagem de mapas zerados do jogador e exibir no tab um [Iniciante], [Novato], [Experiente] como nos servidores de surf.
- Pode ser anexado junto ao jogador o total de dano causado em todos os mapas jogados e entregar tags por dano causado a zumbi. 
- Podemos salvar quantas vezes o jogador foi top defender e entregar uma tag quando atingir X

**Comment by hcjordao** [comment]
É apenas uma sugestão inicial (v 1.0.0) deve ter coisas mais interessantes que eu não pensei e que podem ser atreladas

**Comment by hcjordao** [comment]
É uma sugestão inicial como o nome sugere v1.0, deem opiniões e criticas para modelarmos uma nova até ficar de uma forma boa. Tem que ver com o @danielhidalgojunior e com o @quasemago o que é e não é possível. Mas diferentes dos outros reworks que tivemos gostariamos que estressasemos isso até o talo para não termos arrependimentos futuramente.

**Comment by danielhidalgojunior** [comment]
very good.

tudo é possível. Me disponho a desenhar as tabelas do banco caso necessário.

**Comment by lpcorrea** [comment]
Quem tem tag hoje terá ela resetada? Ou existe a possibilidade de dar uma tag especial pra essas pessoas? (como era feito manualmente creio eu que não tenha como)

De resto estou de acordo com tudo, muito bem feito.

**Comment by kobe-hcjordao** [comment]
Então a ideia é transferir as tags existentes hoje para o novo modelo 

> Transferência das tags atuais existentes para o novo sistema. @hcjordao e @gabrielacms

Tem que ver como fazer depois que criar a parada, mas sim essa a ideia

**Comment by kobe-hcjordao** [comment]
fanzack minha duvida seria se ficaria muito load heavy no server para entregar uma tag, tipo skyrim, 18 pessoas zeram tem que fazer as validações de up de tag para as 18 pessoas no banco de dados. Ficaria muito pesado para fazer isso na transição de um round pra outro?

**Comment by danielhidalgojunior** [comment]
não conheço o contexto de desempenho de consultas via sp para o mysql, mas usando como base tudo oq ja trabalhei relacionado a aplicacao+db, não demoraria nem microsegundos pra fazer isso.

**Comment by danielhidalgojunior** [comment]
Creio que o mysql tbm suporta bulk insert, então todo round seria apenas uma instrução relacionada a mapa zerado que seria enviada pro mysql

**Comment by quasemago** [comment]
Portanto as tags não serão mais integradas ao Store nesse sistema. Não entendi seu "Exemplo de Definição" @hcjordao, o que significa aqueles números?

@danielhidalgojunior Uma duas tabelas seria o suficiente, uma para os mapas e outra para os players.

Tabela dos mapas:
```
+--------+--------------+------+-----+---------+----------------+
| Field  | Type         | Null | Key | Default | Extra          |
+--------+--------------+------+-----+---------+----------------+
| id     | int(11)      | NO   | PRI | NULL    | auto_increment |
| map    | varchar(254) | NO   |     | NULL    |                |
| tags   | varchar(254) | NO   |     | NULL    |                |
| points | varchar(128) | NO   |     | NULL    |                |
+--------+--------------+------+-----+---------+----------------+
```
Exemplo de insert:
`1 | ze_Pirates_Port_Royal_v5_6 | [Pirates Elite],[Pirates Veteran],[Pirates God] | 1,2,6`

A tabela dos players salvaria apenas o steamid e os pontos que ele possui para dar fetch in-game.

**Comment by kobe-hcjordao** [comment]
@quasemago o número de vezes que um jogador precisa zerar o mapa para ganhar o up de tag.

Pegando Skyrim e Aesthetic, para o Skyrim é necessário zerar o mapa 3 vezes para ganhar a tag [Skyrim Elite], entretanto para Aeshtetic como é um mapa 10x mais difícil é necessário apenas uma vitória.

**Comment by quasemago** [comment]
Hm, então esquece a parte de salvar os pontos na tabela do player que eu citei na minha resposta anterior. Vai ser necessário ter uma tabela com todos os mapas para o jogador.

Tabela:
```
+---------+--------------+------+-----+---------+-------+
| Field   | Type         | Null | Key | Default | Extra |
+---------+--------------+------+-----+---------+-------+
| steamid | varchar(32)  | NO   | PRI | NULL    |       |
| map     | varchar(128) | NO   | PRI | NULL    |       |
| points  | int(11)      | NO   |     | NULL    |       |
+---------+--------------+------+-----+---------+-------+
```
Insert:
`[STEAMID] | ze_Pirates_Port_Royal_v5_6 | 22`

**Comment by kobe-hcjordao** [comment]
Eu tinha conversado com o fanzack no voip e ele disse que era melhor separar no maior número de tabelas possiveis.

- **Tabela Jogadores**
  - ID Jogador
  - STEAM_ID Jogador
  -  IP Jogador
  - Outra info util do jogador

- **Tabela Mapas**
  - ID do mapa
  - Nome do mapa

- **Tabela de vitórias**
  - ID da vitória
  - ID do jogador que ganhou
  - ID do mapa zerado

- **Tabela de Tags** (Acho que tinha essa também não lembro se as tags eram definidas na tabela de mapas ou em uma separada)

Não lembro mais o que ele falou mas ele esquematizou umas 3, 4 5 tabelas para separar o trabalho e deixar mais otimizado. Tem os motivos lá.

**Comment by quasemago** [comment]
No meu exemplo vai ser necessário 3 tabelas como eu citei acima.

- **Tabela jogadores**
  - ID [auto increment]
  - steamid do jogador
  - tag atual do jogador equipada

- **Tabela Mapas**
  - ID do mapa [auto increment]
  - nome do mapa
  - tags do mapa
  - pontos necessários para as tags

- **Tabela Vitórias**
  - steamid do jogador
  - id do mapa
  - vitórias naquele mapa

**Comment by kobe-hcjordao** [comment]
Temos que pensar nesses casos também:

- **Versões de mapas diferentes**
  - Caso 1: Versões diferentes mas muito similares. Contabilizam para a mesmo progresso de tag.
  - Caso 2: Versões bem diferentes de mapa (Wester v2, v7 e v8, Wandererers v2, v4 e v5, mako v5 e v6, cosmo v1 e v5) como funcionaria o esquema das tags?
    - Tags diferentes para cada versão? Se sim, como deixariamos elas?
    - Botar para fora do nominate as versões antigas mas elas ainda contabilizam para o mesmo progresso de tag do mapa?
    - Game over para mapas com versões antigas. Eles são apenas 4 fun. Caso tenha um update de mapa só renomear o banco de dados para a nova versão mas as antigas não contabilizam para tag mais?

Isso é meio dificil de decidir e temos que ver como funcionaria no BD

**Comment by danielhidalgojunior** [comment]
Podemos sentar e montar a estrutura de tabelas juntos. É bom montar pensando em permitir que implementaçoes de novas funcionalidades não necessitem modificação drásticas na estrutura inicialmente definida.

Deveríamos separar os contextos e seguir algumas normas de design de bases relacionais. Como por exemplo, tags deveriam ter sua própria tabela e não estar a ocoplada na tabela de mapas.

**Comment by gabrielacms** [comment]
@hcjordao Eu gostei bastante de como foi apresentada essa ideia. Se der para fazer como voce projetou ai vai ser bem interessante para o servidor. 

Só tenho algumas dúvidas e algumas coisas para comentar: 
- Pelo o que eu entendi isso seria habilitado o tempo inteiro e somente durante os eventos seria desabilitado, correto? Já que como voce citou o evento não daria mais tag, enfim, eu acho que o evento poderia sim continuar dando tag. É que para mim não faz muito sentido eu poder ganhar a tag do Fapescape por exemplo digamos assim "a semana inteira" e somente durante o evento eu não poder ganhar. Tem que levar em consideração que existem pessoas que só conseguem jogar no fds ou que gostam de jogar somente o evento

- Outras coisas teriam que mudar também como a questão de alterar mapa para o último level, com a  implementação desse sistema ao meu ver seria fora de cogitação colocar o último level de qualquer mapa. 
- A questão do vip: Eu acho muito legal isso de dar vip é bem atrativo. Só que temos 2 tipos de evento no sv. O tryhard e o evento. Como ficaria isso? O tryhard também daria vip? Se sim, se eu ganhasse o tryhard no sábado e o evento domingo, ficaria com 2 semanas de vip?

**Comment by kobe-hcjordao** [comment]
> * Pelo o que eu entendi isso seria habilitado o tempo [...]

Os eventos dariam os prêmios normais falados lá na sugestão, vips ou skins. O plugin de tag automatica ainda estaria funcionando, portanto se o jogador ganhar o mapa ele pode ganhar um progresso de +1 na tag. 

O que pode ser feito em eventos para manter os mesmos atrativos é uma configuração de admin que ao ser ativado possibilite que o jogador ganhe 2x/3x/4x o progresso no mapa. 

> * Outras coisas teriam que mudar também como a questão de alterar [...]

Concordo e não tinha pensado sobre isso. Uma regra nova para a administração + um comando que desativa o plugin durante o mapa é o suficiente para isso. Antes de setar o último level seria necessário desativar o progresso de rank. 

> * A questão do vip: Eu acho muito legal isso de dar vip é bem atrativo [...]

Pra mim o tryhard ficaria sem nada, é como eventos mas não da nenhum prêmio só a oportunidade do pessal incrementar seu progresso de tags com um time bom e a ajuda da administração para garantir smooth gameplay através da rigidez durantes os mesmos.

**Comment by alminha021** [comment]
So manter uma logica simples, sem incrementar a quantidade necessaria de upar uma tag de um nivel para outro. 
exemplo:
-Se precisa de 10 vitorias pra upar a tag pra elite, depois vai precisar de mais 10 vitorias (precisando de 20)
exemplo:
- se precisa de 1 vitoria pra tag elite, proximo nivel tbm eh + 1 vitoria ( precisando de 2)

Mantendo sempre a mesma margem de vitoria, basta colocar para o evento recompensar com X vitorias ( depende do mapa , o quanto eh necessaria pra um up)
ex: 
se pra elite precisa de 10 , e veteran + 10 (20)
Um evento ira recompensar com 10 vitorias nesse caso

No caso de um mapa elite ser 1000 , e veteran +1000 (2000 no total)
Um evento nesse mapa ira recompensar com 1000 vitorias

Deve da pra integrar no !startevent , pra ele pegar a quantidade de vitorias q precisa pra 1 up e dar para os vitoriosos.

**Comment by gabrielacms** [comment]
> Pra mim o tryhard ficaria sem nada, é como eventos mas não da nenhum prêmio só a oportunidade do pessal incrementar seu progresso de tags com um time bom e a ajuda da administração para garantir smooth gameplay através da rigidez durantes os mesmos.

Beleza. Mas ainda focando no Evento em si, cada mês tem cerca de 4 domingos e vamos supor que nos 4 domingos só rolem mapas de nível difícil para cima e que o servidor **ganhe** todos eles (Ex: l0v0l, paramina, ridorana e tirith), onde a recompensa inicial seria Vip Standard para mapas médios e Vip Pro para mapas difíceis; será que seria worth para o servidor bancar essa quantidade de vip?
Serão 7 dias só mas pode ocorrer do jogador ganhar evento seguido e por ai vai. GFL e GUC por exemplo, dão vip como recompensa só que eles não fazem evento semanal que nem nós fazemos. Penúltimo evento da GUC ocorreu em janeiro e o último ocorreu só agora em Março. E a GFL nem todo evento que ela faz, ela dá vip. Para mim, ou diminui a quantidade de eventos que vai rolar no mês (o que seria ruim ao meu ver para o sv) ou descarta essa possibilidade de dar vip baseado na dificuldade do mapa e deixa a Skin como recompensa padrão e o vip sendo apenas exceções.

**Comment by lucaslinha** [comment]
> Os eventos dariam os prêmios normais falados lá na sugestão, vips ou skins. O plugin de tag automatica ainda estaria funcionando, portanto se o jogador ganhar o mapa ele pode ganhar um progresso de +1 na tag.
Bom o proposito disso é fazer a galera se interessar por mapas dificeis não so apenas em eventos certo ? porém isso so vai aumentar ainda mais a dependencia ou a ganancia deles por eventos, ja que vai ser vip + tag nos eventos, como eu ja tinha dito antes, enquanto a recompensa dos eventos for melhor que a recompensa dos dias normais, ainda vão preferir os eventos e consequentemente ficar dependente deles.  Por mim separar a tag do vip ja seria uma grande avanço, agora colocar os 2 juntos no evento so piora a situação.

**Comment by hcjordao** [comment]
> So manter uma logica simples, sem incrementar a quantidade necessaria de upar uma tag de um nivel para outro[...]

Sinceramente, pensei antes mesma coisa de ser incrementado com o mesmo número de mapas, acho ruim por que ao meu ver tem que ser difícil de ganhar o mapa, o cara muito bem pode farmar uma tag de um mapa em 2 meses, pra mim tem que dar progressão pro cara no servidor para tempo, jogar um ano no server para conseguir uma das tags upadas pro God isso jogando o mapa com uma certa frequência. A ideia é dar conquistas pro jogador conseguir.

Acho que isso junta muito com o que a Gabi falou de dar um bonus de tags durante evento, assim manteriamos o evento como estão atualmente sem ter que mexer muito. Entretanto acho ruim esse esquema de dar 50 vitórias pois o jogador jogou no evento e ganhou no evento. Um bonus pode ser dado x vezes o valor.

> Pra mim o tryhard ficaria [...]

Acho que o que falei acima se encaixa nisso. Evento com bonus de recebimento de tag (os mapas contam mais vitórias), e deixa por isso acho que o esquema de vip e tal podemos manter como fazemos atualmente, talvez darmos vip mais frequenta já que não existirá mais rank.
 
> Bom o proposito disso é fazer a galera se interessar [...]

Segue a mesma coisa que eu sugeri, tu não vai ganhar uma tag em si mas sim um pouco extra de progresso.

**Comment by danielhidalgojunior** [comment]
> So manter uma logica simples, sem incrementar a quantidade necessaria de upar uma tag de um nivel para outro[...]

Podemos implementar um sisteminha de peso em cada vitória, onde jogar normalmente no dia a dia te dá 1 ponto ao zerar (considerando um mapa que precisa de 30 pontos para ganhar a primeira tag, por exemplo). Quando for evento ou tryhard, o admin pode mudar o peso da vitória para qualquer valor, inclusive para 30, o que faria os vencedores ganharem a tag ao zerar o mapa uma única vez.

**Comment by hcjordao** [comment]
@danielhidalgojunior 
> Podemos implementar um sisteminha de peso em cada vitória [...]

Acho ruim foi o que eu falei antes, pois isso dai vai fazer a progreção ficar cobrada, acho que o evento poderia dar uma juda mas não dar uma tag completa pro cara.

**Comment by hcjordao** [comment]
Fiz um update para uma versão v1.1 com as sugestões dadas na parte de Admin commands e Cvars com o que eu achei pertinente, o que eu não achei interessante argumentei nos meus comentários acima.

Tinhamos que marcar um tempo esse fim de semana na sala penthouse para discutir isso:
@quasemago, @danielhidalgojunior , @gabrielacms , @alminha021 , @lucaslinha , @lpcorrea 

Obrigado :)

**Comment by quasemago** [comment]
Sei lá, acho que vai tirar muito a importância dos eventos já que tags vai ser possível ganhar jogando durante toda a semana.

**Comment by hcjordao** [comment]
Você também acha então que ganhar durante um evento deveria upar automaticamente para o próximo nível como os outros disseram?

**Comment by lucaslinha** [comment]
> Sei lá, acho que vai tirar muito a importância dos eventos já que tags vai ser possível ganhar jogando durante toda a semana.
Rapaz se não for facil o farm, vão continuar dependendo de "time de evento" pra conseguir tag.

**Comment by lucaslinha** [comment]
Faz igual falaram antes, evento 1/2 vezes por mes com vip e tal, tryhard continua mesma coisa ja que ele ta sempre apresentando mapas poucos jogados e de resto se o cara quiser conseguir sua tag que va aprender o mapa e carregar o time, se vira, negocio de ficar esperando fds pra poder jogar pq tem confiança 0 em tudo.

**Comment by alminha021** [comment]
Não vejo sentido em mudar o evento, ta funcionando direitinho , maioria das vezes ta lotado.
Tem gente que so pode jogar nos fds , e o evento eh o melhor horario pra se jogar mapas difíceis, nao vejo o porque prejudicar esse pessoal ou mudar a forma como esta ocorrendo o evento.

**Comment by alminha021** [comment]
eh o mesmo que comprar o mibr que so estava com o coldzera carregando o resto, e no dia seguinte vender ele e colocar mais caras duvidoso no lugar.
Tem que ajustar o resto, quem tafazendo sua parte naotem porque sofrer mudanças

**Comment by hcjordao** [comment]
A minha unica duvida é saber o que vcs preferem:

Base dos exemplos:
Skyrim
Jogador Fulano -> Nivel da tag 13/20 (Elite -> Veteran)

- Opção 1 (Somente somar a tag) 
  - Multiplicador de eventos faz o cara conseguir 4 vitorias ao inves de uma.
  - Final ficará Fulano 17/20

- Opção 2 (Incrementar até o proximo level)
  - Ao ganhar Fulano ficará com 20/20, upando a tag para Veteran automaticamente

- Opção 3 (incrementar o número até a tag + a vitórias atuais)

**Comment by hcjordao** [comment]
A minha unica duvida é saber o que vcs preferem:

Base dos exemplos:
Skyrim
Jogador Fulano -> Nivel da tag 13/20 (Elite -> Veteran)

- Opção 1 (Somente somar a tag) 
  - Multiplicador de eventos faz o cara conseguir 4 vitorias ao inves de uma.
  - Final ficará Fulano 17/20

- Opção 2 (Incrementar até o proximo level)
  - Ao ganhar Fulano ficará com 20/20, upando a tag para Veteran automaticamente

- Opção 3 (incrementar o número até a tag + a vitórias atuais)
  - Ao ganhar Fulano ficará com 33/20 (20 para upar a tag para Veteran + as 13 vitórias que o mesmo ja possui.)

**Comment by lucaslinha** [comment]
> Não vejo sentido em mudar o evento, ta funcionando direitinho , maioria das vezes ta lotado.
> Tem gente que so pode jogar nos fds , e o evento eh o melhor horario pra se jogar mapas difíceis, nao vejo o porque prejudicar esse pessoal ou mudar a forma como esta ocorrendo o evento.

Ue mas como vai prejudicar se você vai ter a chance de ganhar as tags do mesmo jeito com esse plugin no mesmo horario que acontecia o evento ? Provavelmente pq eles so se esforçam em um evento, é isso ? Dai vai ficar impossivel ganhar as tags ?

**Comment by alminha021** [comment]
pro fulano ta com 13 vitorias, duvido que aceitem ele nominar o mapa vanilla para evento, vao cobrar config add.

Opçao 3 unica justa ai.

opçao 1, preciso comentar? nao da pra compara o skyrim full skin com o evento so permitido pistola e skin bloqueada

opçao2 , cara tem 19 vitorias, vai pra 20? mei bosta

**Comment by alminha021** [comment]
Evento que eu saiba tem um tempo de duração maior com deadline, acabar o tempo total e o admin aumentar o tempo que eu saiba nao da tag. Vai ser divertido fazer 8/0 e acabar o tempo e o extend do harrypotter e ninguem ganahr tag.

Querem reduzir pra 2 fds evento? tem mapa ai que precisa da config de evento por conta do tempo, ou vao colocar 90min sempre que cair mapa dificil? kkk

Nao vejo porque reduzir os eventos pra 2 por mes. Nao dou a minima se o cara so se esforça nos fds , tem uma galera que so entra na sexta ate domingo. Uma das poucas paradas que a galera gosta , por isso ta sempre lotado fds

Vcs tao achando que colocar isso dai vai fazer os cara jogar harrypotter , diddle , santassination 14:00 de uma terça feira , eu nao vejo mudando nada, vejo muita tag shroom god aparecendo, so isso, de resto? vai ficar igual.

**Comment by lucaslinha** [comment]
Duração da pra resolver facil aumentando numero de vte ou extends na votação e sobre esses mapas, eles exigem time, é obvio que não vão jogar um mapa desse com um time da tarde, porém muitas vezes em certos horários, o server tem uma quantidade de gente que tem noção do basico, ou seja um time no minimo bom para pelo menos tentar e mesmo assim acabam por desistir antes da hora. Em resumo fora de evento, o server não joga esses mapas nem quando não tem time e nem quando tem.

**Comment by lucaslinha** [comment]
Nessa semana mesmo caiu kitchen, ja começou com uma ruma de gente pedindo rtv dizendo que seria impossivel passar e mesmo com um time mediano, passou do level 2 calando a boca de muita gente na hora, muitos mapas tem condições de passar, mas essa falta de vontade atrasa isso.

**Comment by gabrielacms** [comment]
Eu sugeri de diminuir a quantidade de eventos por conta das recompensas relacionadas a VIP que o haru tinha citado no 1° post. Pq eu acho que vip por 1 semana para todos que ganharem o evento (e tendo evento durante 4 domingos) para mim não ia rolar. Agora se não for dar mais vip como recompensa principal que nem o haru citou depois, por mim pode deixar como está.

**Comment by hcjordao** [comment]
Deixa como está o evento e fazemos com a opção 3. Sobre o povo upar para shroom etc, temos que antes de lançar o plugin sentar e passar o pente fino nos mapas.

**Comment by lucaslinha** [comment]
Sobre esses shroom da vida, daria pra fazer uma config de overplayed como zm mais rapido, negev capada, no molotov e por ai vai, mas ai teria que fazer algo pra detectar o mapa sendo jogado X vezes dentro de um certo periodo para dar trigger ou algum cmd manual e deixar ativado la, se o cara venceu nessa config é pq ele mereceu mesmo.

**Comment by hcjordao** [comment]
Não precisa deixar mais hard os mapas. Só configurar o quanto é necessário para upar a tag simples.

Mapa | Elite | Veteran | Pro | Legend | God
--- | --- | --- | --- | --- | --- |
Fapescape | 5 | 15 | 30 | 45 | 60 |
Skyrim | 10 | 20 | 40 | 80 | 120 |
Shroom1 | 20 | 40 | 80 | 120 | 240 | 
Aesthetic | 1 | 2 | 3 | 4 | 5|

**Comment by alminha021** [comment]
e quem ja tem tag?
se o cara tem skyrim pro , na tabela vamos colocar 
fulano 40 vitorias , neh? ou ele começa do começo?

**Comment by hcjordao** [comment]
Sim, já colocariamos forçando as vitórias de cada um dos jogadores nos mapas. Se não vai deixar quem ja junta tag pelos 100 eventos muito putos.

**Comment by hcjordao** [comment]
Outra coisa isso de upar a tag pro próximo nível seria apenas em eventos de um mapa único. Mapas de combo eles atuariam como se fossem tryhard, ja que a tag seria a tag do combo. Temos que ver como seria inserida essas tags de combo.

**Comment by alminha021** [comment]
Nao vao tirar o settag? Deixa os combo com tags cosmeticas 
Combo eh a tag do combo somente, o cara coloca oque quiser , vitoia contaria apenas 1 por mapa

**Comment by hcjordao** [comment]
Sim essa é a ideia. Tags de combo serão inseriadas por fora (esse meu ver como fariamos é em questão de código e do banco de dados) já que vamos inserir de uma forma diferente.

**Comment by hcjordao** [comment]
Atualizada versão para 1.2 com as sugestões mencionadas.
```
-> Cvar para eventos criadas para fazer a gerencia automatica de up de tag sem perder o progresso atual do jogador
-> Modificado

**Comment by hcjordao** [comment]
Atualizada versão para 1.2 com as sugestões mencionadas.
```
- Cvar para eventos criadas para fazer a gerencia automatica de up de tag sem perder o progresso atual do jogador
- Modificado a secção Mudanças necessárias já que não haverá mudanças em como os eventos são feitos

**Comment by hcjordao** [comment]
Vamos fazer isso when?

**Comment by hcjordao** [comment]
Isso foi despriorizado. Talvez revisitemos com a chegada do source2 🚀
