### ISSUE TITLE
[ZE] Thread de melhorias na store

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#139]
Discutam aqui melhorias na store relacionadas tbm ao issue #98

**Comment by alminha021** [comment]
_Colocar na loja_
**Emote e Spray ( personalisados se possivel)**

- Emote - digitar :spicy: por exemplo, e aparece o spicy na cabeça do jogador

- spray - creio que deva existir um plugin de sprays custom, so precisa pensar nos que colocariamos

* Alguns apenas para vips.

**PET na store**
Vejo poucos vips usando, os pets mais usados sao os corvos que acho que eh pra galera pleb
libera uns pet nessa store , pokemons quem sabe?

*Mantem alguns pets para vip eh claro.

**zknifes**
- ta liberado sem custo nenhum eu acho
- coloca as facas boladonas na store (desentupidor , cloudsword, as do sao , nao sei qual mais tem)

**auras**
- novas auras , as que tinha quase ninguem usava, so usava as de evento que eram mais elaboradas
- elaborar novas auras pra comprar

**tag's**
- pq nao? umas tag de "nivel" que o cara compra com dinheiro
- nessas tags teria os caracteres especiais que sera bloqueados do sm_settag ( coraçao, estrela, cavalo etc..)

**sounds**
- sons curtos de 1 ou 2 seg
- de preferencia que saia do jogador , como no emote , nesse caso so escuta que esta perto dele

** traver de granadas**
- Colocar alguns tracer basicos na store pra plev ( cor branca , red, green, blue )

- os outros trcer coloridos libera pra vip ( roxo, ciana, amarelo, laranja etc..)

* eh so uma ideia

**Comment by lpcorrea** [comment]
Concordo com tudo que o alma passou.

## Som de entrada
* Apesar de ser mt cancer é muito engraçado, poderia ser uma feature do deluxe.
* Pode ser configurado pra não tocar caso seja evento/tryhard ou tenha algum lider ativo no round.

## Skins de granada
* Adicionar mais skins no Store, eu usava a skin da bola de neve mas infelizmente removeram sadboys.

## Skins
* Adicionar algumas skins de zumbi e humanos para comprar temporariamente.
* Skins de zumbi são fixas, skins de humanos com um ciclo trimestral.

**Comment by alminha021** [comment]
Coloca uns preço salgado mesmo.

vi os boludo dando creditos em loja nos eventos deles, achei daorinha.
ideia:
Recompensa os vencedores com X creditos no evento, seria legal colocar ( Participar tbm poderia recompensar, um tempo minimo jogado durante o evento daria y) , dai nao seria apenas TAG as recompensas
