### ISSUE TITLE
Retirar EW do cyberderp

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#14]
materias totalmente bugadas.

**Comment by hcjordao** [comment]
Removido, esperando sincronização do repo com o server.

**Comment by quasemago** [comment]
EW Re-adicionado, problema estava nos filtername.

**Comment by hcjordao** [comment]
Vimos que o cyberderp está com problema de cache de partículas pelo que vimos ontem. Os itens aparentam estar funfando normal.

**Comment by lucaslinha** [comment]
vcs testaram com o stripper que eu fiz ? ou deixam desabilitado ? @hcjordao

**Comment by hcjordao** [comment]
Esta ativado o seu stripper. Quando testamos ontem não estava funfando as partículas.

**Comment by hcjordao** [comment]
@lucaslinha depois testa os paranaues e vê se tá funfando

**Comment by alminha021** [comment]
no server ainda ta td bugado
boss bugado , o cara q pega fica travado.
nenhuma materia  tem particula 
alguma materias funfam sem particulas, outras nem fazem nada
no tab tem algumas [Gelo] outras sem o [] , tipo Fogo
materia de zm nao funfa.

**Comment by hcjordao** [comment]
Devo remover esse mapa do nominate?

**Comment by lucaslinha** [comment]
sim. ate resolver essas particulas.

**Comment by hcjordao** [comment]
Mapa removido do nominate. Na hora de adicionar o mapa no nominate novamente abra um novo issue se necessário, não esquece de atualizar a lista no mapas-servidor. Issue fechado.
