### ISSUE TITLE
[ZE] Draw tracer para lider. 

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#140]
Adicionar um recurso ao lider para desenhar um tracer atraves da sua mira para demarcar o caminho que se deve percorrer pelo mapa, bastante util para jogadores jogando o mapa pela 1 vez. 

![giphy](https://user-images.githubusercontent.com/31349929/81482009-5add4400-920a-11ea-9b97-9dc414bd5684.gif)

**Comment by hcjordao** [comment]
Movido para #143
