### ISSUE TITLE
[ZE] Item duplicado buga na EW

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#141]
Não é de hoje que basicamente todo mapa que possui matéria duplicada tanto de CT quanto de ZM, o item buga se + de 1 pessoa estiver equipando o mesmo. 
Exemplos de mapas que ocorrem o bug: 
ze_slender_escape_rc2
ze_diddle_v3
ze_industrial_dejavu_v3_3_3_e2_d
ze_atos_v1_12
ze_ny_marathon_p2

Na cfg, possui o maxamount que em teoria era para definir a quantidade de itens do mesmo. Mas não importa se esse valor estiver em 1 ou + de 1, as matérias não funcionam corretamente se duas ou mais pessoas estiverem com o mesmo item equipado. 

Onde e o que pode ser o problema? é na cfg?é no plugin? 
Tem que tentar encontrar a solução para esses bugs pq é bem merda ter que ficar dropando a pistola cada vez que for usar, sem falar que zm não consegue dropar a faca. 

Obs: todos os mapas citados estavam com o maxamount em 1. Mesmo alterando a quantidade ou mantendo em 1, continuaram bugadas.

**Comment by quasemago** [comment]
@gabrielacms Isso se não me engano foi fixado, pode confirmar para mim? lembro de ter feito uma correção a respeito disso.

**Comment by quasemago** [comment]
Já foi corrigido faz algum tempo!
