### ISSUE TITLE
[ZE] Melhorias Lider

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#143]
Juntando os multiplos issues de lider criados para apenas um.

## Lider Mark: (Video de Referencia - https://youtu.be/eSKRo7vwhqw?t=450)
- [ ] Comando de criar marcação (Atualmente o usado para inserir o verde). Adiciona uma marcação com uma letra, e incrementar as marcações existentes. Primeira vez usando o comando aparecerá A. Segunda vez usando o comando B assim sucessivamente até um limite de 4-5, passando o limite reseta as marcações antigas e retorna para a primeira.

- [ ] Comando de clean + reset. Reseta todas as marcações existentes. Retorna para A e limpa os desenhos pelo mapa.

- [ ] 3 Comandos similares ao primeiro só que são fixos (Um ZM, outro Recuar, outro defender).

## Overlay:
- [ ] Remover overlays em inglês do servidor, devidor que são meio inúteis, adicionar um overlay constante em hint para os usuários em português de forma que não atrapalhe a visão. De preferência abaixo da mira do mesmo onde fica a hint box.

## Votação p/ lider:
- [ ] Reduzir número necessário para jogador se tornar líder. Seis é um valor muito alto, reduzir para 3 jogadores. Talvez abrir votação que nem é o VTE, mas a duração da votação é bem reduzida, tipo 8 segundos para não atrapalhar muito.

## Whitelist:
- [ ] Remover todos os jogadores da whitelist de lideres atualmente, adicionar um canal em nosso discord onde um jogador pode dar um +rep a um jogador e com um minímo a ser decidido liberamos essa feature. Similar ao report.

## Blacklist
- [ ] Adicionar o comando -rep, caso o jogador receba um número X de reps negativos, que seja adicionado a blacklist de lideres. Podemos observar pelos reports tbm.

## Rank:
- [ ] Adição de um item na pontuação de mapas (assim podemos controlar quais mapas isso é valido e não qualquer um) onde caso haja um lider (acho que o mesmo pode ser feito para mapas level 4* para cima, para top defenders, para top defenders apenas uma porcentagem especificada na .cfg) e o round for ganho o lider ganhará uma porcentagem extra de pontos do mapa. Incentivo aos jogadores a tentarem liderar e zerar outros mapas. Para isso é necessário que haja propaganda para o servidor para que os jogadores tomem conhecimento disso. Seria interessante agregar com a sugestão de whitelist para não ter ladrão de lider.

## Draw Tracer:
- [ ] Adicionar um recurso ao lider para desenhar um tracer atraves da sua mira para demarcar o caminho que se deve percorrer pelo mapa, bastante util para jogadores jogando o mapa pela 1 vez.

![a](https://user-images.githubusercontent.com/27697496/81823982-52875080-950b-11ea-90d1-fdffd7ef6302.gif)

**Comment by lucaslinha** [comment]
* Quem estiver na Whitelist poder acessar o menu apertando F duas vezes. 

* Dentro do menu ter a opção de escolher entre o Leader 1 e Leader 2(O l2 é mais um suporte, so precisa ter acesso a marcaçoes, não tem acesso a beacon ou tracer.

**Comment by gabrielacms** [comment]
> ## Votação p/ lider:
> * [ ]  Reduzir número necessário para jogador se tornar líder. Seis é um valor muito alto, reduzir para 3 jogadores. Talvez abrir votação que nem é o VTE, mas a duração da votação é bem reduzida, tipo 8 segundos para não atrapalhar muito.
> 
Para mim o líder tem que ser automático. Incluir mais uma votação no servidor é residentsleeper demais. Concordo completamente em reduzir o valor necessário mas acho completamente desnecessário uma votação para líder. Tem mapa que muita coisa pode acontecer em questão de segundos, imagina ter que esperar uma votação acabar para uma pessoa ter um beacon ou poder fazer uma marcação.
> ## Whitelist:
> * [ ]  Remover todos os jogadores da whitelist de lideres atualmente, adicionar um canal em nosso discord onde um jogador pode dar um +rep a um jogador e com um minímo a ser decidido liberamos essa feature. Similar ao report.
> ## Blacklist
> * [ ]  Adicionar o comando -rep, caso o jogador receba um número X de reps negativos, que seja adicionado a blacklist de lideres. Podemos observar pelos reports tbm.
> 
Interessante os 2 (+rep e -rep) mas prefiro esse tipo de decisão ser somente da administração sem nenhuma interferência dos jogadores. Imagina o mimimi que vai ter uma pessoa dando -rep em alguém. Só se isso acontecesse por meio de reação e o pessoal não tiver acesso a quem reagiu de tal forma. 
> ## Rank:
> * [ ]  Adição de um item na pontuação de mapas (assim podemos controlar quais mapas isso é valido e não qualquer um) onde caso haja um lider (acho que o mesmo pode ser feito para mapas level 4* para cima, para top defenders, para top defenders apenas uma porcentagem especificada na .cfg) e o round for ganho o lider ganhará uma porcentagem extra de pontos do mapa. Incentivo aos jogadores a tentarem liderar e zerar outros mapas. Para isso é necessário que haja propaganda para o servidor para que os jogadores tomem conhecimento disso. Seria interessante agregar com a sugestão de whitelist para não ter ladrão de lider.
> 
[...] e o round ganho o lider ganhará uma porcentagem extra de pontos [...] tá mas nesse caso o líder teria que zerar o round também né?

**Comment by alminha021** [comment]
Marcaçao incremental, aprovado.
Marcaçao draw, aprovado.

Overlay poderia combar com comando de radio ja que foram bloqueados.
-> Dedenda aqui:
                  - overlay pt/br ou no hint
                  - No chat: "(LIDER): Defenda aqui!!"
                  -Radio. Audio: "defenda"


Sem burocracia, recebeu vl = vira ldier jah.

+rep -rep ( poder maior para os admins)

Incluir nas regras o "roubo de lider eh proibido"
  O que eh roubar lider? Eh vc ver alguem dando call certa, mas o time morre por besteira e alguem da whitelist der !lider para liderar e ganahr ponto. Ja avisa que isso eh caso de -REP.

Canal do Discord para isso
Anunciar sempre que alguem entrar na whitelist e sair dela.
Plebs nao comentam, canal so para anunciar.
Nesse canal coloca umas regras gerais de como funcionara , que da pontos liderar, admin pode dar -rep, Que existe blacklist etc...

**Comment by lucaslinha** [comment]
Esqueci disso, mas o libera lider no spec tambem, podendo usar as marcaçoes e tal, porém ele vai precisar de imunidade de kick durante isso. "Ah mas ai vão abusar para não tomar kick." Da pra resolver isso adicionando uma tag de leader para o leader atual, viu que o cara ta com a tag e não ta fazendo nada ? So dar um -rep e reportar.

**Comment by hcjordao** [comment]
Decidido em pauta #147
