### ISSUE TITLE
[ZE] No Played Day 

### ISSUE THREAD

**Issue by InFuse5** [quasemago/zrageservers#144]
Basicamente é um determinado dia da semana onde o nominate so apresentará mapas pouco jogados ou praticamente nunca jogados, é um dia pra falar NÃO para os mapas que são spamados constantemente no server. É realmente um desperdicio o server ter 370 mapas e grande parte disso nunca ter nem sido jogado em meses, o objetivo desse projeto é fazer algum desses mapas rodarem e acabar no conhecimento dos jogadores de aquele mapa existe. 

Alguns demais pontos sobre:

- Você poderá nominar normalmente, so que o nominate so apresentará mapas poucos ou nunca jogados. 

- Terá tambem um bonus de pontuação para todos os mapas presentes neste nominate. 

Ps: Essa parte é mais uma sugestão de minha parte mas caso isso for para frente e de certo, eu posso fazer sorteio de vip a cada X quantidade de mapas zerados neste dia.

**Comment by gabrielacms** [comment]
Massa.
Acho que não há necessidade de sorteio de vip até porque ao meu ver pode gerar alguns problemas futuros. Não tem como certificar que todas as wins serão legits (se o zm deixou etc). Levando em consideração que começará a 00:00 e terminará 23:59. Como serão mapas desconhecidos, sabemos que sempre há aqueles que sempre falam "deixa conhecer o mapa, não mata não"
E também por conta de alguns reports recentes sobre a falha na entrega de pontos. Não sei se quando dá esse erro, se gera o log de vitórias do mesmo jeito.

**Comment by lucaslinha** [comment]
> Massa.
> Acho que não há necessidade de sorteio de vip até porque ao meu ver pode gerar alguns problemas futuros. Não tem como certificar que todas as wins serão legits (se o zm deixou etc). Levando em consideração que começará a 00:00 e terminará 23:59. Como serão mapas desconhecidos, sabemos que sempre há aqueles que sempre falam "deixa conhecer o mapa, não mata não"
> E também por conta de alguns reports recentes sobre a falha na entrega de pontos. Não sei se quando dá esse erro, se gera o log de vitórias do mesmo jeito.

Da pra fazer com uma quantidade minima de jogadores e para o caso de erro, da para aconselhar aos jogadores a sempre tirar print do final.

**Comment by gabrielacms** [comment]
Depois da criação da tag Tryhard no discord ainda há a necessidade da implantação desse issue? Eu fiquei fora algumas semanas mas até então o pessoal costumava a marcar a tag sempre que queriam conhecer algum mapa que mal é jogado no servidor. Creio que se continuar incentivando isso ai vão voltar a fazer diariamente.
