### ISSUE TITLE
[ZE] Mapa ze_infected_tramway bugado

### ISSUE THREAD

**Issue by Xeloximiro** [quasemago/zrageservers#148]
Ao final do level, zm não toma slay, sem finalizar o round.

**Comment by gabrielacms** [comment]
Vai ser enviado para o servidor um stripper para tentar corrigir esse bug. Precisará de testes.

**Comment by quasemago** [comment]
@InFuse5 @gabrielacms Possuem alguma atualização sobre isso?

**Comment by InFuse5** [comment]
lancei um stripper a um tempo atras mas não tive feedback de ngm ate agora.
