### ISSUE TITLE
[ZE] Alteração da penetração de bala das armas

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#152]
**Qual o motivo para alterar isso?**
Atualmente usamos o método antigo de penetração (pré-2015) que faz com que praticamente todas armas tenham alta penetração assim deixando o jogo mais fácil, porém, esse método tem um ponto negativo que é o aumento considerável de var nos tiroteio. (GFL e PSE usam o método novo que irei explicar logo em seguida).

O novo método (usado no jogo padrão) possui penetração individual das armas e portanto isso iria dificultar bastante em alguns mapas, podemos pegar como exemplo o Bahamut do Mako, uma P90 no novo método iria dar 2x menos dano que atualmente fazendo que fique bem mais hard e parecido com o que é no CS:S.

Resumindo, o novo método da consideravelmente menos lag mas seria necessário reajustar os knockback das armas visto que irá causar menos danos aos zumbis e consequentemente empurrar menos.

Extra: Retirar o hitbox das skins para mais otimização.
- [ ] Master Chief
- [ ] Leon
- [ ] Coconuts
- [ ] Megumin
- [ ] Batman
- [ ] Ghost Face
- [ ] Krul Tepes
- [ ] Sasuke
- [ ] Goblin Slayer
- [ ] Enterprise (Azur Lane)

**Comment by lpcorrea** [comment]
Acho uma alteração válida, visando aumentar os slots futuramente e é uma ótima opção pois é o que os gringos usam.

**Comment by alminha021** [comment]
Sendo zm to me sentindo sendo mais empurrado do jeito que esta, na pratica ficou mais facil, principalmente pra jogador de rifle , com a demora pra zm ganahr speed um cara de rifle te atirando te joga muito longe.
Resumindo: ficou mais facil pra ct, nao gostei.

**Comment by quasemago** [comment]
O novo tipo de penetração utiliza os valores atuais da valve, portanto algumas armas ficaram até mais forte como é o caso da AK47, enquanto outras ficaram pior (MAC10 e BIZON).

Outra alteração que possivelmente tenha responsabilidade pela essa facilitação é o novo plugin "Anti Bullet Collision" que remove completamente a colisão das balas entre aliados, portanto você não perde mais uma porcentagem do dano ao varar 2 ou vários CTs.

Uma possível solução seria nerfar o Knockback das armas que estejam muito fortes como é o caso da AK47 já citada anteriormente, não recomendo mexer no KB geral pois vai nerfar ainda mais as SMGs.

**Comment by hcjordao** [comment]
Houve algum progresso na remoção das hitboxes dos bonecos?

**Comment by quasemago** [comment]
Não, o @lucaslinha iria trabalhar nisso.

Quanto a minha resposta anterior para o alma, devemos discutir sobre nerfar levemente o KB dos Rifles, visto que no novo método de penetração de bala elas ficaram mais fortes.

**Comment by lucaslinha** [comment]
Retirei as hitbox de todas, menos a do masterchief que ja ta sem, so falta enviar por server agora.

**Comment by quasemago** [comment]
Está em vigor no servidor!
