### ISSUE TITLE
[ZE] Aplicação das mudanças propostas pela staff. 

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#158]
- Molotov:
  -> Redução slow e aumento do preço.

- Shotguns/Revolver/Desert:
  -> Restrição. 

- SCAR-20/G3SG1:
  -> Restrição.

- Kevlar(COLETE):
  -> Remoção do custo com redução do limite de compra. 

Ps: Lembrete de postar o changelog sobre qualquer mudança feita.

**Comment by hcjordao** [comment]
- [ ] Molotov
- [ ] Shotguns/Revolver/Desert/Scar/G3SG1
- [x] Kevlar

**Comment by hcjordao** [comment]
Mudanças aplicadas nos pedidos, qualquer bug abrir o issue novamente.
