### ISSUE TITLE
[ZE] Adição do Eban blocker no EntWatch.

### ISSUE THREAD

**Issue by InFuse5** [quasemago/zrageservers#159]
Como ja diz o nome, ele bloqueia usuarios que estão banidos de ativarem itens que possuem teleporte com filtro para adquirir o item como exemplo: Skyrim, Diddle, Minas, Harry Potter. 

Isso seria de grande importancia para a gameplay desses mapas ja que usuarios banidos acabam ativando o teleporte, não pegando o item e consequentemente desativando ele pelo resto do round, assim arruinando o round. 

Não tenho muito conhecimento sobre a função do parametro pois não tenho acesso ao plugin, mas pelo que entendi, o parametro hooka a entidade que possui filtro e invalida o bypass do jogador banido que tentar ativa - lo., assim não podendo ativar a entidade. 
```
"16"
	{
		"name"              "EBAN BLOCKER"
		"hammerid"          "-1"
		"maxamount"         "1"
		"trigger"			"1151262"
	}
}
```

**Comment by hcjordao** [comment]
Isso funciona comprovado? Se sim posso incluir no ew, se tu quiser @lucaslinha ja pode fazer a branch no repositorio principal com essas mudanças

**Comment by lucaslinha** [comment]
Considerando que a ew do server foi refeita recentemente, quase ctz que não tem, esse exemplo é da ew da gfl que blocka quem esta banido de entrar no shop do diddle.
