### ISSUE TITLE
[ZE] Rebalanceamento Knockback.

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#162]
Proponho um rebalanceamento do knockback do servidor, incluindo classes zumbis e armas. Segue abaixo os valores atuais do servidor.

Knockback dos zumbis:
-
- Normal: 5.7
- Mother:  5.0

Knockback das armas:
-
Pistolas:
- Todas em 1.0.

SMG's:
- Mac10, MP9, UMP: 1.0
- Bizon, MP7, MP5sd, P90: 0.9

Rifles:
- Todos em 1.0.

LMG's:
- M249: 0.8
- Negev: 0.7

**Comment by alminha021** [comment]
_Concordo em ajustar, o novo sistema para penetração que foi implementado deixou muito mais facil para os CT._

### **Zombies:**
**_Mother_** = Voltar ao valor original antes da alteração ( reduzir 0.5, deixa em 4.5)

**_Son_** = Voltar ou manter o kb, zombie son tem q sofrer mesmo (exceto em caso de mothers q morrem e voltam de son)
voltar para 5.2 ou deixar 5.7 mesmo, whatever


_Obs:_ proponho q as mother voltem como mother mesmo morrendo, =D.
_Obs2:_ Porque mudar o kb dos zm? Pq mesmo com a penetração alterando e teoricamente ficando melhor para oz zombies, isso nao aconteceu, ficou pior na real.
primeiro pq as balas dos ct nao sofrem reduçao quando atravessa o amiguinho, deixando mais roubado , proponho q volte a sofrer reduçao novamente.
segundo pq algumas armas ficaram broken.


### **armas**

**pistols**
- ajustar deagle (se realmente for voltar, 0.2 ta otimo, useless weapon , eh so pra fazer graça) 
- manter em 1 mesmo, nao vejo problema

**SMG**
wtf bizon eh nerfada? mp9 pelo firerate q deveria ser nerfada , 4 hs seguidos = flying zombie

- smg em geral = kb em 1


**Rifles**
- arma pra fazer graça ou farmar dinheiro e top defender
 - ficaram roubadas demais 
primeiro pq o pente eh alterado delas, nunca entendi o pq e pra que( pra fazer dano bla bla bla, pega p90 q vc faz)
segundo pq a alteraçao na penetraçao deu um boost legal nelas , principalmetge agora q vc pode atirar pelo seus amiguinhos.

- reduzir para 0.7 ( a ta pequeno , meu, eu nao sei como ficaria, proponho deixar assim para ver , mas aposto q eh um otimo valor)

**LMG**
Arma roubada, fim.
- 0.6 as duas

**Comment by quasemago** [comment]
Retirei a colisão de bullet com aliados via plugin, não tem nada haver com a mudança de penetração. Não rola deixar reduzindo a bala ao atravessar o aliado, no novo método de penetração ele perde 50% do dano ao atravessar **UM** jogador e não atravessa o segundo.

**Sobre os valores das SMG's:**
Acho que é melhor apenas subir o kb da bizon para 1.0 e reduzir a P90 para 0.8 (atualmente em 0.9).
Reduzir o kb da da MP9 para 0.9 pelo mesmo motivo da P90 (fire-rate alto).

**LMG's:**
Concordo.

**Rifles:**
Concordo, não faz sentido ter KB alto nos rifles visto que o motivo deles terem munição aumentada é para ser utilizados em bosses baseados em HP (OnBreakable) e não hit (math_counter).

_
Enfim, esperemos mais feedback do pessoal.

**Comment by lucaslinha** [comment]
Zumbis: 
- Mother:
Por mim da um buffão na mother tipo 4.5 
- Son:
Leve nerf no son tipo uns 5.9 

Armas: 
- Pistola:
So nerfar a deagle e deixar ela atirando ervilha, o resto ta safe 

- SMG: 
Bizon sobe 10% e P90 desce 10%;  O resto ta safe

- Rifle: 
desce tudo em 40%

- LMG: 
Negev desce uns 10/20% e m249 continua como está(poquissimos conseguem fazer um spray decente com ela e a mesma em baixa quantidade não faz verão em hold)

**Comment by jericosa** [comment]
Acredito q os valores q vcs estao botando irao deixar o gamer muito dificil para o lado ct

Zumbis:

Mother:
Coloca  4.5
Son: Bota 5.8
Deixa como ta
Armas:

Pistola:
Deixa como esta

SMG:
Bizon sobe 10% e P90 desce 15%; O resto ta safe

Rifle:
desce tudo em 20%

LMG:
Negev desce uns 10% e m249 5%

**Comment by lhsatsuma** [comment]
(Leigo no assunto comentando)

KB ZM:
- Mother: deixar 4.8

Só mudar:
- Bizon: deixar 1.0
- Rifle: deixar 0.8 (Como o ronning apontou, n faz sentido rifle ter kb alto)


> Reduzir o kb da MP9 para 0.9 pelo mesmo motivo da P90 (fire-rate alto).

Apesar do fire rate ser alto, o recoil da MP9 é meio alto, eu deixaria como está.

> Obs: proponho q as mother voltem como mother mesmo morrendo, =D.

Concordo com esse Obs aqui...

O resto das armas eu nao uso, então n consigo opinar tbm.

**Comment by quasemago** [comment]
Knockback foi reajustado com base no feedback. Já enviei para o server e está em fase de testes!

**Comment by quasemago** [comment]
Issue fechado visto que ninguém mais deu feedback, caso seja necessário será reaberto.
