### ISSUE TITLE
[ZE] Alteração nas munições

### ISSUE THREAD

**Issue by lpcorrea** [quasemago/zrageservers#164]
Sugestão inicial feita pelo Alma. Transcrita para o GitHub para não ser peridida.

## SMG
* Ajustar munição para 64 balas.

## Rifles
* Munição padrão;
* Diminuir preço para compensar. (Valor a decidir)

## Pistolas
* Munição padrão

> Vou começar a transcrever as sugestões que eu ache relevante para que não sejam perdidas no Discord.

**Comment by gabrielacms** [comment]
Não deu para entender o motivo da sugestão. É para aumentar a dificuldade? No caso da diminuição das munições de rifle são para forçar o pessoal a parar de jogar com rifle e passar a jogar com smg? 

A quantidade de munição atual da SMG é 76. 12 a mais do que a proposta. Vai fazer mesmo diferença? 

Enfim, por mim pode dar uma testada para ver o feedback dos jogadores. Já possui uma sugestão de preços?  (no caso do rifle)

**Comment by quasemago** [comment]
Concordo com as sugestões, atualmente está muito nutela com os rifles possuindo 64 de munição.

**Comment by gabrielacms** [comment]
SMG: 64 ammo 
Rifle: 30 ammo 
Pistol: 12 ammo 

A quantidade de munição padrão das pistolas no csgo é bem variada, creio que seja melhor deixar tudo com um mesmo padrão.

> Deagle -  7 ammo
P2000 - 13 ammo
cz75a - 12 ammo
p250 - 13 ammo
revolver - 8 ammo
usp_silencer - 12 ammo
elite - 30 ammo
> 
Valores: 
SMG - Mantem preço 
Rifle - Atualmente está $4200. Creio que pode deixar em $3700 
Pistola - Mantem preço

**Comment by kobe-hcjordao** [comment]
Minha sugestão:
- Ammo padrão em tudo como disseram.
- Aumentar o preço da HE para 7k 🤓

**Comment by quasemago** [comment]
Gostei da sugestão @gabrielacms, mas a pistola elite irá ser exceção na padronização das munições visto que 12 balas nela seria ruim.

Caso todo mundo concorde, creio que já dê para adicionar isso ao servidor essa semana.

**Comment by quasemago** [comment]
Já está em vigor!
