### ISSUE TITLE
[ZE] Bug ze_assassins_creed_csgo

### ISSUE THREAD

**Issue by lpcorrea** [quasemago/zrageservers#165]
https://youtu.be/QztByNUMcns

Ta meio ruim o vídeo mas basicamente tem um local onde o chão não tem física.

Ali não é o caminho que os CTs tem que fazer para prosseguir o mapa.

**Comment by quasemago** [comment]
@InFuse5

**Comment by alminha021** [comment]
Ja foi fixado, nao?
pedi a uns dias para me mostrarem onde eles bugavam, e ja nao conseguiam

**Comment by InFuse5** [comment]
ja foi fixado, pode fechar se quiser.
