### ISSUE TITLE
[TTT] Reformulação Loja

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#166]
Já faz um tempo que a loja do TTT não é alterada e venho trazer essa sugestão.

**Loja todos:**
- Sem dano de queda ($6000): Alterar o preço para $10000 ou remover o item.
- Knockout Bullet: continua como está custando $7000 mas deve ser bufado a porcentagem do drop (atualmente em 20%).

**Loja Inocente:**
- Comprar T próximo round ($24000): Alterar o preço para ~$30000 ou remover o item.
- ID: recomendo remover o item visto que ninguém utiliza e não serve para nada.

**Loja Detetive:**
- Heavy ($10000): Aumentar o preço para $12000~$14000.
- Anti 1-Hit Knife ($2100): Aumentar o preço para ~$6500 visto que ela dura o round todo.
- Dnascanner ($9000): Aumentar o preço ou retirar a informação do role do assassino do corpo checado, assim o jogador ficaria apenas como suspeito e não receberia KOS.
- Health Station ($5600): Remover o item pois ninguém utiliza.
- Safezone ($9000): Aumentar o preço para ~$11000 visto que ela é bem OP podendo colocar em lugares estratégicos.
- 1-Hit AWP ($4600): Aumentar o preço consideravelmente ou remover o item, visto que ela anula totalmente o Heavy do Traidor que custa $10000.
- Detective Revolver ($6000): Remover o item, pois acho injusto você de T fazendo roleplay e toma uma bala na testa de um DTT batata só de zoeira.

**Loja Traidor:**
- 1-Hit Knife ($4200): Aumentar o preço para $5000~$6500 ou remover o item.
- Decoy Body ($9000): Remover o item já que ninguém utiliza.
- Decoy Teleport ($1500): Remover o item já que ninguém utiliza e por que ele buga bastante.
- Jihad ($4500): Bufar o range da explosão ou remover o item.
- Invisibility Cloak ($16000): Aumentar o preço para $20000 pois é um item OP.
- Blackout ($9000): Remover o item já que ninguem utiliza.
- Míssil ($10000): Remover o item deixando apenas o míssil teleguiado.
- Míssil Teleguiado ($18000): Aumentar o preço do item para $20000.

**Comment by alminha021** [comment]
**Loja todos:**

Sem dano de queda ($6000): Alterar o preço para $10000.
Knockout Bullet:  $7000 porcetagem 40%).

**Loja Inocente:**

Comprar T próximo round ($24000): remover o item.
ID: remover o item

**Loja Detetive:**

Heavy ($10000): Aumentar o preço para $12000

Anti 1-Hit Knife ($2100): Aumentar o preço para ~$6500

Dnascanner ($9000): aumenta o preço para 12k, retirar a informação do role do assassino do corpo checado, assim o jogador  + aparacer no chat para todos. ( matou 2 ino e continua vivo = pode dar kos)

Health Station ($5600): Remover

Safezone ($9000): Aumentar o preço para ~$12000 
1-Hit AWP ($4600):  remover o item,
Detective Revolver ($6000):aumentar pra 30k

**Loja Traidor:**

1-Hit Knife ($4200): Aumentar o preço para $8000
Decoy Body ($9000): Remover 
Decoy Teleport ($1500): Remover 
Jihad ($4500): Bufar o range da explosão 
Invisibility Cloak ($16000): Aumentar o preço para $20000 + menor duraçao ( 5s)
Blackout ($9000): abaixar para 3k
Míssil ($10000): Remover 
Míssil Teleguiado ($18000): manter + duraçao de 10s ou o missil explode automaticamente

**Comment by alminha021** [comment]
**_### extras_**

**1** add block parcial de itens de traitor
todo round 20% de todos os itens estao bloqueados para a compra , podendo aumentar para 40% depois.

pq? fazer os caras se adaptarem. E deve ser legal escutar o choro do cara que virou traitor e a hit-knife foi bloqueada


**2** Colcoar limite de 2 compras por jogador no round (3 para o vip)

**Comment by lhsatsuma** [comment]
> Loja todos:
> 
> Sem dano de queda ($6000): Alterar o preço para $10000 ou remover o item.

Deixar como está, muito util.


> Knockout Bullet: continua como está custando $7000 mas deve ser bufado a porcentagem do drop (atualmente em 20%).

Aumentar para 60%


> Loja Inocente:
> 
> Comprar T próximo round ($24000): Alterar o preço para ~$30000 ou remover o item.

Diminuir preço para 19.000, ninguém gosta de jogar mapa sendo só inocente... Aumentar limite de 2 para 3.

> Loja Detetive:
> 
> Heavy ($10000): Aumentar o preço para $12000~$14000.

Se aumentar o HP blz, se não deixa como tá.


> Anti 1-Hit Knife ($2100): Aumentar o preço para ~$6500 visto que ela dura o round todo.

Aumentar para 5.000



> Dnascanner ($9000): Aumentar o preço ou retirar a informação do role do assassino do corpo checado, assim o jogador ficaria apenas como suspeito e não receberia KOS.

Retirar a informação se o assassino é traidor ou inocente, já foi discutido este ponto anteriormente no chat da staff.


> Safezone ($9000): Aumentar o preço para ~$11000 visto que ela é bem OP podendo colocar em lugares estratégicos.

Deixar como está, justamente pq o traidor pode comprar o fake ID.


> Detective Revolver ($6000): Remover o item, pois acho injusto você de T fazendo roleplay e toma uma bala na testa de um DTT batata só de zoeira.

Deixar como está.


> Loja Traidor:

> 1-Hit Knife ($4200): Aumentar o preço para $5000~$6500 ou remover o item.

Deixar como está. N tem necessidade de aumentar o preço.



> Decoy Teleport ($1500): Remover o item já que ninguém utiliza e por que ele buga bastante.

Concordo, ja vi nego usando pra bugar o cara fora do mapa


> Jihad ($4500): Bufar o range da explosão ou remover o item.

Deixar como está, o apito e talz já é suficiente assim.


> Invisibility Cloak ($16000): Aumentar o preço para $20000 pois é um item OP.

Deixar como ta, nem é tao OP por causa do IP.



> Blackout ($9000): Remover o item já que ninguem utiliza.

É pouco utilizado pq ele demora pra ser ativado, se ativar na hora q compra muita gente ia usar.

> Míssil Teleguiado ($18000): Aumentar o preço do item para $20000.

Deixar 18.000, nao vejo problema nisso.


Obs.: Não adianta aumentar o preço dos itens se o cara sem VIP não ganha tanto crédito assim.
Tipo, 30k no revolver? Pra q? N tem necessidade disso cara.

**Comment by Tardigrada-TTT** [comment]
Gostei das sugestões, não vou comentar com os que concordo:

**Loja todos:**

- Sem dano de queda ($6000): Alterar o preço para $10000 ou remover o item.
                 - Não acho que dever ser removido ou aumentado o seu valor, é um item que é usado em ocasiões de extrema rapidez na hora que você toma TP do traidor de um lugar alto.

**Loja Inocente:**

- Comprar T próximo round ($24000): Alterar o preço para ~$30000 ou remover o item.
       - Não concordo com aumento ou remoção! É um item caro e que muitas vezes é a única chance de virar traidor em um mapa. A escolha aleatória de traidor muitas vezes desfavorece algumas pessoas, já passei mapas inteiros sem ser traidor e outras pessoas sendo 5 vezes seguidas, esse é o único item bom para inocente. É melhor melhorar esse plugin do que remover esse item do shop.

**Loja Detetive:**

- Dnascanner ($9000): aumenta o preço para 12k, retirar a informação do role do assassino do corpo checado, assim o jogador + aparacer no chat para todos. ( matou 2 ino e continua vivo = pode dar kos)
      - Concordo em aumentar o preço, apenas!

- Health Station ($5600): Remover o item pois ninguém utiliza.
       - Não concordo, eu uso, só não usa quem não conhece.

**Loja Traidor:**

- 1-Hit Knife ($4200): Aumentar o preço para $5000~$6500 ou remover o item.
       - Deixar o preço em 5500.

- Decoy Body ($9000): Remover o item já que ninguém utiliza.
       - Não concordo! Esse item ele temq ue ser reformulado, ninguem utiliza porque ele é caro e tem apenas um uso. Recomendo permanecer o mesmo preço, porém ele tem que durar o round todo, para todos os corpos que você matar!! E também anular quando o traidor testa algum corpo e ativa o decoy body! É um excelente item só que não foi bem estruturado no server.

- Jihad ($4500): Bufar o range da explosão ou remover o item.
        - o range não é o problema, o problema é que do nada tem um som de alguem gritando e alguem correndo atras de você, ai você mata a pessoa e acaba, nada explode. Quem utiliza a jihad tem que ou ter invencilibilidade no momento do uso ou ficar invisivel.

- Invisibility Cloak ($16000): Aumentar o preço para $20000 pois é um item **OP.**
           - Ele é OP justamente porque ele tem fucking 3 usos. Recomendo deixar apenas para um uso.

- Blackout ($9000): Remover o item já que ninguem utiliza.
          - Não utilizam pq é um item que demora para ser ativado, eu nem sei qual o tempo. Você compra e tem que ficar parado por um minuto pro mapa ficar escuro. Deixa por $7000 e põe insta blackout.

- Míssil ($10000): Remover o item deixando apenas o míssil teleguiado.
        - Não concordo, ele é utilizado em outros momentos.

- Míssil Teleguiado ($18000): Aumentar o preço do item para $20000.
          - Não vejo motivos para o aumento de preço. Ta bom do jeito que está.



**Obs:**   Gostei demais da intuição em melhorar o shop para a gameplay no sevrer, mas ficaria um absurdo o aumento dos preços dos itens na loja.

**Recomendo:**  Para a loja de inocente, recomendo ainda adicionar um item que:
Ao ser usado, você fica imune de qualquer dano por 1 segundo. Com apenas um uso e um valor de $8000.

**Comment by mystery-luck** [comment]
- **Loja todos:**

Sem dano de queda ($6000): Alterar o preço para $10000 ou remover o item.
> Alterar o preço para $10000 visto que é um item que se usa em poucas situações.

Knockout Bullet: continua como está custando $7000 mas deve ser bufado a porcentagem do drop (atualmente em 20%).
> Ser bufado ao ponto de se tornar viável.

- **Loja Inocente:**

Comprar T próximo round ($24000): Alterar o preço para ~$30000 ou remover o item.
> Manter o preço pois o limite de compra já previne a compra várias vezes.

ID: recomendo remover o item visto que ninguém utiliza e não serve para nada.
> Remover.

- **Loja Detetive:**

Heavy ($10000): Aumentar o preço para $12000~$14000.
>Manter o preço, visto que, detetive ganha menos crédito matando traidor, além de ter que comprar outras coisas além.

Anti 1-Hit Knife ($2100): Aumentar o preço para ~$6500 visto que ela dura o round todo.
>Manter o preço pois ajuda a counterar vips que possuem a 1 hit knife de graça.

Dnascanner ($9000): Aumentar o preço ou retirar a informação do role do assassino do corpo checado, assim o jogador ficaria apenas como suspeito e não receberia KOS.
>Aumentar o preço.

Health Station ($5600): Remover o item pois ninguém utiliza.
>Remover.

Safezone ($9000): Aumentar o preço para ~$11000 visto que ela é bem OP podendo colocar em lugares estratégicos.
>Aumentar o preço.

1-Hit AWP ($4600): Aumentar o preço consideravelmente ou remover o item, visto que ela anula totalmente o Heavy do Traidor que custa $10000.
>Aumentar o preço.

Detective Revolver ($6000): Remover o item, pois acho injusto você de T fazendo roleplay e toma uma bala na testa de um DTT batata só de zoeira.
>Concordo 100% pode tirar.

- **Loja Traidor:**

1-Hit Knife ($4200): Aumentar o preço para $5000~$6500 ou remover o item.
>Manter o preço, o item não é tão OP e o preço está balanceado para quem não é vip.

Decoy Body ($9000): Remover o item já que ninguém utiliza.
>Remover.

Decoy Teleport ($1500): Remover o item já que ninguém utiliza e por que ele buga bastante.
>Remover, várias vezes vejo algum T novo no server parando fora do mapa com o item.

Jihad ($4500): Bufar o range da explosão ou remover o item.
>O range está bom o problema é que é fácil counterar o item visto que demora pra ativar e faz um barulho muito alto.

Invisibility Cloak ($16000): Aumentar o preço para $20000 pois é um item OP.
>Aumentar o preço e remover alguns usos (Por exemplo de 3 mudar para 2)

Blackout ($9000): Remover o item já que ninguem utiliza.
>Não remover, mas, reformular, como o Tardigrada disse, deixar instantâneo.

Míssil ($10000): Remover o item deixando apenas o míssil teleguiado.
>Não remover é útil em diversas situações e várias pessoas usam.

Míssil Teleguiado ($18000): Aumentar o preço do item para $20000.
>Aumentar o preço.

**Comment by alminha021** [comment]
divide os itens por layers de karma

itens op => Karma 150

itens bons => karma 120 ate 149

itens lixo => karma 100 ate 120

sem loja pra vc => karma < 100

**Comment by alminha021** [comment]
acaba com a cultura do rdm que o spawn comentou.

150 eh obrigação.

**Comment by Tardigrada-TTT** [comment]
Mais que concordo com isso, que o alma disse!! Já é um início das mudanças a serem feitas com relação ao karma (falo isso lembrando do karma influenciar no nemesis, tank e etc..)

> divide os itens por layers de karma
> 
> itens op => Karma 150
> 
> itens bons => karma 120 ate 149
> 
> itens lixo => karma 100 ate 120
> 
> sem loja pra vc => karma < 100

**Comment by danielhidalgojunior** [comment]
> Já faz um tempo que a loja do TTT não é alterada e venho trazer essa sugestão.
> 
> **Loja todos:**
> 
> * Sem dano de queda ($6000): Alterar o preço para $10000 ou remover o item.
Não é muito usado, embora como o tardi falou, nego binda isso pra não morrer no TP de queda. Prefiro que mantenha esse do jeito que está.

> * Knockout Bullet: continua como está custando $7000 mas deve ser bufado a porcentagem do drop (atualmente em 20%).
Eu gostaria que aumentasse para pelo menos 40% a chance de dropar, mas precisa ter cuidado com as brincadeirinhas de rdm entre inocentes que esse item vai incentivar (hihi vou dropar a arma do tardigrada com um tirinho de usp).

> 
> **Loja Inocente:**
> 
> * Comprar T próximo round ($24000): Alterar o preço para ~$30000 ou remover o item.
O preço tá ok, acho que deveria é aumentar o usos para 3 ou 4. Como o tardi disse, tem vezes que eu não viro T no mapa sem comprar o role.

> * ID: recomendo remover o item visto que ninguém utiliza e não serve para nada.
Também não vejo utilidade para o ID do inocente, porém seria bom remover o comando /id do traidor, caso ele tenha, nunca testei. O traidor continuaria usando normalmente...

> 
> **Loja Detetive:**
> 
> * Heavy ($10000): Aumentar o preço para $12000~$14000.
Aumenta o preço e coloca pra vir junto com escudo.

> * Anti 1-Hit Knife ($2100): Aumentar o preço para ~$6500 visto que ela dura o round todo.
Preço dele tá ok, nada mais junto pro detetive.

> * Dnascanner ($9000): Aumentar o preço ou retirar a informação do role do assassino do corpo checado, assim o jogador ficaria apenas como suspeito e não receberia KOS.
como o alma falou, retira as informações e depois ajustamos as regras para poder dar kos após encontrar 2 mortos pelo mesmo player, assim aumenta um pouco o roleplay.

> * Health Station ($5600): Remover o item pois ninguém utiliza.
seria bom se ele desse mais do que 100 de vida, ai o pessoal deve começar a implorar pro detetive comprar.

> * Safezone ($9000): Aumentar o preço para ~$11000 visto que ela é bem OP podendo colocar em lugares estratégicos.
preço da safe tá ok já, só serve pra pegar batata mesmo. Traitor esperto compra fake id e sai dançando no meio.

> * 1-Hit AWP ($4600): Aumentar o preço consideravelmente ou remover o item, visto que ela anula totalmente o Heavy do Traidor que custa $10000.
remove, ngm usa

> * Detective Revolver ($6000): Remover o item, pois acho injusto você de T fazendo roleplay e toma uma bala na testa de um DTT batata só de zoeira.
nunca gostei desse item

> 
> **Loja Traidor:**
> 
> * 1-Hit Knife ($4200): Aumentar o preço para $5000~$6500 ou remover o item.
Deixa como está, tem alguns caras que a unica chance deles de matar alguém é usando a hit

> * Decoy Body ($9000): Remover o item já que ninguém utiliza.
item bosta, remove

> * Decoy Teleport ($1500): Remover o item já que ninguém utiliza e por que ele buga bastante.
bugado, uma bosta, remove


> * Jihad ($4500): Bufar o range da explosão ou remover o item.
diminui o delay para 5 ou 10 segundos, aumenta em uns 50% o range e diminui o tempo para explodir pela metade.

> * Invisibility Cloak ($16000): Aumentar o preço para $20000 pois é um item OP.
nunca usei, mas gosto da ideia do alma

> * Blackout ($9000): Remover o item já que ninguem utiliza.
bosta, remove

> * Míssil ($10000): Remover o item deixando apenas o míssil teleguiado.
remove

> * Míssil Teleguiado ($18000): Aumentar o preço do item para $20000.
concordo com a ideia do alma nesse caso. E tira a piroca, coloca um projétil decente, tem muita criança jogando no sv e mostrar piroca na cara deles n é legal. Sem contar que o saco fica na frente e vc n consegue ver em quem vai acertar.

**Comment by danielhidalgojunior** [comment]
> divide os itens por layers de karma
> 
> itens op => Karma 150
> 
> itens bons => karma 120 ate 149
> 
> itens lixo => karma 100 ate 120
> 
> sem loja pra vc => karma < 100

Pra mim, nego com karma muito baixo deveria ter menos chances de virar T. O dano por karma deveria ser diminuído, principalmente por causa dos random que entram no sv, matam 2 e quitam. Pelo menos com dano bem reduzido, eles não iriam conseguir matar e quitar. Já perdi muito round de T pq o cara me olhou e deu bala no começo do round.

**Comment by danielhidalgojunior** [comment]
outra coisa, ser T não dá dinheiro nenhum, já fiz a limpa em em vários rounds e nunca ganhei mais do que 8k. Traidor poderia fazer um pouco mais de grana em, e diminuir a grana que inocente ganha por matar T, dar mais grana por testar corpo, dar grana por dar kos pelo radio (só no fim do round, e só se ele acertar quem é T)... Incentivar o povo a seguir objetivo

**Comment by quasemago** [comment]
Já foi mesclado com o servidor.
