### ISSUE TITLE
Remover extend do RTV

### ISSUE THREAD

**Issue by lpcorrea** [quasemago/zrageservers#167]
### Sugestões de alteração:
* Trocar o Extend por "Novos mapas / Nova votação" (realizar uma nova votação com mapas aleatórios).

**Comment by gabrielacms** [comment]
Eu não sei bem se é isso mas me recordo de comentarem no servidor que não faz muito sentido o pessoal dar rtv em um mapa e ter a opção de extender. Creio que seja isso. Levando em consideração os outros issues, não vejo tanta urgência nessa modificação, até porque teria a necessidade de modificação do plugin. 
Mas se no futuro for feito algo sobre, creio que uma opção de Random Map é mais viável do que a realização de uma nova votação.

**Comment by quasemago** [comment]
Farei isso outra hora.

**Comment by quasemago** [comment]
Feito, irei testar mais tarde!

**Comment by quasemago** [comment]
Testado e está funcionando perfeitamente.
