### ISSUE TITLE
ze_eden_a2 com o boss invisível

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#17]
Irei adicionar o **ze_eden_a3** que é versão nova para ver se tem o mesmo problema.

@hcjordao

**Comment by hcjordao** [comment]
Nao joguei esse mapa nem vi o boss como é ve oq da ai com a nova versão.

**Comment by quasemago** [comment]
Possível causa: Meu fix realiza o uncache das **stringtables** e **particlesystems** ao terminar o mapa, provavelmente deve estar faltando tais partículas no manifest do mapa, o que resulta nos bugs apresentados visto que elas não são incluídas no novo cache.

Possível fix: adicionar as partículas que estejam faltando ao manifest do mapa.

**Comment by alminha021** [comment]
Sei la, pelo que vi ele fez tudo certinho. tem o eden.pcf no bsp dele e no manifest ta correto tbm.

particles_manifest
{
	"file"	"particles\eden.pcf"
}

ele usou de material pra fazer o boss e os ataques:
particle\particle_glow_01.vmt            
particle\particle_smokegrenade1.vmt
particle\particle_ring_wave_2.vmt
particle\particle_ring_blur.vmt

**Comment by hcjordao** [comment]
Alguma novidade nesse issue?

**Comment by lucaslinha** [comment]
Sim testei a versão a3 e vi isto: 
https://prnt.sc/nyi7if  Nesta foto os sprites são mostrados corretamente ali, ja que sprite não tem problema de precache, mas as particulas ficam invisiveis e não são carregadas de jeito nenhum. 

https://prnt.sc/nyi7v6 (Unknown Particle)

**Comment by hcjordao** [comment]
Remove do mapcycle?

**Comment by quasemago** [comment]
@hcjordao versão nova já **a3** foi adicionada ao servidor, favor testar ela para ver se o problema também acontece!

**Comment by alminha021** [comment]
Na **a3** aparece as particulas normalmente. ja esta jogavel

unico erro eh :
C_OP_RenderSprites::RenderUnsorted: Attempting to use an unimplemented sprite renderer for system "custom_particle_011"!
nao identifiquei o que era.
