### ISSUE TITLE
[ZE] Hide forçado durante o inicio do round ? 

### ISSUE THREAD

**Issue by InFuse5** [quasemago/zrageservers#170]
Enfim acabei descobrindo isso essa semana, aquele famoso bug de fps em que muitos jogadores ficam com fps baixissimo chegando ate fodendos 9 fps mesmo tendo um pc high end é devido ao propio jogo e não aos mapas, muito provavelmente a maneira que o jogo renderiza multiplas models na tela, mais precisamente quando varias models estão stackadas ou agrupadas na sua tela quando você spawna no mapa dentro de varios outros cts ou ate mesmo quando todo mundo se junta em uma porta por exemplo, claro isso não acontece com 100% de precisão, eu notei que tem uma certa chance de acontecer. Eu lembro que essa palhaçada começou depois de um update, provavelmente um update que aconteceu antes de jogarem o stalker_ultimate  onde foi a primeira vez que relataram aquilo. 

Então eu dei uma olhada em alguns servers asiaticos e um deles força hide no inicio do round, o que faz sentido ja que o hide desabilita a renderização da model, a ideia é ativar em todos os cts durante alguns segundos no inicio do round e depois desativar novamente para pelo menos evitar que os jogadores caiam no conto do fps pelo menos nesse inicio de round.  

Agora pouco olhando o discord percebi que ainda acontece na zrage e muitos acabam culpando o mapa sem saber o real motivo, acho que implementar isso no server não seria mal. Então a ideia é essa, espero que seja pensado futuramente.  Abraço

**Comment by quasemago** [comment]
O Hide seria aplicado e depois de X segundos desativaria automaticamente (será checado se é o hide automático ou o jogador utilizou o !hide)?

Qual seria o range desse hide automatico?

**Comment by InFuse5** [comment]
> O Hide seria aplicado e depois de X segundos desativaria automaticamente (será checado se é o hide automático ou o jogador utilizou o !hide)?
> 
> Qual seria o range desse hide automatico?

Acho que precisaria checar ou então so aplicar o hide manual do jogador depois desse acabar, se possivel o maximo range possivel que der ja que alguns spawns são separados.

**Comment by quasemago** [comment]
Baixa prioridade, esperando mais feedback do pessoal.

**Comment by alminha021** [comment]
Se realmente resolver o problema de fps baixo, eu ja considero prioridade media pra alta.

Estava bem recorrente o problema, muita gente reclamava, inclusive tinha mapa que todos tinha q sair e voltar do server, ja era 1 round perdido, fora os q a galera jogava com fps baixo

**Comment by quasemago** [comment]
Adicionei por 5 segundos o hide forçado no início do round.

**Comment by quasemago** [comment]
Implementado.
