### ISSUE TITLE
[ZE] Aumentar o tempo de mapas longos

### ISSUE THREAD

**Issue by lpcorrea** [quasemago/zrageservers#175]
Sugerido por [Sanson](https://steamcommunity.com/profiles/76561198068622839/)

Aumentar o tempo de mapas longos ou dar mais extend. Ex mapas: aesthetic, m0w0m, avalanche, onahole.
Como esta agora fica muito dificil jogar estes mapas fora de evento porque sempre acaba o tempo.

**Comment by lpcorrea** [comment]
Aumentar a quantidade de VTEs possíveis, incrementando a porcentagem de votos necessários para extender.

1 VTE -> 60%
2 VTE -> 70%
3 VTE -> 80%
4 VTE -> 90%

**Comment by InFuse5** [comment]
A ideia de aumentar a porcentagem é boa e tal mas passou de 80% nenhuma votação vai ganhar, posso falar isso com convicção ja que sempre tem um batata que se morrer no spawn ja quer que o mapa mude.

**Comment by InFuse5** [comment]
Sem contar que eu acho que isso daria mais trabalho pro ronning quando poderia apenas aumentar o timelimit do mapa de maneira equivalente a duração.

**Comment by alminha021** [comment]
Olha, é tudo muito bonito mas eu nao vejo isso sendo usado nesses mapa kkkk

Prevejo ter esse trabalho todo pensando que os caras vão jogar esses mapas sempre que puderem, quando na verdade vai rolar 1x a cada 20 dias.
So vai aumentar o numero de rounds jogados em mapa de surf , superporcariashitshow ,pizzatime etc..

**Comment by alminha021** [comment]
Mas se quiserem , acho válido aumentar 1 ou 2 vte com um minimo necessario alto, tipo maior 85%.

Se isso for aplicado a evento , tem que rever se é necessario colocar um deadline em tempo de duraçãp, até pela saude do pessoal. Ja temos muito tempo de mapa rolando , aumentar o vte isso ocasionaria em 30min a mais. Chegaria proximo a 4 horas de evento

**Comment by lpcorrea** [comment]
A mudança seria para apenas mapas selecionados manualmente, e não para todos.

Vejo o pessoal se interessando mais pelos mapas longos, estão sempre chamando a tag tryhard, acho que seria interessante essa mudança, mesmo que não ocorra agora

**Comment by gabrielacms** [comment]
Creio que é muito mais fácil alterar o timelimit desses mapas em questão. 
Sobre o vte, foram pouquíssimas vezes que vi uma votação dar 80%. Por mim, poderia ser feita uma cvar que ao invés de liberar esse vte incremental, apenas libera deixe o pessoal abrir mais de 1 vte no mapa. Nós adms conseguimos forçar 3 vtes. Deixa o povo abrir 2.
Ex: nesses mapas mais dificeis, o pessoal iria poder dar vte 2x ao invés de 1. Mas isso seria especificado na cfg do mapa para não utilizarem isso em outros mapas.
E isso não afeta os eventos. Evento continuaria do mesmo jeito: 2 horas + 2 extends + 1 vte. Se quiserem usar outro vte,usem mas não valeria tag, como já ocorreu outras vezes.

**Comment by gabrielacms** [comment]
Aproveitando que o issue fala sobre o vte, o Pataum deu a sugestão de liberar mais de um vte somente em mapa não zerado. 
Ao invés de liberar +1 vte, poderia ser feita uma alteração no tempo do extend desses mapas não zerados. 
- Default: 15 minutos vte
- Mapas não zerados: 25 minutos vte

**Comment by quasemago** [comment]
Alguém tem algo a acrescentar?

**Comment by alminha021** [comment]
Acho mais valido eumentar o tempo do vte mesmo.
mapa curto -> 15 min
mapa longo -> 25 min

Poderia tambem começar com uns 10min a mais de mapa tambem.

Prefiro assim do que liberar mais vte pro pessoal.

**Comment by InFuse5** [comment]
Em breve vou aumentar o timelimit de alguns mapas, se tive sugestão de mapa deixa ae.

**Comment by danielhidalgojunior** [comment]
aumentar o tempo do vte parece ter ser o mais simples e efetivo

**Comment by kobe-hcjordao** [comment]
> Aumentar a quantidade de VTEs possíveis, incrementando a porcentagem de votos necessários para extender.
> 
> 1 VTE -> 60%
> 2 VTE -> 70%
> 3 VTE -> 80%
> 4 VTE -> 90%

Gosto dessa opção. É assim em outros servidores

**Comment by quasemago** [comment]
> Aumentar a quantidade de VTEs possíveis, incrementando a porcentagem de votos necessários para extender.
> 
> 1 VTE -> 60%
> 2 VTE -> 70%
> 3 VTE -> 80%
> 4 VTE -> 90%

Atualizei o plugin para ser nesse formato, ainda preciso testar antes de enviar para produção do server.

**Comment by quasemago** [comment]
Testado e funcionando!
