### ISSUE TITLE
Sugestão rank

### ISSUE THREAD

**Issue by kobe-hcjordao** [quasemago/zrageservers#178]
1. Aumento de cooldown de mapas para evitar um pouco mais farm em mapas faceis (mas vai acontecer todo server de ZE tem seus mapas overplayed, ñ tem oq fazer)

2. Retorno de buff de pontos em leveis mais difíceis
  - É um trabalho coletivo, vcs players precisam dar retorno caso haja mapas/leveis que estão dando muito ou pouco ponto. Caso contrário o farm continuará ocorrendo só que em outros mapas
  - Eventos e tryhards valeriam 0 de pontos para evitar farm apenas nesse momento

3. Pontuação depende do time
  - Atualmente a pontuação é estática, se ganha o level irá ganhar os pontos. Independente da sua contribuição no round. O que pode ser feito é uma pontuação baseado no time. Como funcionaria?
- X -> Média entre os 3 top defenders do mapa é calculada. (top 3 defenders)
- Y -> Média de todo o time é calculada (time = quem está vivo no momento da vitória)
- Z = Y/X -> Razão da contribuição do time com média dos top defenders.
- Pontos entregues para todos os vencedores seria baseado em Z. Ou seja, se Z for alto (geral contribuiu com a defesa) pode-se dar dobro de pontos no mapa, se Z for médio (pontuação normal), se Z for baixo (pontuação é dividida no meio)

  - Obviamente que isso só seria implementado em rounds onde a pontuação do level é maior que um certo valor.
  - Resumindo se todo o time que sobreviveu participou da defesa dobro de pontos, se for um time ruim que ngm defendeu todos ganham metade dos pontos (tirando os top defenders imagino eu, ainda não sei)

**Comment by gabrielacms** [comment]
O Infused já sugeriu essa qustão do cooldown algumas vezes. O cd dinâmico. E sim, todo servidor de Ze tem seus mapas preferidos. 

O que precisa tentar descobrir antes de fazer qualquer alteração no rank é tentar entender o real motivo de jogarem os mesmos mapas todos os dias. 
- Se jogam para farmar ponto pois sabem que são os mapas que eles conseguem zerar
- Ou se jogam pq é literalmente o mapa que conseguem jogar. 

Já ocorreu buff de ponto em mapa naquela vez que voce fez haru e sinceramente não vi as coisas mudando. O pessoal não jogava os mapas que você tinha dado buff. O que tem que ser feito é NERF. Nerfa totalmente os mapas overplayed. Coloca esses mapas dando 1-5 pontos deixa ai por 1 semana e vamos ver. Se pararem de jogar esses mapas depois do nerf, significa que de fato ligam para o rank e estavam jogando para farmar. 
Agora se continuarem jogando mesmo nerfando, significa que não vai adiantar mexer em rank. 

Por que eu prefiro nerfar do que buffar mapa? 
Ex: Portal story - 80 pontos 
Shroom 2 - 160 pontos 
Slender - 170 pontos
Isso ai é a quantidade total de pontos. Acha que o povo vai deixar de jogar isso para tentar sei lá, um dark souls valendo 200 - 300 pontos?

**Comment by kobe-hcjordao** [comment]
Pode ser tbm. Mas tipo para isso dar certo o rework de pontos nos mapas teria que ser algo semanal a cada 2 semanas para ajustar. Isso teria que ter algm dedicado somente nisso, otherwise devagarzinho vai voltar ao mesmo status.

Sobre CD dinamico totalmente sou a favor mas isso não depende de mim

**Comment by kobe-hcjordao** [comment]
Eu mudo de opnião constantemente sobre a balança de um server tryhard/casual.

**Comment by lpcorrea** [comment]
Pra facilitar não teria como colocar um log de quantidade de vezes que os mapas foram jogados na semana?

**Comment by kobe-hcjordao** [comment]
Eu já fiz uma sugestão de logs de mapa no servidor. Log gerado no fim de todo o mapa

**Shroom2**
Total Defendido: 500k
Média de defesa por jogador: 15k (Média de defesa total por jogador -> Ver quanto foi de peso morto no time)
Score final no mapa: 6-3
Foi zerado: Sim - Não
Erros no Rank: Sim/Não (se houve algum round onde pontos não foram entregues)
Total de pontos ganhos: +3000 pontos (soma de todos os pontos ganhos no mapa de todos os jogadores)

**Comment by quasemago** [comment]
O primeiro ponto já está em vigor no servidor, basta ser feito mais configurações individuais para os mapas overplayed.

**Comment by alminha021** [comment]
Tem a sugestão tambem de descontar pontos do ranking para nomear mapas overplayed.

Prefiro zerar os pontos do overplayed , como foi discutido, de tempos em tempos podemos olhar o server tracking e procurar aqueles que estão sendo jogados constantemente.

Ficar de ferias eu olho o server tracking direitinho, começar a pegar info de la tambem.

**Comment by danielhidalgojunior** [comment]
@kobe-hcjordao seria ótimo poder ter mais variáveis para poder calcular uma pontuação mais justa. Concordo plenamente nesse sentido. Porém acredito que seria interessante aplicar algumas variáveis que vão afetar sua pontuação individual ao zerar o mapa, afinal o time no geral pode estar ótimo, mas podem ter players que não estão contribuindo que vão acabar ganhando uma bolada nas costas de quem está.

O fator time seria um fator global de pontos que vai afetar todos igualmente, porém podemos ter fatores individuais positivos e negativos em conjunto.

exemplos positivos:

- Está usando matéria (pegou matéria, finalizou round com matéria, algo do tipo)
- Está fazendo trigger (não sei se é possível identificar)
- Pontuação acima da média do time no top defender
- Estar como lider

exemplos negativos:
- Pontuação abaixo da média do time no top defender
- Eban ativo ou recebido durante o mapa

E cada fator poderia contribuir na sua pontuação individual no final (seja por % ou valor fixo), então José pode ganhar 150 e Pedro pode sair com 175.

Talvez esses fatores específicos positivos devessem ficar até escondidos do público para evitar tentativas se de aproveitar.

**Comment by alminha021** [comment]
**Pra deixar guardado**
alma Ranking

Definição de Winning points(WP) e Death points(DP).



user points = U               	% Pontos do usuario                
team points = T               	% Media de Pontos do time de ct quando a infecçao acontecer 
users online = Uo             	% players online quando a infecçao acontecer
map points = Mp				  	% Pontos que o mapa entrega
map overall diff = Mo           % Dificuldade do mapa em geral
map lvl diff = Ml				% dificuldade do level
streak = S                      % Quantidade de rounds perdidos em sequencia
Zombie infection points = ZiP   % Quantidade de pontos ganhos pelo zm por infecçao 


% Coeficientes para ranking  

Coeficiente de Rating =  CoR = U/T 								% Pontos do user sobre pontos medio do time			
Coeficiente de lambança = CoL = 5+(0.25 x S )					% Coeficiente da Lambança influenciando as derrotas											
Coeficiente de players = CoP = (Uo/45)+0.1  	                % Coeficiente da quantidade de players online sobre os slots
Coeficiente de dificuldade Level sobre mapa  = CoD = Ml/Mo		% Coeficiente do nivel de dificuldade do level sobre o mapa  	  												


=============================Humans Points=============================

---------------  WINNING POINTS => WP  -----------------

SE CoR > 0.8 
	Uo < 25

			Wp = { Mp x CoD x [ CoP x ( 1/CoR + 0.1 ) ] } - ( CoL x 3 )
			

	Uo > 25

			Wp = { Mp x CoD x [ CoP x ( 1/CoR + 0.1 ) ] } -  CoL 
	

SENAO
	Uo < 25
		
		WP = Mp - (CoL x 2)  
	
	
	Uo > 25
		
		WP = Mp - CoL 
			

------------ DEATH POINTS => DP  ----------------

SE CoR > 1 

	Uo < 25
			
		DP =	[ $VALOR$ x (1/CoD) x CoR ] - CoL 



	Uo > 25
	
		 DP =	[ $VALOR$ x (1/CoD) x CoR ]  - ( CoL / 4 ) 
		 
	
=============================Zombie Points=============================
  
Zombie mother winning points => ZWP

ZWP = %VALOR2$ x (1 / CoD) 

ZiP =  %VALOR3%

**Comment by gabrielacms** [comment]
Bom, aquele dia nós conversamos e chegamos na decisão de que não era necessário fazer nenhuma alteração no rank atualmente. Seria melhor esperar ver se o cd dinâmico vai melhorar alguns pontos

**Comment by alminha021** [comment]
Pois é.
Tem que ver como vai ficar, e como falei, nao vi ninguem farmando nem nada, se o cara ta 24 horas no servido devido a covid nao tem muito o que fazer pra ajudar quem nao pode estar la presente.

Melhor esperar, como so querem fazer mais uma mudança no rank pra nunca mais mudar ele, melhor ir com calma , vamo guardar as informações pra quem sabe um dia precisar alterar o ranking, deixar competitivo etc..

**Comment by danielhidalgojunior** [comment]
bom, arquiva esse issue entao e quando surgir a necessidade de alterar algo a gente ressuscita ele
