### ISSUE TITLE
Revisão de regen e hp nos zms

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#18]
Health regen da mother é quase a mesma coisa do son zombie, a diferença é pouca, a logica seria a mother ter o dobro do son.  

Por mim a mother tem que ter tudo que o son tem em dobro, afinal uma mother vale por 2. Por exemplo se o son regenera 200, a mother tem que regenerar 400, se a mother se regenera em um intervalo de 2, o son tem que se regenerar em um intervalo de 4.

**Comment by alminha021** [comment]
Verdade. Maioria nao gosta de jogar de zm (eu gosto) , agora imagina um cara pega mother , eh triturado na parede , sai com 1000 de hp, e nao pode tentar mais nada  direito, pq 1000 acaba rapidinho tomando bala, e o tempo de regeneraçao eh lento demais, se tentar o cara morre e pega o son lixao la, meu deus.
por mim , se o cara morre de mother, era pra voltar de mother. Cara ja foi selecionado pra zm, ele tem q pelo menos poder jogar o round full sem medo. Matar mother com materia o cara ja perde materia, tenso perder o mother tbm.

- Regeneraçao tem q aumentar a quantidade e diminuir o cd.
- Mother morre e volta de mother.
 
Se acharem roubado , muda so um, ou aumenta o regen ou deixa o cara voltar de mother.
Por mim tinha que ser os dois, mas neh...

**Comment by hcjordao** [comment]
Concordo com a parte da regeneração de vida e quantidade de vida regenerada. 
Sobre voltar mother discordo.

**Comment by quasemago** [comment]
Da para revisar essa parte de regeneração e talvez aumentar um pouco também a HP para mapas que não da override nisso.

**Comment by lucaslinha** [comment]
Então todos concordam certo ? Quem fará a revisão ? Por mim mantem o son como ta e dobra tudo na mother.

**Comment by quasemago** [comment]
ué, da sugestão ai.

Valores atuais do mother:

> "health"                "11000"
"health_regen_interval" "2.0"
"health_regen_amount"   "200"

**Comment by lucaslinha** [comment]
Chegando em casa eu faço um commit com isso.

**Comment by quasemago** [comment]
Concordo com o que foi apresentado pelo @alminha021 sobre a questão da HP.

Portanto os atributos da HP do zm classic na minha opinião devem ser deixados como estava e dar uma leve bufada no mother (convenhamos que os coitados estão muito nerfados).

**Comment by hcjordao** [comment]
Os Valores foram atualizados vou fechar este issue. Caso necessidade de novo, abrir novamente ou novo issue.
