### ISSUE TITLE
[ZE] Liberar acesso dos recursos de lider ao spec.

### ISSUE THREAD

**Issue by InFuse5** [quasemago/zrageservers#180]
O spec não tem acesso a qualquer um dos recursos de lider e nunca entendi o pq, tudo funciona perfeitamente nele, ate o beacon segue certinho a sua camera.

**Comment by alminha021** [comment]
Jogo ja eh chato de zm, poucos jogam serio de zm.
Liberar o cara ir pra spec so pq virou zm eh meio meeeh.
Se isso for implementado, que ele de um override na fila e vire zm com 100% de certeza no proximo round.
Se continuar indo pra spec vai continuar virando mother round seguinte.

Se nao tiver essa balança, acho muito podre dar esse recurso pra vip , zm com config de casual por conta do server, nao vejo porque dar esse tipo de privilegio enssa config, matar de zm eh muito mais hard que jogar de ct, sorte que os cara morrem por mapa

**Comment by InFuse5** [comment]
Não não, esse issue não é pra liberar acesso ao spec, é para liberar o lider para o spec.

**Comment by kobe-hcjordao** [comment]
Discuerdo, joga de zm e da call

**Comment by lpcorrea** [comment]
Concordo com o haru, caiu de zm tem que ajudar o time

**Comment by InFuse5** [comment]
Novamente vocês se perderam no assunto do issue, isso não tem nada a ver com não querer jogar de zumbi ou ter opção de não ser zm, tem a ver com permissão de lider em spec, não confundam as coisas por favor. Um dos motivos para qual criei o issue é de que gosto de liderar de spec, ja falei isso algumas vezes antes, sem contar que quando eu liderava de spec eu sempre costumava ja ser spec desde o inicio do mapa e não esperando ser zm pra virar spec.

**Comment by lpcorrea** [comment]
Agora entendi, seria ao contrário. Você quer liderar e não quer jogar nem de CT nem de ZM, dai os comandos funcionam de spec. Não vejo o pessoal fazer muito isso, mas também não vejo problema em liberar.

**Comment by alminha021** [comment]
Mas quando que vão usar isso? obviamente quando virarem zm mother ou morrerem.
Não vejo problema desde que nao sobre para os zm.

Ainda acredito que se quer jogar de spec, quando voltar tem q dar overide na fila de infecçao e virar mother.
ou permitir a entrada de spec somente antes da seleção de time.

**Comment by InFuse5** [comment]
> Agora entendi, seria ao contrário. Você quer liderar e não quer jogar nem de CT nem de ZM, dai os comandos funcionam de spec. Não vejo o pessoal fazer muito isso, mas também não vejo problema em liberar.

Exatamente, spec tem um controle bem melhor sobre os jogadores do que quem está no jogo que so tem controle do lugar onde ele está, acho bem melhor.


> Mas quando que vão usar isso? obviamente quando virarem zm mother ou morrerem.
> Não vejo problema desde que nao sobre para os zm.
> Ainda acredito que se quer jogar de spec, quando voltar tem q dar overide na fila de infecçao e virar mother.
> ou permitir a entrada de spec somente antes da seleção de time.

Sim pode ser também a ideia do override, e bom ate hoje não vi alguem que também tenha feito isso além de mim, mas seria bom pra evitar futuramente.

**Comment by danielhidalgojunior** [comment]
pra mim é de boa (desde q n ganhe pontos) e concordo com o ponto do alma, só dando uma ideia alternativa, o cara só poderia ir pra spec se estiver de CT, se for zm (infectado ou mother), tem q jogar até o final pra n dar desvantagem pro lado dos zumbis.

**Comment by lpcorrea** [comment]
Acho que deveria ir pra spec apenas antes de ter a infecção, pq mesmo indo como CT atrapalha o time

**Comment by danielhidalgojunior** [comment]
> Acho que deveria ir pra spec apenas antes de ter a infecção, pq mesmo indo como CT atrapalha o time. Isso se o cara já foi lider no round passado

Atrapalha qual time? N entendi

No caso os cts não perdem tanto pois o cara continua liderando de spec

**Comment by lpcorrea** [comment]
Não perdem tanto, mas perdem 1 cara pra atirar nos ZM. 

De qualquer forma se o cara ta liderando o mapa de spec, pra mim ele deveria entrar de spec antes da primeira infecção ocorrer.

**Comment by danielhidalgojunior** [comment]
Mas só dá pra votar em líder dps da primeira infecção né.

Talvez não antes da infecção, mas nós próximos segundos ou minutos, pra evitar de o cara ir pra spec pra escapar de ser infectado ou algo do tipo

**Comment by lpcorrea** [comment]
Não vejo problema dele ir pra spec antes da infecção, ele vai ficar em primeiro na fila de qualquer forma, mas estou pensando em já implementar aquele esquema de dar 1 vl só, depois o cara fica como lider até o fim do mapa, ai se ele quiser ir pra spec direto ele vai.
