### ISSUE TITLE
[ZE] Aplicar efeito de teleporte no jogador com a ausencia de zumbis.

### ISSUE THREAD

**Issue by InFuse5** [quasemago/zrageservers#181]
Existe uma regra no server sobre ultimo zumbi em que o cara quita como ultimo zm e um ct aleatorio no meio do time vira zm e acaba matando todo mundo, gerando dor de cabeça, um fix bem simples seria esse ct quando transformado levar um ztele na hora para evitar esse tipo de problema.

**Comment by quasemago** [comment]
Isso é bem simples de fazer, irei esperar mais feedback antes de pensar em implementar.

**Comment by danielhidalgojunior** [comment]
Isso já devia ter sido corrigido faz anos kkkk.

Acho que nesses casos poderia ter uma mensagem na tela ou no chat pro cara q foi escolhido pra virar zm só pra n deixar ele confuso por ter virado ZM do nada.

**Comment by quasemago** [comment]
Feito
