### ISSUE TITLE
[ZE] Adicionar warmup ao server.

### ISSUE THREAD

**Issue by InFuse5** [quasemago/zrageservers#183]
Bom ja vem sendo dada essa ideia faz um bom tempo e ate agora não vi algo nela que prejudique o server, então vou deixar por aqui:

* Warmup de ate 30 - 35 segundos.

* Infecção desativada durante o warmup, apenas humanos que por sinal respawnam se morrerem igual no warmup do propio jogo.

* Ao final do warmup a ordem da lista de infecção é randomizada para não prejudicar ninguem. 

* Pontuação de rank e defender desativada.

* Numéro mínimo de jogadores presentes para inciar a contagem do warmup, creio que de 6 a 8 parece um bom numéro para mim.

INB4: "Ah mas o rank ja é ativado com numéro baixo para encher o servidor, isso não vai dar certo." Esse pensamento é falho pra mim, o que mais se ve nas madrugadas da vida ou pela parte da manha quando tem numéro baixo de jogadores, é ct pedindo pra zumbi não pegar ou não infectar, o tal do "vamo conhecer o mapa, pega não." So por isso ja percebe que na maioria dos casos com um numero baixo de jogadores, eles sabem que não vão fazer porra nenhuma no mapa, muito menos ganhar ponto, então porque não deixar eles free conhecendo o mapa ate o server pegar um numero maior de jogadores ? Esse sistema ja funciona em alguns servers asiaticos no csgo e na unloze no css, nunca vi jogadores reclamando ou problemas serios do mesmo.

**Comment by danielhidalgojunior** [comment]
gostei

**Comment by quasemago** [comment]
Proposta está sendo tratada no issue #185.
