### ISSUE TITLE
Rework no plugin de lider 

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#2]
- [x] Remover lider do hide assim como qualquer entidades/particulas vindas do lider.
- [x] Criar um whitelist para lideres que podem ser setados automaticamente caso queiram. Jogadores merecedores de utilizar não precisam de votações para se tornar lideres. Se trolarem, perdem esse whitelist.
- [x] Efeitos mais fortes com o beacon. Segue em baixo links de exemplos.
- [ ] Efeito de marcação de indicação melhor e mais visível comparada ao atual no servidor segue em vídeos.

Montar efeito de hold como em https://youtu.be/VwiF5XT4Egs?t=282.  
Cor de beacon -> https://prnt.sc/nw120v

**Comment by hcjordao** [comment]
Queira a opinião do infused e da gabi nesse ponto aqui. O lider está bem inutilizado, tem que dar mais destaque pra ele em questao de particulas (não somente esse beacon)  alem de fazer ele ser mais atrativo pros jogadores quererem virar um

**Comment by lucaslinha** [comment]
1. Esse beacon é bem merda, não tem pq manter ele so pq é visivel atraves das paredes, tem que ser um beacon bem mais impactante, imponente, foda se ver atraves de parede ngm liga pra isso. 

2. Não tem precisão de follow me, deixa so o defend here e que ele ja venha padrão, ou seja que não fique precisando usar comando pra ativar o sprite na cabeça. 

3. Outra coisa bem interessante é que o lider da gfl vem com um traço de bala rainbow piscante pra galera saber onde o cara ta atirando.

**Comment by hcjordao** [comment]
Olha o video que eu mandei no comentario. Ali tem um lider que eu curti. Por default ja vem esse rastro laranja bem forte no chao que fica por bastante tempo. O sprite em cima da cabeça permanente. E o comando ativavel é simples um beam verde bem chamativo que indica uma posiçao e tu pode usar tanto pra indicar ponto de defesa ou qlqr outra coisa que o cara que ta liderando ache importante.

**Comment by quasemago** [comment]
Preciso ver como fazer esse "here" de particulas, quanto ao beacon querem colocar uma aura no lugar?

Os objetivos "follow me" and "defend here" não precisam ser passivos, afinal é só apertar uma vez no inicio do round e boa fica até o cara morrer.

**Comment by gabrielacms** [comment]
Entre aura e beacon, eu prefiro beacon. Aura os vips tem, o pessoal do holiday tb. Líder tem que ter algo que os outros jogadores não tenham.
Beacon: 
- Tem que ser em uma cor mais forte
- O tempo para o beacon sumir tem que ser um pouquinho maior para criar um "rastro" nem que seja pequeno para mostrar por onde o líder passou
Eu testei algumas alterações aqui e ficaria assim +- do mesmo jeito do vídeo que o haru mandou, só que a cor não está esse laranja mt forte - https://prnt.sc/nvjt9p 
Testa esse código dps: TE_SetupBeamRingPoint(vec, 10.0, 80.0, g_BeamSprite, g_HaloSprite, 0, 20, 1.5, 5.0, 0.0, {255, 128, 0, 255}, 10, 0);

**Comment by hcjordao** [comment]
Além de destaque no chat e nas msgs de radio.

**Comment by quasemago** [comment]
msg de radio :residentsleeper:

@gabrielacms Qual o delay de refresh desse "beacon"? o atual do servidor é 1 seg.

**Comment by hcjordao** [comment]
kkkk ajuda tá corno, qualquer destaque pro lider é nice. O ideal é mudar pra cores bem chamativas no chat o lider.

{cor chamativa, vermelho}[LIDER] {outra cor chamativa, roxo}<Nome do jogador>: {cor boa de ler mas diferente de branco, laranja/amarelo}msg no chat.

Pras msgs de radio so por pra ser vermelho mesmo

**Comment by hcjordao** [comment]
@quasemago olha esse placeholder da PSE, muito topperson que o infused enviou, bem melhor do que a que eu tinha visto.

https://youtu.be/VwiF5XT4Egs?t=282

**Comment by gabrielacms** [comment]
Aqui está em 1seg também. Deixando 1 segundo nessa configuração ai, vai deixar um rastro de no máx 2 beacons. Se for colocar que nem aquele primeiro vídeo que o Haru mandou, eles usam em uns 0.5 seg. Que dai deixa um rastro maior. Tipo assim: https://prnt.sc/nw120v

Se for deixar em 0.5 tem que diminuir a espessura do beacon. Na cfg que eu mandei em cima, o beacon está bem grosso e com 0.5 fica meio escrotinho de ver. 
Se quiser eu testei um outro aqui -> TE_SetupBeamRingPoint(vec, 10.0, 80.0, g_BeamSprite, g_HaloSprite, 10, 8, 2.0, 3.0, 0.0, {255, 128, 0, 255}, 10, 0);

**Comment by gabrielacms** [comment]
Desculpa pelo double post ^^ 
Tem um plugin de JailBreak que tem umas marcações no estilo dessas que voces mandaram.
https://github.com/PremyslTalich/TeamGames
https://github.com/PremyslTalich/TeamGames/wiki/MoreMarks
https://github.com/PremyslTalich/TeamGames/wiki/Marks

Voce ativa a marcação atirando e apertando E (vermelho) ao mesmo tempo ou apertando SHIFT + E (azul)
http://prntscr.com/nw1hsa

Dai creio que só teria que aumentar o tamanho ou mudar o sprite.

**Comment by hcjordao** [comment]
Deixando aqui o link pro beacon mais chamativo: https://streamable.com/8nthw

**Comment by alminha021** [comment]
-- concordo com a ideia do rainbow tracer . na gfl tem um rainbow tracer , seria interessante tbm na zrage.
Podemos testar, ou pelo menos liberar para os lideres daquela whitelist, pra nao ocorrer o problema de :
"me seta lider ai pra eu jogar de tracer" e o cara nao lidera porra nenhuma, so pede lider pra fazer graça de tracer.

pelo menos eh assim que eu faria. 
-> lideres da whitelist q sabemos q lideram tem a opçao de usar o rainbow tracer
-> lideres fora da lista nao tem, se viram com a marcaçao verdinha la, ate entrar na whitelist se tiver fazendo um bom trabalho

 
-- Beacon pode mudar de cor tbm, exemplo: 
alternar entre a cor padrao (amarelo forte quem sabe) e um azul quando eh pra ser follow ,
e qnd for pra defender alternar entre o amarelo padrao e vermelho

**Comment by quasemago** [comment]
Rainbow tracer? poderia explicar melhor? mande um vídeo.

Berg relatou que a whitelist não está funcionando corretamente, fiz um update e testarei mais tarde.

**Comment by hcjordao** [comment]
Update na lista. Beacon mais forte já foi adicionado e está nice.

**Comment by hcjordao** [comment]
-> Rainbow Tracer: Basicamente cada tiro sai com uma cor de tracer. Na GFL nao tem tracer entao é chamativo de qualquer forma. Não é necessário. Ao inves de ser rainbow que é meio meh, da pra por outro tipo de tracer diferenciado. No mapeadores em 2015 tinha um monte de tipo de tracer so socar um pra ser o do lider.

Consegue alterar o sprite verde por aquele mais bonito la depois ronn?

**Comment by hcjordao** [comment]
Como há um post recente sobre rework no plugin de lider irei fechar e transferir para lá. 
#54
