### ISSUE TITLE
Mapa muito facil ze_RTCW_Ominous_Rumors_p4 devido remoção dos leveis hard e extreme

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#20]
Como o mapa tem 3 leveis mas tbm tem 3 dificuldades sobre cada level melhor deixar ou o modo HARD ou o modo EXTREME como padrão ao inves do modo EASY. Esse modo easy é ridiculo demais.

**Comment by lucaslinha** [comment]
vou ver se consigo deixar so os extreme, mas acho que vai dar um trabalhozinho, é basicamente tudo misturado pelo que me lembro.

**Comment by hcjordao** [comment]
Qnd eu baixar os trecos de novo posso ver como funfa esse stripper. Deixar em stand-by o issue até lá?

**Comment by hcjordao** [comment]
@lucaslinha algum progresso?

**Comment by lucaslinha** [comment]
Parei um tempo com o server pra trabalhar no meu mapa. :thanossmile: Vou so att vers e fixar major bugs/glitchs.

**Comment by lucaslinha** [comment]
Retirei o easy e coloquei o hard no lugar. Pode encerrar o issue se quiser.

**Comment by quasemago** [comment]
@lucaslinha já foi testado se está tudo correto?

**Comment by lucaslinha** [comment]
Foi testado no dedicado, então creio que deve funcionar.

**Comment by quasemago** [comment]
@lucaslinha Pode fechar esse issue?

**Comment by lucaslinha** [comment]
sim
