### ISSUE TITLE
Volta do Panorama fix do Shufen ?

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#21]
Esse plugin faz muita falta, tinha antes e retiraram não sei pq motivo. Galera não extende e a gente não tem noção de que não extendeu pq o timeleft não aparece mais.

**Comment by quasemago** [comment]
Irei adicionar isso por conta propria, aquele fix da uns bugs em relação a seleção de equipe.

**Comment by quasemago** [comment]
Foi adicionado o fix de seleção de time de forma individual visto que o PanoramaFix do Shufen apresentava alguns problemas.
