### ISSUE TITLE
Bug de download, baixando todo mapa arquivos repetidos

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#23]
Downloading http://fastdl.zrage.com.br/csgo//materials/models/player/CuddleTeamLeader/Body.vmt.bz2.
Error downloading http://fastdl.zrage.com.br/csgo//materials/models/player/CuddleTeamLeader/Body.vmt.bz2
Downloading http://fastdl.zrage.com.br/csgo//materials/models/player/CuddleTeamLeader/Body.vmt.
Error downloading http://fastdl.zrage.com.br/csgo//materials/models/player/CuddleTeamLeader/Body.vmt

**Comment by quasemago** [comment]
Não sei nem pra que serve esses materiais.

**Comment by quasemago** [comment]
É um lixo de uma skin que iria ser usada na pascoa, irei remover.
