### ISSUE TITLE
Bug texturas ze_biohazard3_nemesis_b4_1

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#24]
Report de jogador sobre bug de texturas no mapa.

**Comment by lucaslinha** [comment]
versão nova inc.

**Comment by hcjordao** [comment]
Remover esse mapa do nominate enquanto isso?

**Comment by hcjordao** [comment]
Ainda ta com esse bug de textura ou ja teve a att de versão?

**Comment by lucaslinha** [comment]
Ja tem versão nova, não posso dizer se fixou isso pois não sei onde fica.

**Comment by lucaslinha** [comment]
Mapa foi retirado do server, melhor fechar o issue.
