### ISSUE TITLE
Map Bonus Plugin

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#25]
Fiz a att da formula do mapbonus, mas tem algo bem estranho, os mapas todos ou estão com bônus normal de 1 ou com o bônus máximo possível de 15 dias.

**Comment by quasemago** [comment]
Plugin desativado temporariamente.

**Comment by quasemago** [comment]
Fiz um update no plugin, testarei mais tarde.

**Comment by quasemago** [comment]
Parece estar funcionando corretamente depois do update que fiz, irei testar mais um pouco antes de fechar esse issue.

**Comment by quasemago** [comment]
Fixado!
