### ISSUE TITLE
Troca de versão do mapa - ze_dark_souls

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#26]
http://fastdl.gflclan.com/csgo/maps/ze_dark_souls_ptd_v0_4_csgo7.bsp.bz2

Segue em anexo a ew, stripper e o vscript que é citado no stripper. 
O local desse vscript é - csgo/scripts/vscripts/dark/item_c_patched.nut
[dark_souls.zip](https://github.com/quasemago/zrageservers/files/3244148/dark_souls.zip)

**Comment by lucaslinha** [comment]
Não confio muito nessa versão, ja vi outros server crasharem nela e provavelmente vai ter csgo8.

**Comment by gabrielacms** [comment]
Entendi. Podia testar ou sei lá, até sair essa csgo8 alterar a EW da versão atual do sv. Todas as matérias do mapa tem limite de uso e a ew não mostra isso.

**Comment by lucaslinha** [comment]
hmm vou add stripper do csgo6 com esse EW ai.

**Comment by hcjordao** [comment]
Infused vai fazer update de stripper. Não vai haver atualização para essa nova versão devido possíveis indícios de crash. Issue Fechado.
