### ISSUE TITLE
Kick por spam de comando. (SMAC)

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#27]
Várias pessoas estão tomando kick por spam

Jabi, berg ontem tomaram kick por ligar a lanterna. Eles falaram que apareceu aviso de spam do comando. Haru acabou de tomar kick também. 
Eu consegui pegar o aviso do kick do pastor só. 

[SMAC] Merged Zamasu was kicked for spamming: snd_setsoundparam Music.StartRound_03.valve_csgo_02 volume 0

**Comment by quasemago** [comment]
Valve fazendo merda como sempre, removeu o comando mas deixou os input.

https://blog.counter-strike.net/index.php/2019/05/24458/

**Comment by lucaslinha** [comment]
Também ja tomei quando estava testando um mapa de madrugada.

**Comment by quasemago** [comment]
Update acima que eu citei.

> – Removed a development command for adjusting sound parameters.

**Comment by quasemago** [comment]
Desativei o kick por spam de cmd temporariamente até a valve cabeça de rola arrumar isso.

**Comment by quasemago** [comment]
Issue trancado pois não tem o que fazer, basta esperar um update da valve.

**Comment by quasemago** [comment]
Fixado!
