### ISSUE TITLE
Top Defender melhorias

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#28]
- [x] Aumentar a proteção de infecção ao inves de ser apenas o top1 incluir top 2 e top 3 (Quem defende tem que ser mantido no time a todos os custos).

- [x] Quando o humano for salvo por ter ficado em top defender incluir uma msg no HUD -> "Você foi salvo de infecção por ter ter ficado no top 3 de defensores do round".

Infused sugeriu umas ideias interessantes em sugestoes no discord, pra nao falar por ele vou esperar a opiniao dele aqui.

**Comment by alminha021** [comment]
::top 3 livre de infecção:: = ok, apoiadissimo (isso resolve ate a parada da infecçao viciada, pra nao virar zm mother com os mesmos companheiros "quase" sempre, pegar top defender em 1 round antes da sua vez de mother muda seu lugar na fila [atrasa], pelo emnos eh assim q eu acho q o plugin responeria) .

::"voce foi salvo" ::-> Questao de estetica, pra mim ok, novato que ver isso vai querer pegar top denovo , ja que ninguem gosta de zm T_T 
* minha duvida, ele vai pro fim da fila de infecção[pula a vez dele e joga no fim da fila]?
 ou so eh salvo naquele round e no proximo que ele nao pega top 3 ele ja ta no começo da fila pra infecçao [ignora a vez dele mas mantem ele no começo da fila, no caso vai virar no proximo]?

 :: chat cores chamativas :: -> por mim nao precisa, parada de vip isso ai, so uma tag no TAB ja ta bom.

:: objeto na cabeça :: -> gostei, coloca diversas coroas diferentes um cone ,  triangulo illuminatti no futuro, sei la, mas so a coroa por enqunto ta ok.

:: remover hide top defender:: -> nao gosto de vestido na minha cara , seria mais um pra eu ficar longe, mas pode remover ele do hide , por mim ta ok, eu me adapto.

**Comment by lucaslinha** [comment]
Concordo com os 3 primeiros, sobre o 4º eu acho que a coroa em cima da cabeça poderia ser usada com o plugin de hat pra colar na cabeça da model, pq em mapas que vc precisa olhar pra cima como mist e grau, a coroa fica tapando sua visão. Daria pra colocar outras coroas nos 2 e no 3 lugar do defender tmb. 

Agora as minhas ideias : 
1. Armazenamento de dano total durante todo o evento, iniciou o evento ativa a convar e ja começa a contar, baseado nesse dano acumulativo vc poderia usar como moeda de troca para uma skin limitada, limitada ? Sim ... por exemplo uma skin com estoque de 5, ou seja so 5 pessoas poderiam pegar ela por seila 3 milhões de dano, ta mas pq isso ? Simplesmente pelo fato de que quanto menos pessoas tem uma skin, mais ela se valoriza e faz as pessoas lutarem mais ainda para conseguir ela.

2. Fazer o score do tab como score do top defender, é basicamente o mesmo sistema da gfl do css, o numero mostrado nos seus assists equivalem a posição atual em que você está e obviamente quem estiver em 1° vai estar no topo do score.  

3. Mostrar os 5 primeiros top defenders no final de cada round, mas obviamente so os 3 primeiros ganham recompensa. Isso é mais para visualização de quem chegou perto de alcançar os 3 primeiros.

**Comment by gabrielacms** [comment]
Seria interessante implantar isso. Só deixo um comentário sobre 2 itens:
- Hide: sei que a proposta de remover o hide é por conta da coroa mas não sei..para mim a remoção do hide faz sentido só para líder. Mas vcs que sabem
- Coroa: eu gosto bastante disso. Só deixo um aviso que quando for implantado, testar o top defender em mapas que as matérias tem level. Assim que o top defender foi implantado na gfl, eles tiveram que desativar por um tempo o sistema nesses mapas. Porque o top mudava o targetname da pessoa para colocar a coroa. E isso fazia perder os leveis. 

Em relação às sugestões do Infused, estou de acordo com todas.

**Comment by quasemago** [comment]
> Aumentar a proteção de infecção ao inves de ser apenas o top1 incluir top 2 e top 3 (Quem defende tem que ser mantido no time a todos os custos).
Ok, nada contra.

>   Quando o humano for salvo por ter ficado em top defender incluir uma msg no HUD -> "Você foi salvo de infecção por ter ter ficado no top 3 de defensores do round".
Desnecessário, mas ok...

>   Incluir assim como na nova versão do lider mudança no chat com cores chamativas para o top 1 [Top Defensor] Nome do jogador: msg do jogador.
Mais firula pra conflitar com os 300 plugins de cores de chat/nome, desnecessário.

>   Incluir como padrão um objeto em cima da cabeça do top defender 1. Idealmente ele poderia escolher entre muitos objetos disponiveis, mas como versão inicial apenas colocar a coroa padrão em todos os servers de ZE. Na GFL todo round o jogador que ficou em top defender tem que usar um !topdefender pra ativar a coroa. Não é automatico
Desnecessário, só uma coisa pra conflitar com os sprite do leader caso o topdefender queira ser um.

>   Remover do hide o top defender 1. Para mostrar a coroa dele :spicy:
Prefiro deixar apenas quem possui materia e lider imune ao hide pois o topdefender muitas vezes tem batatas que ficam atirando em zumbis sem parar mesmo durante bossfight.

**Comment by quasemago** [comment]
> * Coroa: eu gosto bastante disso. Só deixo um aviso que quando for implantado, testar o top defender em mapas que as matérias tem level. Assim que o top defender foi implantado na gfl, eles tiveram que desativar por um tempo o sistema nesses mapas. Porque o top mudava o targetname da pessoa para colocar a coroa. E isso fazia perder os leveis.

@gabrielacms Então foi mal implementado, não é necessário atrelar nenhum targetname ao jogador, basta dar parent no sprite (vide sprites do leader).

**Comment by quasemago** [comment]
@lucaslinha 

> 1. Armazenamento de dano total durante todo o evento, iniciou o evento ativa a convar e ja começa a contar, baseado nesse dano acumulativo vc poderia usar como moeda de troca para uma skin limitada, limitada ? Sim ... por exemplo uma skin com estoque de 5, ou seja so 5 pessoas poderiam pegar ela por seila 3 milhões de dano, ta mas pq isso ? Simplesmente pelo fato de que quanto menos pessoas tem uma skin, mais ela se valoriza e faz as pessoas lutarem mais ainda para conseguir ela.

Hmmmmm.... não gostei, mas vejamos o que dizem.
> 2. Fazer o score do tab como score do top defender, é basicamente o mesmo sistema da gfl do css, o numero mostrado nos seus assists equivalem a posição atual em que você está e obviamente quem estiver nas primeiras posições vai estar no topo do score.

Conflita com o entwatch, além de eu achar meio inútil isso pois é anunciado os top defender tanto no chat quanto no hud durante o fim do round.
> 3. Mostrar os 5 primeiros top defenders no final de cada round, mas obviamente so os 3 primeiros ganham recompensa. Isso é mais para visualização de quem chegou perto de alcançar os 3 primeiros.

Só vai confundir a cabeça de batata pq não ganhou nada mesmo estando no anuncio.

**Comment by lucaslinha** [comment]
Não não vai confundir a cabeça de ninguem, ate pq ninguem sabe o que ganha desse top defender.

**Comment by alminha021** [comment]
ow , me colocapra aparece o dano de geral ai no console no final.
so pra ver qm ajuda mesmo. Começarem a expor isso ai os batata vao começar a defender pra nao apssar vergonha.

**Comment by hcjordao** [comment]
> Concordo com os 3 primeiros topicos, sobre o 4º eu acho que a coroa em cima da cabeça poderia ser usada com o plugin de hat pra colar na cabeça da model, pq em mapas que vc precisa olhar pra cima como mist e grau, a coroa fica tapando sua visão. Daria pra colocar outras coroas nos 2 e no 3 lugar do defender tmb.

Mas seria feito como na GFL tu só equipa através de um comando !topdefender ou algo do genero. Não precisa equipar se não quiser.

> Agora as minhas ideias :
> 
> 1. Armazenamento de dano total durante todo o evento, iniciou o evento ativa a convar e ja começa a contar, baseado nesse dano acumulativo vc poderia usar como moeda de troca para uma skin limitada, limitada ? Sim ... por exemplo uma skin com estoque de 5, ou seja so 5 pessoas poderiam pegar ela por seila 3 milhões de dano, ta mas pq isso ? Simplesmente pelo fato de que quanto menos pessoas tem uma skin, mais ela se valoriza e faz as pessoas lutarem mais ainda para conseguir ela.

O que poderia ser feito na real é no fim do mapa exibir um acumulativo de dano total no mapa ao inves de mostrar o top defender normal. Sei lá man eu ja sou meio brega com o sistema de store pq apesar de ser uma forma de organizar os itens tem muita coisa confusa ali no meio. Store pra comprar item mas nem tudo da pra comprar, tu ganha credito e mal usa eles pra nada. Tu acessa os perks do vip pelo store etc. Acho que botar mais coisa vai confundir o cara.

Se tivesse como voltar no tempo eu mantinha o !zclass pra escolher skin, com descrição da mesma ali se é de vip, vip deluxe, vip do rank mensal. 

Teria um !vip pra caso o cara nao fosse vip aparecer como compra e se for aparece o menu de perks de vip com tudo que ele tem acesso, passava oq tava na store tudo pra isso sem esse esquema de credits.

Teria um !tag que abre um menu pra mudar tudo da cor e etc da sua tag. Ali embaixo estaria um event tags e special tags. Tu pode clicar em todas as tags especiais mas caso vc nao tenha ganho aparece uma msg de tag de qual evento foi e quando. As que vc tem acesso apareceria com uma estrelinha na frente.

E ficaria por essas mesmo. Em caso de eventos temporários onde se comprava coisa por esses credits do store simplesmente muda pra time online no servidor e permite o acesso deles por um comando !especial/!tempolimitado sei la.

> 2. Fazer o score do tab como score do top defender, é basicamente o mesmo sistema da gfl do css, o numero mostrado nos seus assists equivalem a posição atual em que você está e obviamente quem estiver nas primeiras posições vai estar no topo do score.
> 3. Mostrar os 5 primeiros top defenders no final de cada round, mas obviamente so os 3 primeiros ganham recompensa. Isso é mais para visualização de quem chegou perto de alcançar os 3 primeiros.

**Comment by hcjordao** [comment]
> Concordo com os 3 primeiros topicos, sobre o 4º eu acho que a coroa em cima da cabeça poderia ser usada com o plugin de hat pra colar na cabeça da model, pq em mapas que vc precisa olhar pra cima como mist e grau, a coroa fica tapando sua visão. Daria pra colocar outras coroas nos 2 e no 3 lugar do defender tmb.

Mas seria feito como na GFL tu só equipa através de um comando !topdefender ou algo do genero. Não precisa equipar se não quiser.

> Agora as minhas ideias :
> 
> 1. Armazenamento de dano total durante todo o evento, iniciou o evento ativa a convar e ja começa a contar, baseado nesse dano acumulativo vc poderia usar como moeda de troca para uma skin limitada, limitada ? Sim ... por exemplo uma skin com estoque de 5, ou seja so 5 pessoas poderiam pegar ela por seila 3 milhões de dano, ta mas pq isso ? Simplesmente pelo fato de que quanto menos pessoas tem uma skin, mais ela se valoriza e faz as pessoas lutarem mais ainda para conseguir ela.

O que poderia ser feito na real é no fim do mapa exibir um acumulativo de dano total no mapa ao inves de mostrar o top defender normal. Sei lá man eu ja sou meio brega com o sistema de store pq apesar de ser uma forma de organizar os itens tem muita coisa confusa ali no meio. Store pra comprar item mas nem tudo da pra comprar, tu ganha credito e mal usa eles pra nada. Tu acessa os perks do vip pelo store etc. Acho que botar mais coisa vai confundir o cara. caso fosse tudo concentrado nesse !topdefender ate acho o valido.

Se tivesse como voltar no tempo eu mantinha o !zclass pra escolher skin, com descrição da mesma ali se é de vip, vip deluxe, vip do rank mensal. 

Teria um !vip pra caso o cara nao fosse vip aparecer como compra e se for aparece o menu de perks de vip com tudo que ele tem acesso, passava oq tava na store tudo pra isso sem esse esquema de credits.

Teria um !tag que abre um menu pra mudar tudo da cor e etc da sua tag. Ali embaixo estaria um event tags e special tags. Tu pode clicar em todas as tags especiais mas caso vc nao tenha ganho aparece uma msg de tag de qual evento foi e quando. As que vc tem acesso apareceria com uma estrelinha na frente.

E ficaria por essas mesmo. Em caso de eventos temporários onde se comprava coisa por esses credits do store simplesmente muda pra time online no servidor e permite o acesso deles por um comando !especial/!tempolimitado sei la.

> 2. Fazer o score do tab como score do top defender, é basicamente o mesmo sistema da gfl do css, o numero mostrado nos seus assists equivalem a posição atual em que você está e obviamente quem estiver nas primeiras posições vai estar no topo do score.

No CSS até era Ok no tab mas o melhor ainda era sua posição no topo superior esquerdo. Aparecia sua posição junto com o quanto que faltava pro proximo, e caso tu fosse o primeiro o quanto na frente tu ta do 2 segundo. O tab pra mim da kill pra quem foi o top defender do round e quem zerou o round ganha uma estrela de MVP.

> 3. Mostrar os 5 primeiros top defenders no final de cada round, mas obviamente so os 3 primeiros ganham recompensa. Isso é mais para visualização de quem chegou perto de alcançar os 3 primeiros.

Tanto faz isso pra mim. Na real o certo seria mostrar a posição que tu ficou no round no chat e no HUD não apenas o quanto tu deu de dano. No momento no chat não mostra nada sobre ti e no HUD so mostra seu dano.

------------------------------------------------------------------------------------------------------------------
Sobre a mensagem no HUD que tu foi salvo da infecção é pq muita gente nem sabe dessa feature do top defender. Precisa mostrar que tu foi salvo. No source é mostrado uma mensagem junto com um som de renascimento tipo assim: https://www.myinstants.com/instant/angelical-oooh/ kkk

**Comment by lucaslinha** [comment]
A ideia do score é justamente essa que o alma citou, saber a posição de cada um pra ver se os cara toma vergonha na cara.

**Comment by hcjordao** [comment]
Cria 3 posições de posicionamento do HUD pra tipo de tela e gg

**Comment by alminha021** [comment]
precisa de som não, muita frescura.
Quanto a ms do hudg, nao eh necessario mas nao vai prejudicar nada ter ele, por mim se der pra implementar seria ok.
Quanto a entwatch no tab, eu particulamente nao uso o hud, logo so sei qm ta com materia pelo tab ou pelo chat. Nao uso pra deixar o mais clean possivel a vista.
Mas isso sou eu... por isso prefiro q mostre a quantidade de dano da galera no console mesmo, todo fim de round. 
Por mim vcs decidem, console ou no tab, td da pra se acostumar. Qualquer coisa qm nao usa hud , pode começar a usar tbm, quem gosta de materia acho q jah usam, pelo menos a maioria. Existem alguns casos a parte tipo eu q nao gosta de jeito nenhum do hud.

**Comment by hcjordao** [comment]
Repeita o somzinho de 2s. O povo vai se tocar que foi salvo por defender. Seria bem nice. Depois precisa alinhar quais updates querem que entre no top defender.

**Comment by hcjordao** [comment]
@quasemago comentarios sobre essa melhoria? 🐦

**Comment by hcjordao** [comment]
Att o topico ocm o que foi alterado até hoje. Ainda acham necessárias essas mudanças?

**Comment by lucaslinha** [comment]
Sim, log de dano sempre sera bem vindo, mas da um trabalhinho pra fazer.

**Comment by hcjordao** [comment]
Removi as firulas extras de coroas e alterações na estética do jogador já que é um pouco mais chato de fazer e não é necessário no momento. Entretanto queria fechar isso com uma alteração simples no código de adição da proteção de infecção ao segundo e terceiro top defender do round. 

1 - 100% de chance de proteção
2 - 75% de chance de proteção
3 - 50% de chance de proteção

Jogadores que defender precisam estar vivos, não deixo 100% para o cara não fazer o minimo e achar que está safe.

**Comment by hcjordao** [comment]
@quasemago depois adiciona a proteção de infecção para top defender assim como está acima plox

**Comment by quasemago** [comment]
Done

**Comment by hcjordao** [comment]
Testei bastante e está funcional. Fui protegido da infecção como top def 2 e 3, e fui infectado tbm sendo top def 2 e 3.
