### ISSUE TITLE
Warmup no Server.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#29]
Precisamos de um warmup no server para ajudar a quem demora muito para carregar os mapas, em certos mapas por exemplo os cts que carregaram 1 ja conseguem ganhar o 1 round e quem carregou tarde so lamenta.  Não so isso como também quem carregou rapido ja sai na frente do cash do zshop em relação aos outros jogadores. 

Mas precisamos de um warmup bem feito e não apenas um warmup genérico igual ao do propio jogo. Primeiro que ele precisa ser dinamico, ou seja se ele detectasse poucos jogadores ele setaria um tempo maior, se ele detectasse uma quantidade media de jogadores no server, ja seria um tempo menor para iniciar.  E também vale lembrar que durante o warmup ambos ct e zm precisam estar sobre o efeito de god para evitar qualquer falso positivo.

**Comment by quasemago** [comment]
Para mapas mais novos é de boa implementar isso no sistema de level deles, mas os antigos tem que refazer tudo.

Não acho necessário, vai ser um trampo do kct.

**Comment by lucaslinha** [comment]
Faz um generico com apenas um god então.

**Comment by quasemago** [comment]
@hcjordao O que tem a dizer? pra mim é totalmente desnecessário.

**Comment by hcjordao** [comment]
O servidor dor gringo tem um esquema de warmup no servidor deles, precisa de uma porcentagem de jogadores ingame pra iniciar o mapa. Se for dar um trampo grande pra fazer melhor postergar isso indefinidamente qnd não tiver nenhum update pra se fazer aí faz isso dai. Da pra dar uma varrida nos fóruns do alliedmodders pra ver se existe algo do genero. Server da GFL não tem isso e eu não vejo como uma necessidade em comparação ao rework do líder, top defender, mão bônus e fixes de mapas em geral.

**Comment by lucaslinha** [comment]
Não é prioridade, mas é uma necessidade, disto não se tem duvida. Esses falsos positivos de zshop, 1º round de qualquer mapa sempre vai ser um round perdido e mapas que os 1º a carregar sempre vão vencer o mapa são um problema na minha opnião.

**Comment by hcjordao** [comment]
Não vejo como um problema isso. Não me incomoda tanto isso tirando no mirrors edge o primeiro nivel que é o mais irado. Fora esse mapa eu realmente não me interesso, pois independentemente do povo zerar de primeira o mapa se tiver gente ainda querendo zerar o rtv ou nao vai ter sido liberado ou vai recem ter sido liberado que ainda da chance de ser jogado um round a mais.

**Comment by hcjordao** [comment]
Problema são mapas que isso ocorre e um jogador fica mocado em um lugar e o zm ao inves de avançar o mapa pra avançar o tp, ficam tentando pegar ele e o mapa fica travado ali.

**Comment by hcjordao** [comment]
Por enquanto não vamos implementar isso. Talvez futuramente. Até lá issue fechado.
