### ISSUE TITLE
m249 deve voltar a nossos servidores?

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#30]
1. Todos os mapas
2. Todos os mapasl, mas aumentar preço do rebuy. Atualmente 4600 por ai
3. Em alguns mapas
4. Em alguns mapas, mas aumentar preço do rebuy. Atualmente 4600 por ai
5. Não voltar.

**Comment by lucaslinha** [comment]
2. 
Ela seria bom apenas para mapas especificos, mas o problema é quem vai ficar encarregado de colocar ela nestes mapas especificos ? Pq eu mesmo ja tenho coisa demais pra me preocupar, então acho que libera pra todos e aumentar o preço é a melhor solução.

**Comment by alminha021** [comment]
5 ou 4.
seguindo essa logica, se for liberar ela em mapa especifico, prefiro q libere a poison em mapa especifico tbm, 
do jeito q ta sem negev e m249 ta bom, taoa prendendo a jogar, se for liberar opressao , q aumentem a taxa de infecçao e buffem zm.

**Comment by quasemago** [comment]
2

**Comment by hcjordao** [comment]
Ambiente de testes por uma semana.
