### ISSUE TITLE
Vento do dreamin na whitelist 

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#31]
fraquinho fraquinho.

**Comment by hcjordao** [comment]
Pega o hammerid que posso inserir no .txt

**Comment by quasemago** [comment]
@hcjordao algum progresso nisso?

**Comment by hcjordao** [comment]
Arrumado, ja adicionei na whitelist e está upado no server. Irei fechar o issue, se continuar bugado so reabrir.
