### ISSUE TITLE
Nerf nesse rank de vip.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#35]
Na minha humilde opnião, esse vip de rank ta muito op, com um vip com tantos recursos e com facil acessibilidade, o individuo nunca vai querer comprar um vip no server, o ideal é esse vip ser uma versão limitada do vip PRO e não ser quase um vip PRO. Ele precisa ser uma degustação do verdadeiro vip. 

Eis o que eu penso sobre os recursos : 

. Slot Reservado = Não precisa, so a imunidade de kick.
. Tracer = Sem problemas 
. Double Exp = Sem problemas 
. Pets = O ideal seria limitar e não ter todos de mao beijada.
. Destaque no chat = Mesma coisa, o ideal seria ter o recurso limitado.
. Nominate gratis = Sem problemas 
. Fake Inventory = Sem problemas 
. Desconto = Sem problemas 
. Double He = Nem ferrando, tem que ter so uma, duas he's é pra quem paga.
. Skin Color = Sem problema. 
. Skins = Não tem acesso, pelo menos eu acho. 
. Zmarket = Nunca ouvi falar.

**Comment by quasemago** [comment]
No caso eu teria que criar um novo plano que seria identificado como **VIP_RANK** por exemplo. Isso requer muitas modificações tanto no **VIP Manager** quanto nos plugins que fazem uso desses recursos (Store, etc).

O que acha @hcjordao ?

**Comment by danielhidalgojunior** [comment]
Não é só o top 1 que ganha o vip PRO? Não vejo problema nenhum se for esse o caso. O que poderia mudar é colocar uma regra pra impedir esse monopólio do rank afinal são sempre os mesmos que ficam no top. Talvez fazer com o vencedor de algum mês fique pelo menos 2 meses sem poder pegar novamente o VIP, mesmo que ficasse top 1. Creio que assim iria deixar mais justo para as pessoas que não passam o dia todo com o cu na cadeira do pc.

E o VIP PRO é justamente para valer a pena estar no TOP 1, se for pra botar algum vip bosta capado no lugar só vai diminuir a vontade do pessoal de chegar no top.

**Comment by alminha021** [comment]
Não é dificil pegar top 1. Basta morar no servidor, se os cara quiserem podem acampar lá e tirar o vip do pastor q ta sempre top 1/2/3 . Não vejo problema em ganhar sempre, se não temos outros jogadores tão regulares ai nao podemos fazer muito, pegou o vip "merecidamente".
Eu e o haru estamos banidos do rank , e estamos indo rumo ao top 20 top30 pra vc ver como é facil, isso so com pontos de mother e top defender. 
Mas concordo em limitar algumas coisas, principalmente a he "extra" , slot reservado, uma mudança pra anti kick seria legal tbm, pro cara pear top 1 o cara ja mora la no server, vai mudar quase nada.
prioridade pra quem paga, sempre.

**Comment by lucaslinha** [comment]
É apenas o top 1 que ganha ? Eu pensava que era top 3, mas de qualquer forma a double he e slot reservado são muito op mesmo sendo apenas pra 1 pessoa.

**Comment by alminha021** [comment]
eu acho q eh o top 1 eh deluxe e o top 2 e 3 eh vip pro, mas nao tenho certeza

**Comment by alminha021** [comment]
https://steamcommunity.com/groups/ZombieRageServer#announcements/detail/2818583225336546084
senao tiverem mudado, top 1 eh pro e top2/3/4 eh standard

**Comment by danielhidalgojunior** [comment]
Prefiro deixar como está mas fazer algo pra esse vip tbm passar nas mãos de outros jogadores que não dormem no sv

**Comment by gabrielacms** [comment]
Não há outra maneira desse vip do rank passar em outras mãos. Porque quem fica no sv o dia inteiro vai continuar ficando e quem não consegue ficar vai continuar não conseguindo. Concordo que tem que ser nerfado alguns dos benefícios. Por mim só o top1 ganhava o vip, top2-3 ganhava skin e o resto ganhava no máximo o colors (se a skin do trooper fosse ficar como default forever). 

Ou continuar dando vip para top1/2/3 ( com benefício limitado ) e esse vip que daria para o top4 ser sorteado entre o top20? Só consigo ver outras pessoas ganhando vip se for por sorteio. 
Ou usar o gameme para esse vip do top4. Esse ai os jogadores nem precisam ficar sabendo. Ao invés de usar a quantidade de pontos, usam os hits que voces tanto comentam. Pelo menos vai valorizar quem defende.

**Comment by hcjordao** [comment]
Concordo que podemos reduzir o numero de skins exclusivas para os players até o top 20, poderia ser reduzido pra top 5 ou top 8. Podemos fazer a troca de VIP simples no top 2 e 3, deixar apenas pro top 1 o VIP Pro, e o resto apenas skins exclusivas no servidor.

Exemplo:
- Top 1 (Vip PRO + Todas skins exclusivas vindas do rank)
- Top 2-3 (Skin exclusiva do Top 4-8 + uma outra skin exclusiva)
- Top 4 - 8 (1 Skin Exclusiva)

Acho que o premio do VIP pro top 1 é mal divulgado. Se o cara ta ali o dia inteiro no server com 8 pessoas online pra farmar o rank não tenho nenhum problema com isso e tbm não tenho nenhum problema que esse cara seja vip por 2 anos seguidos. O fato é que tem que haver jogadores que inicializam o server pra permitir que ele seja lotado a noite, quem lembra quantas vezes chegavamos em casa e vimos o server morto de noite pq nao tinha ngm jogando de tarde e por isso ngm entrava a noite. Nós jogadores mais velhos so vamos entrar no server se estivermos ou bem entediados ou se o server tiver pelo menos 15+ jogadores, as vezes nem isso, não venham me falar que não é verdade pq eu sei, acho que o unico que não é assim é o @alminha021 que inumeras vezes ele fez o kickstart do server no icecap, posso estar errado mas não acho que é o caso. Então o vip tem que ser OP sim, ele da tudo que um jogador quer mas tbm nao dando oq ele mais quer que é uma skin exclusiva somente dele.

**Comment by quasemago** [comment]
@hcjordao Então ficou assim:

- TOP 1 (tier 3): Continua como já está, recebendo o VIP PRO e todos seus features.
- TOP 2-3 (tier 2): Skin _)esse por consequência por ser um tier acima, também recebe o reward do tier 3__
- TOP 4-8 (tier 1): Skin

Concordam? Acho mais justo desse tipo, dar skin até o TOP 20 é demais, e o TOP 1 merece receber todos os benefícios sim pois é um cara que está sempre ativo levantando o servidor.

**Comment by danielhidalgojunior** [comment]
Nem sempre o cara com mais pontos é o que levanta ou passa mais tempo no servidor. To top 4 no rank e não tenho um terço de horas de uns caras aí desde o começo do mês.

**Comment by danielhidalgojunior** [comment]
Gostei da ideia da gabi de sortear o vip standard para o top 20

**Comment by alminha021** [comment]
Fanzack tu eh o sexto em horas no gameme, por mim se o cara ta no server direto nao vejo problema de ganhar o vip sempre todo mes, querendo ou nao o cara fez o esforço pra ta la direto, infelizmente poucos tem esse tempo sobrando pra ta lá.
Por mim ok as mudanças, so 1 vip decente ta ok, deixa os top se matarem pelo top 1.
ate pq devia ter muito acomodado do top 2 ao top 4 q ganhava vip.
por mim deixava as 2 skin de vip de rank pro tier 3 , e o tier 2 as mesma skin mais alguma coisa, enfim tanto faz, skin ta ok, ams se tiver algo mais, ia ser bom.
A ideia de dar o colors pra eles quando acabar o evento de ferias tbm eh daora, se o stormtropper continuar la eh claro. ( da ate pra aumentar o top tier 1 para top4-12 por exemplo )
Nao mudaria tanto assim (reduçao) de ganahdores pq pode desanimar alguns.

**Comment by hcjordao** [comment]
Não é um rank de tempo apenas. É um rank de skill onde horas dedicadas fazem vc ganhar pontos. O top 1 online está em na posição 13 do rank do vip justamente pq não basta ficar online no servidor tu tbm tem que se esfoçar um pouco pra ganhar o mapa que é o proposito do rank, atender ambas as necessidades que precisamos. Se não voltaríamos a mesma discussão que o rank por tempo tinha um monte de batata se achando que estava um na frente do outro por causa de tempo como se fosse alguma coisa. Ou pra outra discussão que o rank permanente de skill trazia a toxicidade a tona, esse rank é o trade-off de misturar os dois.

**Comment by lucaslinha** [comment]
Não precisa mexer em ganho de vip (esse não é o ponto desse issue). É sobre nerf dos beneficios do vip de rank, essa he dupla e slot reservado são 2 coisas fortissimas pra deixar pra uma pessoa que não esta contribuindo financeiramente pro server.

**Comment by lucaslinha** [comment]
"Ah mas ele ta contribuindo com o tempo dele la." Esse negocio de que o top 1 representa o cara que mais jogou no server é furada, representa o cara que mais acumulou pontos, não confundam uma coisa com outra. O berg por exemplo que trabalha boa parte do dia e joga so a noite no server conseguiu pegar o top 1 por varios meses no passado.

**Comment by lucaslinha** [comment]
Quer dar o vip pra quem ta contribuindo com tempo ? Pega quem ficou mais tempo online e da para ele então.

**Comment by quasemago** [comment]
Bom, podemos aproveitar esse issue para mexer em quem vai receber tais coisas como o haru sugeriu. Quanto ao TOP 1 limitado, talvez a HE e os pets já seja de bom tamanho pois acho justo o cara receber o slot reservado para garantir a vaga nos eventos.

**Comment by hcjordao** [comment]
Como eu disse é um trade-off de skill e tempo online. Se tu quer passar menos tempo no servidor mas ainda ser top 1 basta zerar os mapas ou tu pode dedicar mais tempo no server mas ainda assim precisa ter skill pra zerar uns mapas. Pra mim nada roubado em dar uns perks a mais pra quem é top 1 no servidor. Ronning ja ta trabalhando na HE que da replace que vai ter um tempo reduzido. Não acho nada OP dar isso pra 1 jogador no servidor.

**Comment by hcjordao** [comment]
@quasemago chegou a reduzir o plano de top points no rank?

**Comment by quasemago** [comment]
Ainda não mexi nada, mas antes de atualizar o tier farei as mudanças citadas na minha resposta anterior:

> @hcjordao Então ficou assim:
> 
> * TOP 1 (tier 3): Continua como já está, recebendo o VIP PRO e todos seus features.
> * TOP 2-3 (tier 2): Skin _(esse por consequência por ser um tier acima, também recebe o reward do tier 1)_
> * TOP 4-8 (tier 1): Skin
> 
> Concordam? Acho mais justo desse tipo, dar skin até o TOP 20 é demais, e o TOP 1 merece receber todos os benefícios sim pois é um cara que está sempre ativo levantando o servidor.
