### ISSUE TITLE
Aproveitando o site da Zrage ...

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#38]
Aproveitando que o site da zrage poderá ficar pronto um dia, so Deus sabe quando. Poderiamos aproveita - lo e fazer dele o nosso "fórum", incluindo nele o cadastro dos jogadores, com esse cadastro poderia ser feito uma série de coisas das quais eu pensei em algumas : 
 
. Cadastro de usuários: com o cadastro abriria uma série de oportunidades para o server como status de member por exemplo, com este status ou cargo, beneficios poderiam ser aproveitados tanto no server quanto no discord. 

. Status de member no DS: falando um pouco sobre votação primeiramente, esse formato de votação atual não da certo de maneira alguma, ele é aberto para qualquer um votar, desde os falsos ativos quanto a quem vota e nem sequer aparece no domingo para jogar, sem contar aos sucetiveis votos trolls ou raid de votos que ja aconteceu antes. Convenhamos que é injusto uma pessoa que não contribui para os eventos participar da decisão de mapas ou ate mesmo trolls que votam em todos os mapas menos em 1 por n motivo, por isso creio que está na hora de "fechar" essa votação para as pessoas que realmente tem interesse nisso, como acontecia antes quando a votação era no grupo da steam. Enfim apenas membros cadastrados no site teriam cargo no discord e poderiam ver a sala oculta das votações. 

.  Abas auxiliares: ja vi que vai ter um espaço para obter todos os mapas da rotação, da pra aproveitar um espaço e colocar as skins que são usadas atualmente no server como as atuais de rank e as de vip, sem contar as skins disponiveis para o vip deluxe. 

. Desconto no vip; como uma forma de impulsionar os cadastros no site, poderia rolar um desconto no vip apenas para a 1 vez de cadastro do membro. 

. Status de member no server: Essa parte não vou comentar pq não tenho noção do nivel de dificuldade que seria colocar uma nova classe no server, mas fica a sugestão.

**Comment by alminha021** [comment]
- cadastro so logar a steam no site ta ok jah. vc precisa logar pra comprar o vip mesmo

- eu entrei umas 10x no maximo no site, so entro quando eh pra comprar vip.

- Votação fechada eu não concordo, ia limitar muito a votação. Infelizmente tem muito voto ai q atrapalha mesmo, mas acontece... temos que aceitar e jogar o mapa escolhido por votação.
Eu particularmente prefiro tryhard a eventos, por conta de muitas vezes cai um combo lixo ou mapa q nao curto por meio de votação.

- Colocar informaçoes no site seria OK , informaçoes de mapas nao zerados , dificuldade etc...
Informações de rank , evento , explicar sistema de vip e rank isso seria muito bom mesmo. 

- Desconto, sei la, o cara tem q logar na steam pra comprar, com,o falei, cadastro nao vejo muito p porque ter.

**Comment by lucaslinha** [comment]
Isso aqui não vai para frente, melhor fechar o issue.

**Comment by quasemago** [comment]
Fechado, pode ser reaberto no futuro.
