### ISSUE TITLE
Bug spawn ZM ze_volcano_escape_v4fix

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#4]
Fim do mapa os zms não respawnam e o mapa não acaba, além do que não são ganhados pontos na vitória dos humanos.

**Comment by lucaslinha** [comment]
vou colocar a vers do rules of p pra ver se é melhor

**Comment by hcjordao** [comment]
@lucaslinha qual a versão completa?

**Comment by hcjordao** [comment]
Fiz uma gambiarra, não tenho ideia se vai funcionar provavelmente não. Não entendi qual é o bug que ocorre, fui dar uma olhada no mapa pra ver se tinha algo de errado com a nuke, unica coisa que ocorre é o mesmo nome para ambas nukes em lugares separados, mas não acho que isso buga o respawn do zm.

**Comment by hcjordao** [comment]
Joguei esses dias e ainda tava bugado. Vou remover esse mapa do mapcycle ja que a presença dele nao adiciona em nada. Mapa ez feito de forma bosta.
