### ISSUE TITLE
Matéria de zm crashando o jogo do pessoal

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#42]
Mapa: ze_deadly_stance_a3
Matéria: ZGas

Ocorreu em 2 rounds seguidos, o CSGO das pessoas que estavam perto do ZM que estava com a matéria crashou. 
Acredito que só de estar perto da matéria faça o jogo crashar. Mas o portador da matéria não crasha.
No primeiro round, o Giz pegou a matéria e todos os cts que ficaram próximos a ele crasharam. 
No segundo round, eu peguei ela para testar, o Feluco e o SOUTH PARK que estavam próximos a mim crasharam.

**Comment by lucaslinha** [comment]
Apenas a materia está com esse problema ? Excluir ela do mapa seria uma opção, ou você acha que deveria retirar o mapa ?

**Comment by gabrielacms** [comment]
Infu, infelizmente não chegou a testar tudo desse mapa, o pessoal quis mudar o mapa por conta dos crashes. Mas eu acho melhor só remover essa matéria por enquanto e deixar o mapa lá para ver se tem mais coisas que estão bugadas.

**Comment by quasemago** [comment]
@lucaslinha @gabrielacms Algum progresso sobre esse issue?

**Comment by lucaslinha** [comment]
mapa removido ja.
