### ISSUE TITLE
Pauta Reunião #1 

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#44]
- [x] Liberar todas as armas, fazer config de restrição individual por mapas. Basicamente mapas fáceis e médios que não tem boss permitem o uso de armas alternativas. 
- [x] Config batata (molotov e smoke, preferencialmente só molotov de inicio acho que ja ta bom)
- [ ] Liberar buymenu do csgo junto com zmarket ao invés do atual guns
- [ ] Modo de jogos alternativos special configs. Ativação por meio de votação (Mais de 70%) do jogadores ou por force de admin, ativa um modo especial aleatório dentre os possíveis. (Knife Hit Kill no ZM, Knife Knockback no ZM, Fail Nade que são granadas que tem que empurram o zumbi, Modo vip se o ct que for vip morrer geral perde o round, Munição Infinita, Zumbis Mais Rápidos mas com menos vida, Zumbi com Leap Jump, Enable bhop ativado, sei lá, mais ideias please nos comentarios nem todas que eu falei aqui precisam ser válidas)
- [ ] Utilidades dos créditos através de cosméticos bem caros no server pra manter jogador a busca do farm.
- [x] Diminuir quantidade necessária pra ativar o rank de 6 pra 2 ou 3, deixar bem baixo pro povo ter algum motivo de jogar no server.
- [ ] Aumentar a pontuação por tempo online no server acho que seria bem interessante pra dar um motivo a mais de ficar no servidor.
- [ ] Transferir mensagem de regras e comandos úteis do menu para o chat quando o jogador entrar.
- [x] Trocar votação de mapas atuais do server pra um que possui mais opções. Na Rage na hora da votação tem cerca de 8 mapas pra votar ao invés de só 4/5. Mais opções = menos risco de cair um mapa tipo dark souls.
- [x] Permitir fala durante a votação pra pedir votos, acho que é melhor cair num mapa muito mais jogado do que cair num dark souls da vida não sei oq vcs acham. Pedir diferente de spammar e gritar no mic.

**Comment by lucaslinha** [comment]
Concordo com todos sem objeções exceto a config batata onde deixarei meu comentario :
  Tem que começar com tudo no inicio do round sim, tem vip ate hoje que não sabe fazer rebuy de he, imagina novato. Sobre a molotov , ela retira stamina (coisa que a he ja faz), muito mais viável por a molotov de push da mapeadores. E precisa reduzir o speed dos zms também, grande parte da mortes dos batatas não é por defesa, mas sim pq foi morto enquanto recuava de faca na mao pq o zm alcança o ct muito rapido, nao adianta você ser um Deus dos holds com todas essas granadas e morrer recuando.  Basicamente essa config tem que favorecer 100% os cts, é doloroso pros amantes de zm ? é ... mas tem que entender que quem vem de comp e essas coisas gosta de dar bala na cabeça de zm e não morrer e ficar jogando de faquinha o tempo todo, o novato gosta de ficar vivo e vencer o mapa como ct, ele precisa ter essa sensação de vitoria para gostar do modo. 
  Agora é mais um sugestão que eu não sei se funfa na pratica, mas da pra fazer um comando pros players como !potato ou !tryhard, se o mapa tiver muito dificil, os players vão votar para mudar a config atual e se for o caso contrario também, é mais para caso não tenha adms para mudar a config atual.

**Comment by hcjordao** [comment]
A unica opinião que eu tenho sobre isso de ter comando pra ativar algo é que eu não acho que o povo batara vai utilizar.

Diferente do comando de 4fun de config adicional que provavelmente vai ser usado quando ja tem veterano no server o comando !potato nao vai ser usado se so tiver batata no server então é melhor ser a config batata sempre e ter um !tryhard ou sei la pra ativar a config atual do servidor

**Comment by gabrielacms** [comment]
1- Modo de jogo:
    -  Não pode ficar ativo em todos os mapas, principalmente em mapas tryhard só se tiver adm no sv e o pessoal querer tentar. 
    - Modos de knife: Eu acho que seria melhor ter só um modo de faca. Sabemos como são os brazucas e a chance de confundirem o que vai ocorrer em cada um dos modos é grande. E convenhamos que matar o zm é bem mais legal do que só dar um boost nele e o bhop podia entrar nesse modo. Mas minha opinião só. 
     - Fail nades: Nem todas devem dar fail Algumas vão funcionar normal mas outras vão dar boost. 
     - Na GFL eles tem um modo muito legal que é o do sephiroth. Um mother aleatório é escolhido e ganha laser para tacar no ct. (estilo aquele que o haru ficava usando) Só que esse laser não mata ele só dá slow no ct. 

2 - Shop : ze é um modo que você usa bastante a faca, trás uma parte das facas do zknifes pro shop e add mais models. Seria bom se o zm conseguisse usar tb. 

3 - Sobre a quantidade de mapas que aparecem na votação, vai ter ser um menu mais simples tb. Não vai poder começar no 4 e poderia ter uma opção de mapa aleatório. O plugin sortear um mapa que não caiu na votação como nextmap. O único problema é que pode cair um mapa difícil. 

O resto até o momento estou de acordo.

**Comment by lpcorrea** [comment]
Concordo com tudo que foi apresentado.

+ Teria como trazer o gift de créditos de volta?

**Comment by quasemago** [comment]
@hcjordao Quanto a ter mais opções de mapa teria que começar pelo numero 1, problema é que vai ter muito missclick.

**Comment by danielhidalgojunior** [comment]
É difícil os players organizarem um try hard por contra própria. Creio que o ideal é liberar tudo isso em todos os mapas, inicialmente sem exceção. Caso queiram a versão tryhard do servidor, poderiam o usar o comando tryhard no chat para iniciar a votação e caso quisessem reverter, usar o tryhard no chat novamente.

Creio que assim fique melhor pra todo mundo, afinal, o pessoal está acostumado a jogar nos mapas mais difíceis, então pq não deixar os batatas ganharem em algum desses mapas difíceis usando essas config pra se sentirem cabulosos?

**Comment by hcjordao** [comment]
Já fazem mais de 6 meses que essa pauta foi criada, recomendo fazer outra trazendo problemas que permanecem para essa nova.
