### ISSUE TITLE
Problemas no Stalker Ultimate_v2_3_g7t

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#46]
- Cura : A cura às vezes funcionava e outras não. Tinha vez que usava e aumentava a vida e tinha round que não aumentava. Foram vários rounds que tivemos que setar a vida dos CTS.

- FPS: não é novidade mais mas apenas deixando anotado. Algumas pessoas tiveram queda de fps e outras não tiveram. Para resolver o problema tinha que alterar config de vídeo do jogo. 

Algumas poucas vezes teve um aumento na var do servidor durante o mapa. Mas nada que afetou a gameplay. Tem que ver se tem alguma solução ou uma outra versão mais otimizada do mapa para testar.  Eu tenho certeza que muita gente ali só não desistiu e quitou do servidor pq era um evento. Porque se for um mapa no dia-a-dia o pessoal quita fácil. E o mapa é bem tranquilinho, facilmente viraria um overplayed do sv.

**Comment by lucaslinha** [comment]
Tem um server russo que usa outra versão, vou entrar pra ver dps. Infelizmente esses mapas assim você so tem noção se ta bom ou não quando testa com muita gente e dai a zrage so deixa pra jogar em evento, fica complicado.

**Comment by quasemago** [comment]
@lucaslinha Algum progresso?

**Comment by lucaslinha** [comment]
Testar outra vers dps, tem que mandar pro sv ainda.

**Comment by lucaslinha** [comment]
Tem uma nova versão no nominate, so falta testar para saber.

**Comment by hcjordao** [comment]
Podemos testar essa semana.

**Comment by quasemago** [comment]
Favor, testarem o mapa!

**Comment by gabrielacms** [comment]
Jogamos esse mapa essa semana. A questão da queda do FPS aparentemente foi resolvida, não ocorreu queda de fps em nenhum momento e não houve nenhuma reclamação. Mas vou tentar jogar ele essa semana novamente ou fazer algo (evento) nele já que nesse teste chegamos só até o 2° lvl xD

**Comment by quasemago** [comment]
@gabrielacms @lucaslinha Atualização sobre esse issue?

**Comment by lucaslinha** [comment]
A versão do server ainda não foi testada completamente, eu to esperando os boludos testarem a nova versão no sv deles, quero ver se ta funcional.

**Comment by hcjordao** [comment]
Versão está diferente no mapcycle.txt, já foi testado, ou ainda estamos aguardando?

**Comment by hcjordao** [comment]
@lucaslinha sabes me dizer?

**Comment by hcjordao** [comment]
Vou fechar esse issue devido falta de info sobre o mesmo. Caso o bug esteja ainda ocorrendo abrir de novo please.
