### ISSUE TITLE
CS crashando no modo barricada - ze_SUPERSHITSHOW_a2

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#48]
O modo barricada nesse mapa faz o CS de alguns jogadores crashar. Ocorreu agora a pouco. Tinha umas 16 pessoas no servidor e caiu para 4. Não ocorreu nada de específico no round, o pessoal mal tinha saído do spawn e começou a cair.

**Comment by lucaslinha** [comment]
retirar o level do logic_case resolve.

**Comment by quasemago** [comment]
@lucaslinha algum progresso nisso?

**Comment by lucaslinha** [comment]
To tirando o modo do mapa.

**Comment by quasemago** [comment]
Level barricada foi removido, precisa de testes antes de prosseguir com o fechamento do issue.

**Comment by lucaslinha** [comment]
Creio que esta funcional, melhor fechar o issue
