### ISSUE TITLE
Bug de dinheiro ze_indiana_jones_v4a_004_p4

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#5]
Humanos aparentemente startam com uma quantidade errada de dinheiro no round start. Provavelmente um force cvar no round start feito pelo mapper.

**Comment by quasemago** [comment]
Provavelmente o mapa deve estar forçando o netprop "account" dos jogadores. Uma boa analisada no vmf deve ser suficiente para saber o motivo disso.

**Comment by hcjordao** [comment]
Fixado, esperando sync do repo com o server.
