### ISSUE TITLE
Adicionar feature de mapa novo a votação.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#50]
Alguns servers possuem isso e chama bastante atenção de quem está votando, basicamente mapas recem adicionados recebem um (NOVO) do lado do nome durante o menu de votação. Isso poderia ser uma tentativa dos jogadores terem um incentivo a joga - los e ter a noção de que um mapa novo foi adicionado ja que a maioria não acompanha changelog do discord.

**Comment by quasemago** [comment]
Só adicionar os mapas e testar.
