### ISSUE TITLE
ze_surf_dark_fantasy_v1go3 travando durante o loading

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#51]
É apresentado alguns erros de "missing PCF" que provavelmente tem ligação com o problema.

Mapa foi retirado da rotação temporariamente.

**Comment by quasemago** [comment]
Algum progresso nisso? @lucaslinha

**Comment by lucaslinha** [comment]
Ainda não sei o motivo que causa isso, testei no servers dos boludos e isso não acontece, parece ser um caso isolado na zrage. De qualquer forma o haru pediu para deixar de fora do nominate.

**Comment by hcjordao** [comment]
Vamos deixar para realizar um teste futuramente no mapa. Qualquer admin se quiser pode botar o mapa de nextmap depois de uma votação para fazer o teste.

**Comment by quasemago** [comment]
Mapa estava corrompido em nosso FastDL, já foi reupado!
