### ISSUE TITLE
Skin do slender invisível (ze_slender_escape_rc2)

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#52]
O jogador fica invisível e acaba sendo necessário dar slay no mesmo para desbugar.
Mapa foi retirado temporariamente da rotação até ser fixado.

**Comment by quasemago** [comment]
Potencialmente fixado.

**Comment by lucaslinha** [comment]
Fixado. Dps de uma att da valve qualquer coisa parentada a um objeto invisivel se torna invisivel tmb. O zm não fica mais invisivel ao pegar faca logo o slender tmb não.
