### ISSUE TITLE
Top Defender

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#53]
Acho interessante como falei anteriormente em algum dia da minha vida. Um buff de anti-infecção em top defenders. Para top 1 já está funfando mas acho que top 2 e 3 tbm podem ter.

Top1 - 100%
Top2 - 75%
Top3 - 50%

**Comment by lucaslinha** [comment]
Não concordo com esse tipo de rng, confunde demais a cabeça das pessoas, uma hora ele ganha imunidade e outra hora não, ou 100% ou nada.
