### ISSUE TITLE
Leve alteração no Lider.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#54]
Alteração no lider: 
1. Adição do beacon rainbow no menu. Exemplo: https://gph.is/g/4LgnzkR (Ele basicamente pisca 1 cor diferente a cada tick). 

2. Caso for possivel tmb faz isso com o tracer, basicamente um tracer rainbow (Explicado acima) que seria exclusivo do lider, saber onde o lider esta atirando é muito util em diversos mapas.

**Comment by quasemago** [comment]
Mas teria que trocar o beacon, o atual do server é bem pequeno

**Comment by lucaslinha** [comment]
A ideia do beacon atual é boa e tal, porém ele é bem fraco, passa despercebido demais.

**Comment by hcjordao** [comment]
Eu acho bom isso também, apesar de laranja ser uma cor chamativa, como cada mapa tem suas cores variáveis as vezes pode passar desapercebido o lider.

**Comment by lucaslinha** [comment]
é so adicionar 2 tipos de beacon no menu com salvamento de preferencia, cada um pega o que quiser.

**Comment by quasemago** [comment]
Beacon rainbow já foi implementado. Farei alguns testes com o tracer nos próximos dias.

**Comment by quasemago** [comment]
Tracer rainbow implementado.

**Comment by hcjordao** [comment]
Já foi testado e está funcional novos bugs/enhancements em outro issue.
