### ISSUE TITLE
Level alteração no comando de level. 

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#55]
Sempre que rola um mapa que ninguem conhece sempre tem gente perguntando quantos leveis tem o mapa, seria bom o comando do level listar uma info com todos os leveis bonitinho.

**Comment by quasemago** [comment]
Eu já estava pensando em fazer isso, aparecer algo do tipo:
- Level atual é X valendo Y pontos. [1/5]

**Comment by lucaslinha** [comment]
Sim pode ser dessa forma.

**Comment by quasemago** [comment]
Feito. Teste antes de fechar o issue.

**Comment by quasemago** [comment]
Feito.
