### ISSUE TITLE
Implementação do hitmarker mira.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#56]
A pedido/sugestão do paivones que solicitou uma adição de um hitmarker vermelho localizado na mira como indicador de hit em zms e bosses, usado em alguns outros servidores.

Exemplo : https://imgur.com/a/7yFMorx

**Comment by hcjordao** [comment]
Podiamos add isso dai e remover os outros, deixando só um obrigatorio e padrao para todos os players.

**Comment by gabrielacms** [comment]
Sim e se puder colocar esse showdamage nesse hit ai vai ficar muito bom. É muito bom saber a quantidade de vida que o ZM tem. (eu acho pelo menos)

**Comment by quasemago** [comment]
Tudo isso já foi implementado.
