### ISSUE TITLE
Mudança na localização do hud dos top defenders.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#57]
Mudar a localização do hud dos top defender para o canto central inferior da tela, ja que o atual fica em cima do overlay de humans win, o que é feio demais. 

Exemplo: https://imgur.com/a/PP19FHR

**Comment by hcjordao** [comment]
Uma duvida sobre o hud, ele tem algum delay pra ser mostrado na tela?

**Comment by lucaslinha** [comment]
Como assim delay ? deu a win aparece.
