### ISSUE TITLE
Hud hint de mapas permanecem não funcionais.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#58]
Hud de plugins foi fixado, porém o de mapas continua com formatação zoada. 

Um dos managers da guc comentou isso em relação ao problema : 
"map messages problems is only related to hint text color."

**Comment by quasemago** [comment]
Fiz uma incrementação ao hotfix dos hint. Testem e reportem o feedback.

**Comment by lucaslinha** [comment]
Foi fixado pelo menos no minas tirith, tem que ver nos demais mapas.

**Comment by quasemago** [comment]
@lucaslinha Alguma atualização sobre esse issue?

**Comment by lucaslinha** [comment]
Ate agora não notei problemas quanto a isso.

**Comment by quasemago** [comment]
Ok, caso venha acontecer novamente basta reabrir o issue.
