### ISSUE TITLE
Pontuação Rank

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#59]
Eu acho a pontuação do rank atualmente casual e boa nos servidores. Entretanto, sempre fico com uma pulga atrás da orelha quando mapas com alta dificuldade não são jogados no servidor (nem alta, mas média).

Minha sugestão, que seja criada um .txt mesmo com todos os mapas do servidor, indicando quantas vezes passaram um nível.

Em caso de um level único: 
**ze_arctic_escape_p2 - Level Unico: 2 - Jogadas: 3** (Mapa foi jogado 3 vezes e passado 2)

Em caso de multiplos leveis:
**ze_bestkorea_v1 - Level Um: 5 - Level Dois: 3 - Level 3: 0 - Jogadas: 10** (Mapa foi jogado 10 vezes e em nenhuma vez zerarm o mapa)

O método automatico eu curtia mas creio eu que não deu muito certo, dessa forma podemos agir de uma forma mais manual e editar os pontos when we see fit.

Queria saber a opinião de vocês

**Comment by alminha021** [comment]
Eu queria assim desde o começo

Mas falaram "quem vai ter o trabalho de ficar olhando isso e arrumando"

**Comment by hcjordao** [comment]
Mas é um trabalho a mais. Só que do jeito automatico não da muito certo, o que da pra ser feito é postar aqui os resultados e discutirmos em um tópico mesmo e depois aplicar os ajustes

**Comment by lucaslinha** [comment]
O que quer dizer com isso ? acha que alterando o rank vai motivar a jogarem outros mapas ?

**Comment by gabrielacms** [comment]
Sei lá, apesar de ser interessante ao meu ver é um trabalho que não vai ter muito resultado. Pessoal não está tão vidrado em rank igual era antigamente. Alguns sim, obvio.. mas só querem mapas que conseguem passar. Nem aquele esquema de Death Points afetou isso. Jogam Pirates todo dia do mesmo jeito, jogam surf, supershitshow, 666 crazy escape, etc. 

Se quer fazer esse pessoal jogar mapa diferente, a única solução ao meu ver é removendo o nominate. Colocar o final de semana sem nominate ou só um dia, só vindo mapa random na votação.

**Comment by hcjordao** [comment]
Acho q alteração de pontos teria que ser acompanhada de anuncios no discord. Se não realmente mudar, não mudaria. Acho que o display de pontos no chat já seria bem nice que é algo ja está sendo discutido em outro issue.

**Comment by hcjordao** [comment]
Não sei se vai motivar todos, mas alguns farmadores de rank sim provavelmente e grande parte deles são bem vocais no server. Alterar a pontuação de mapas exemplo Santassination para ter uma pontuação bem maior que a normal mesmo sendo mapa fácil. Ou simplesmente forçar mapas toda semana com um anuncio no Discord. Esses mapas terão a pontuação tri, qua, quintuplicada nos níveis mais dificeis.

**Comment by alminha021** [comment]
ta pra pensar ate em Mapas da semana ou mapas do més , tipo semi eventos mensair/semanais se for fazer manual.
tipo:
**Mapa do mes de outubro:**
_sroomforest3 , santassinatiom , predator ultimate , temple of the demon god , fire temple
 - Mapas com 5x pontuações nos leveis mais altos ( caso de lvl unico 5x a pontuação) com mais de 25players
 - Removida temporariamente o death points_

**Mapa do mes de julho:**
_Mapa com o tema templo , 3x a pontuaçao. ( templo of demon god , temple raider, etc)
 - Mapas com 5x pontuações nos leveis mais altos ( caso de lvl unico 5x a pontuação)com mais de 25 players
 - Removida temporariamente o death points_

**mapa de abril (tema floresta) etc...**
etc...

sei la, eh so uma ideia.

**Comment by hcjordao** [comment]
@alminha021 Sim, o único problema de ser mensal é o farm de points extensivos. Um tempo um pouco menor acho de boas. Gosto da ideia por que ao invés do automatico dá um controle a mais para os ademeres. Se aprovarem a ideia já podemos começar.

**Comment by alminha021** [comment]
aprovo

**Comment by lucaslinha** [comment]
Por mim de boa, mas essa parte vai ser com vocês, eu ja tenho que cuidar de muitas coisas relacionado a mapa.

**Comment by hcjordao** [comment]
Sem problemas, eu posso ver com o @alminha021 e a @gabrielacms para me ajudar com esse tópico

**Comment by hcjordao** [comment]
Irei iniciar hoje e deixar que dure durante duas semanas. Vamos ajeitando medida que vai sendo encaminhado.
