### ISSUE TITLE
Player block Terra

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#60]
Deveriamos quando possível remover a forma de block de CTs com itens de humano de bloqueio de passagem? Assim evitando possíveis trolls no meio do mapa matando todo o time, ou continuamos do jeito que está?

**Comment by alminha021** [comment]
por mim continua. 
Quase sempre tem staff , e quando o cara faz o mapa ele pensa nisso, se a parede deve travar ou nao, se quebra se tem algue travado ou nao, faz parte do modo.
Fora que mapa eh zerado ai bastante ate.
e o cara que trola travando, vai trolar tapando a visão dos ct, entao sei la, nao vejo muito porque, vai deixar facil o que nao é tao dificil.

**Comment by gabrielacms** [comment]
Eu não sei, ao meu ver tem que analisar isso melhor. No discord voce comentou sobre o Wester mas aqui voce está comentando de uma forma geral, correto? Enfim, tem muito trollzinho que pega matéria sem saber como usa ou com a intenção de ferrar com o time mesmo. Em mapas de FF geralmente sempre tem adm on mas tem vários outros mapas que possuem Terra e nem sempre tem alguém da staff online. 
Nosso servidor possui maneiras de limitar a quantidade de CT que a pessoa consegue ver..então é uma coisa a se pensar. Ontem mesmo rolou algo parecido com a Terra no Shroom2. O cara que tinha a terra estava usando !hide e não viu que tinha gente na frente dele.

**Comment by lucaslinha** [comment]
primeiramente vc ja sabe como fazer isso ? ou pelo menos tem em mãos o material para isso ?

**Comment by hcjordao** [comment]
@gabrielacms Não tinha pensado dessa forma Gabi, mas realmente isso acontece várias vezes tendo o uso do hide. Ao meu ver podemos inserir.

@lucaslinha Isso é o de menos, se for possível fazer deve ser relativamente simples de fazer com um exemplo em mãos, resto é só uma mãozinha pelo número de mapas que existem esses tipos de itens. Caso não seja possível fazer em todos os mapas paciência.

**Comment by lucaslinha** [comment]
So quero saber onde você vai conseguir esse exemplo.

**Comment by hcjordao** [comment]
Eu já tenho um, por isso que abri o tópico querendo saber na staff, uno boludo me repassou :)

**Comment by lucaslinha** [comment]
Ah so me interesso nisso por mapa que tem barricada mesmo, ja que sempre tem um retardado travando o time.

**Comment by hcjordao** [comment]
Acho que o trabalho em barricada fica meio fora de mão pois marricada pode ser tanto por item ou por props no mapa. Items especificos de CT ficam mais fácil de trabalhar creio eu

**Comment by lucaslinha** [comment]
ah se for igual o castlevania é impossivel mesmo, agora em um minas é bem de boa.

**Comment by hcjordao** [comment]
Como houve indecisão na staff irei abrir uma votação no servidor, justo?

**Comment by hcjordao** [comment]
Mapa do Wester foi inserido no servidor e creio eu que já passei o stripper para o @lucaslinha para futuras adições em outros mapas, caso alguém queira o stripper me avise.
