### ISSUE TITLE
HUD Timers não estão resetando após final do round

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#61]
Foi verificado que após um round reset/fim do round, timers não são resetados. Idealmente após fim do round todos os timers no hud deveriam ser removidos. 

Mapa verificado -> **ze_raccoon_facility_v6b_p**

**Comment by quasemago** [comment]
Foi testado em outro mapa? pois atualmente os já são encerrados no round end.

```
public void OnRoundEnd(Event event, const char[] name, bool dontbroadcast)
{	
	for (int j = 0; j < MAX_CHANNELS; j++)
	{
		KillTimerEx(g_HudChannelTimer[j]);
		g_isHudChannelInUse[j] = false;
	}
}
```

**Comment by hcjordao** [comment]
Testei no mapa mencionado e não deu kill no hud timer, continuou funcionando no proximo round.

Pode ter sido um mini bug, vou ficar de olho se em outros mapas

**Comment by quasemago** [comment]
Pergunto isso pois nunca percebi isso em outros mapas, e se fosse o caso teria acarretado em algum problema no plugin visto que a limpeza dos channels é feita na forward do roundend.

**Comment by hcjordao** [comment]
É então só percebi nesse mapa. Vou ver se ocorre em outros.

**Comment by hcjordao** [comment]
Devido falta de updates irei fechar esse issues, caso tenham novos favor abrir novamente.
