### ISSUE TITLE
Weekly Maps #1

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#64]
Irei tentar manter aqui as atualizações de mapas que vão ser feitas aqui, não quero por muitos mapas para não só ficarem revesando entre os níveis fáceis.

**ze_evernight_a3_4** | De | Para
--- | --- | ---
*Level 1* | ~~20~~ | **80**
*Level 2* | ~~40~~ | **160**
*Level 3* | ~~80~~ | **400**

**ze_halloween_house_b4** | De | Para
--- | --- | ---
*Level 1* | ~~80~~ | **240**

**ze_Kitchen_v2** | De | Para
--- | --- | ---
*Level 1* | ~~40~~ | **80**
*Level 2* | ~~60~~ | **200**
*Level 3* | ~~100~~ | **1000**

**Comment by alminha021** [comment]
Se puder desativar o death points deles, melhor

**Comment by lucaslinha** [comment]
da uma atenção pra mapa não zerado tmb.

**Comment by hcjordao** [comment]
Deixei kitchen como não zerado, mas posso mudar. Dar um bonus de pontuação a mais para mapa não zerado, o que acham?

**Comment by hcjordao** [comment]
Sobre os death points esses mapas não possuem ai nem precisei remover @alminha021, mas em caso de mapa que tenha eu removo

**Comment by alminha021** [comment]
sim, custa nada nao zerados valerem mais pontos

**Comment by gabrielacms** [comment]
O kitchen não foi zerado msm. E sim, mapa não zerado pode possuir bônus. 
Se eu não me engano, death points tá ativo só em mapa muito jogado (666, pirates, entre outros)
Esses mapas que vão receber esse buff temporário de pontos, vamos anunciar no discord?

**Comment by hcjordao** [comment]
O que eu fiz foi pegar as estrelas no discord definidas pelo @lucaslinha subtrair um e multiplicar os pontos atuais. Para o ultimo level eu multiplico pelo numero real de estrelas. Posso add um bonus bem maior por mapas não zerados

**Comment by hcjordao** [comment]
Fiz um update na pontuação veja o que acham

**Comment by gabrielacms** [comment]
Entendi mas assim, acho que temos que levar em consideração a dificuldade real de cada level. O level 1° do kitchen não é tão difícil assim e pode se tornar com certeza um farm de pontos.

**Comment by hcjordao** [comment]
Eu só fiz isso para ter um exemplo. Mas a ideia é eu postar aqui os mapas da semana ou quem quiser abrir primeiro, e todos validarmos e inserir ajustes com o que você mesmo disse @gabrielacms  com a dificuldade real do mapa

**Comment by alminha021** [comment]
ja que eh manual mesmo, a gente que joga e sente a dificuldade podemos arrumar isso ai, realmente tem mapa que eh dificil mas tem leveis que sao batatas , da pra ir arrumando e evitar farm e tals.
lvl 1 do kitchen eh facil demais, um buffzinho de leve pra incentivarem pelo menos a jogarem
lvl 2 eh ok, mas precisa de call, da um buff legal pra incentivar tbm a tentarem
lvl 3 eh hard as f*ck , da um buffao nele + buff de nao zerado

**Comment by alminha021** [comment]
evernight eu so joguei com call , e nao achei dificil, mas precisa que o pessoal escute a call pra nao morrer de bobeira no mesmo lugar , entao da pra deixar os buff etc

halloween ta ok , eh hard ja que o time vai morrendo aos poucos

**Comment by hcjordao** [comment]
update com as sugestões do @alminha021 **bufão**

**Comment by gabrielacms** [comment]
Só uma sugestão mesmo, dai vcs veem ai se vale a pena ou não..
Definir em todos esses mapas aquela de quantidade mínima de jogadores para esses serem nominados. Os 3 mapas estão com 25 jogadores. Colocar uns 30 ou 35. Como darão muitos pontos, acho importante garantir que mais pessoas terão a chance de ganhar também. Isso é mais para evitar alguma coisa, principalmente de madrugada. 
Ou se tiver como ser feito, algum plugin parecido com aquele que ativava a confg batata e tryhard. Uma maneira de ativar e desativar esse buff. Desativava esse buff durante a madrugada e no período da manhã (já que mesmo colocando quantidade mínima é possível o mapa vir na votação)

**Comment by alminha021** [comment]
Acho que 30 ta de bom tamanho, todo dia ta praticamente batendo esse numero, quanto a desligar de noite ou de manha sou indiferente , gosto da ideia de que o server lote pela manah e de madrugada tbm, nao sou tarde/noite , mas sei que pode rolar farm. Ideal mesmo eh que ele nao apareça nas votações sem ninguém nomeá-lo se der pra fazer isso melhor.. e de preferencia ja setar o numero de player pra poderem nomear pra 30 (ou 25 ou 35 dependendo de quanto vai ficar) pra evitar o famoso "vamo testar o mapa com 15 nego" ai qnd tem gente ele ta no CD.

**Comment by hcjordao** [comment]
Muito dificil rodar farm em mapas com 25 players, mas caso o mapa tenha menos que 25 acho justo refazer caso precise.

**Comment by hcjordao** [comment]
Já irei fazer o post dos Weekly Maps, se quiserem alguma alteração antes do post fale agora
