### ISSUE TITLE
diminuir pontuação de alguns mapas overplayed

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#65]
**ze_surf_shonyudo_v1 - 40 pontos 
ze_surf_outside_b1_10 - 45 pontos
ze_surf_froyo_lite_v2_3 - 60 pontos**
É até assustador ver essa pontuação no Froyo. Enfim, saber surfar não é um requisito do zombie escape, muitas pessoas do servidor não sabem. Acho que a pontuação de qualquer mapa de surf,  tem que ser a mesma ou no mesmo patamar Eu acho que 20 pontos (para os mais difíceis) e 10 para os bem fáceis. 
**ze_star_wars_lvl1**
Atualmente valendo 50 pontos. Esse mapa é muito fácil, acho que 20 pontos é suficiente. Apesar de ter boss, o mesmo foca só uma pessoa até ela morrer. Acaba sendo muito fácil zerar. 
**ze_alien_shooter_v7_ps4**
Atualmente valendo 40 pontos. Está classificado com 2 estrelas, comparando o mesmo com outros mapas da mesma classificação, está dando bastante pontos. 
**LOTR**
Talvez nem precise nerfar os pontos mas acho válido adicionar um death points. Uns 2 pontos de death points. 
**ze_naruto_p**
Mapa repetitivo, chato e fácil. Sugestão de pontos: 
lvl1 - 10 pontos
lvl2 - 10 pontos
lvl3 - 20 pontos
lvl4 - 30 pontos ou 40 já que é o lvl do boss. 

Digam ai o que acham ou se tiver mais algum mapa fácil sendo muito jogado e dando uma quantidade boa de pontos, coloca ai tb.

**Comment by alminha021** [comment]
Comentei desse froyo ai a umas semanas, eh tenso mesmo.
Por mim ok.

Depois deem olhada nos pontos que nao sei onde ta, mas to zerando todo dias esses mapas aqui, ta na hora de subir o death points neles, pq acredito que os pts ja estão baixos, senão estão eles devem ser os mapas que menos tenham pts para dar:
 - ze_alien_shooter_v7_ps4
 - ze_surf_gypt_v1_3_1f
- ze_titanic_escape_v2_3_p
- ze_aepp_nano_grid2_v1
- ze_portal_story_v1_2
- ze_biohazard2_rpd_004_p3
- ze_death_star_escape_v4_3_p2
- ze_JurassicPark_Escape_p2 (nem parece que tem CD , jogam todo dia)
- todos os lotr(tirando o tirith e isengard)


Apesar de serem mapas que gosto pq lotam , eles são extremamente fáceis de farmar , dificilmente vc perde. 
O que desejo eh que eles joguem mapas novos mas que sejam fáceis tbm, aprendam a call e tornem eles extremamente fáceis, pq esses tao saturando já.

**Comment by lucaslinha** [comment]
Eu tinha ctz de que tinha nerfado alguns desses a um tempo, talvez me enganei e nem cheguei a commitar, prox commit eu vou nerfar com ctz.

**Comment by hcjordao** [comment]
Acho que seria bom termos um review semanal sobre mapas e pontuação ai já podemos reduzir e discutir on the flight :), se viu um mapa que precisa ser ajustado já abre um issue aqui

**Comment by alminha021** [comment]
- ze_greencity_fix (mapa bem facil, nao vi quanto de ponto esta dando, mas pediram pra nerfar de tao facil que eh)
*
- ze_roof_adventure_v7_2
- ze_sky_athletic_adv_v9_12
Esses 2 sao casos de que pra mim viraram mapas de farm, Cada level do sky athletic eh 20 pts , e os primeiros sao ridiculos, mapas semelhantes em dificuldade dao 5pts , pelo menos os 2 primeiro devem dar menos pontos, uns 10 ta de bom tamanho(eh pra ser 5) , 20 acho exagerado ja.

Rooftop ja foi um mapa que sofriamos, hj eh izi farm , foi zerado apenas 2 vezes, porem os levei iniciais estao dando em torno de 40 pontos , e adificuldade do mapa so vem apos o level do laser e complica apos o level do surf
mapa de 8 leveis, sugestao:
lvl 1 - 10pts (boss batatao)
lvl 2 - 10pts (minigame corrida) //muito dificil perderem
lvl 3 - 20pts (boss roroso com ataques batatas)
lvl 4 -20 pts (laser) // so 1 ganha 99% ja que eh corrida , entao 10 pts tambem eh de boa
lvl 5 - 30 (boss +-)
lvl 6 - 30 (surf) // ja foi dificil, hj eh facil , geralmente 4 ou 5 passam
lvl 7 - 60 (boss ok)  
lvl 8 - 60 (ainda nao pegaram o jeito, mas eh patetico esse lvl) // 2 solos pq sao apressados

**Comment by lucaslinha** [comment]
Nerfei ze_alien_shooter_v7_ps4/ze_greencity_fix/ze_naruto_p/ze_roof_adventure_v7_2/ze_sky_athletic_adv_v9_12/ze_star_wars_lvl1/ze_surf_froyo_lite_v2_3/ze_surf_outside_b1_10/ze_surf_shonyudo_v1

**Comment by alminha021** [comment]
ze_Rooftop_Runaway_Extended"
40 pontos , super facil
colcoa 10

**Comment by hcjordao** [comment]
Caso necessário abrir issue novamente. Fiz a att no repo do mapa mencionado @alminha021 deve demorar uns diazinhos para entrar. Irei fechar o issue.
