### ISSUE TITLE
Bugs - ze_FFXIV_Wanderers_Palace_v5_2 

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#66]
- [ ]  Garuda não morreu na nuke do level 2

**Comment by lucaslinha** [comment]
Problema é onde ele estava ? Precisou dar slay ? Ele estava afetado por alguma coisa ? tem que detalhar bem para achar uma solução.

**Comment by hcjordao** [comment]
Eu só add o que estava no report de um player para ser investigado.

**Comment by alminha021** [comment]
ta , o garuda era eu, estavamos testando o mapa.
por algum motivo eu nao morri na nuke, a porta fechou e eu estava pra fora, tive q me dar slay.
no evento os garuda morreram, entao nao faço ideia do que era, e acredito que nao estava sobre efeito de nada, a nao ser que tenham me dado god , mas so estava eu e a gabi la, e nao vi em nenhum momento o god ser dado a mim

**Comment by hcjordao** [comment]
Qual level foi isso? Posso forçar o slay do item do zm no round end do mapa.

**Comment by hcjordao** [comment]
@alminha021 sabe me dizer?

**Comment by hcjordao** [comment]
Vou fechar esse issue devido falta de info sobre o mesmo. Caso o bug esteja ainda ocorrendo abrir de novo please.
