### ISSUE TITLE
Bug - ze_star_wars_lvl1

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#67]
- [ ] Item de jedi buga e deixa CT imortal. (Remover via stripper)

**Comment by quasemago** [comment]
Isso é causado pelo plugin do entWatch que tenta bloquear o pickup da materia, porém nesse caso como é uma faca acaba bugando o jogador.

Visto que a proteção contra faca não funciona, editei o plugin para ignorar as restrições quando é uma faca.
