### ISSUE TITLE
Cfg ranking ze_FFXIV_Wanderers_Palace_v5_2 com problema no Ending

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#68]
Config atual utiliza determinadas entidades para detectar o final do level, mas como foi observado durante o tryhard recente não está sendo detectado o mesmo.

Como consequência os humanos não estão recebendo os pontos, além de não gerar os logs de vitórias.

**Comment by lucaslinha** [comment]
Trocado para timer, esperar que funcione. Agora pq o top defender não funcionava, não faz sentido k

**Comment by quasemago** [comment]
@lucaslinha Faz sentido, pois o top defender necessita que os jogados tenham chegado ao fim do mapa, mesmo em caso de derrota.
