### ISSUE TITLE
Weekly Maps Sugestões/Melhorias

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#69]
Melhorias para o Weekly Maps:

- [ ]  Buff de top defender e tempo dentro desses mapas. Através da config de mapas para facilitar.
- [ ] Ter um nome ao lado do mapa no nominate (Weekly Maps!) para chamar atenção assim como ( New )
- [ ] Seria interessante ter algo no HUD do colega para ele saber que o mapa está bufado no jogo.

**Comment by gabrielacms** [comment]
No caso do weekly, como teremos certeza dos mapas que serão válidos e como ficará ativo por 1 semana, podia ter um comando dentro do jogo. Digitar !weekly ou algo do tipo e ter um menu mostrando os mapas disponíveis da semana. O infused tinha sugerido um menu desse tipo para o evento de domingo mas acho que para o weekly maps ficaria melhor, já que os mapas de domingo são escolhidos 2 dias antes do evento

**Comment by hcjordao** [comment]
Acho que não deu nem um pouco certo a iniciativa! Não sei se precisa de mais promoção e/ou ajustes. Eu irei fazer mais uma semana, ver o que rola e qualquer coisa abort.

**Comment by gabrielacms** [comment]
é o que a gnt já tinha comentado anteriormente.. pessoal só quer jogar aquilo que sabem passar. Aumentar os pontos é um incentivo mas eles não possuem interesse nenhum em conhecer alguns mapas. Só querem jogar mapa fácil ou se tiver call, se não tiver, não querem nem tentar conhecer. Enfim, tenta mais uma semana, se não rolar, pensamos em outra coisa.

**Comment by lucaslinha** [comment]
Como eu disse unica chance disso dar certo é deixar os mapas faceis que eles jogam todo dia inuteis e os dificeis obrigatorios e mesmo assim é capaz de não dar certo tambem ja que são um bando de desinteressado que gosta apenas da sua zona de conforto. Basta apenas olhar o chatlog, qualquer mapa com dificuldade mediana, não to nem falando dificil, ja tão pedindo rtv.

**Comment by alminha021** [comment]
Ta na hora de mudar mais entao, 
- opçao com mapa aleatorio na votaçao , 
- fazer os caras gastarem pontos pra nomear etc..
- Ou faz uma opçao la na votaçao "mapas da semana"
ai se ganhar colocava algum mapa aleatorio dentre os quee a gente escolheu como mapa da semana

**Comment by lucaslinha** [comment]
O publico do server respira por aparelhos com aquele matsu e aquele lord eau se interessando em novos mapas para jogar, pq de resto ...

**Comment by hcjordao** [comment]
Como funciona aquela cfg de new maps, consigo montar uma nova com outro nome?

**Comment by alminha021** [comment]
por mim a votaçao seria assim
1 - mapa aleatorio
2 - mapa da semana
3 - mapas nao zerados ou 3 - palyer nominate
4 a 8 - player nominate
nao vejo a opçao "sem voto" ser util.
de preferencia gastando 40 pontos pra nomear.

**Comment by gabrielacms** [comment]
@lucaslinha rolou isso no harry potter agorinha, colocaram o mapa e a maioria do pessoal estava baixando ainda, o warmup do mapa mal tinha acabado e já estavam dando rtv. 

- Mapa aleatório seria legal ter opção 
- Eu sei que poucas pessoas sabem o que é de fato o DeathPoints. Talvez se mostrasse em todo mapa que possui essa configuração, uma mensagem "O deathpoints está ativo nesse mapa" no hint. E ativar essa "punição" em todos os mapas overplayed. 
- Acho que já sugeri isso umas 3x mas uma hora vai, por mim podia usar aquele lance de remover o nominate durante 1 dia da semana. Ninguém consegue nominar mapa. Apesar de ser só 1 dia, pelo menos iria forçar eles a jogarem mapas aleatórios e consequentemente conhecer outros mapas. 
- Voltar a mutar todo mundo durante a votação?!

**Comment by alminha021** [comment]
"Voltar a mutar todo mundo durante a votação?!"
fiz essa sugestao ontem la no ds, ta tenso , aparece um mapa novo na votaçao eu ja escuto
"bora jogar esse nao, nao vai passar, bora um lord of the rings"
"Vota 4  ai, laser island , 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 "
" vota 5 nao que nao vai apssar, vota 4 4 4 4 4 4 4 4 4 4 4 4 4 44 "
MUTA TUDO AI ADEMIR

**Comment by lucaslinha** [comment]
@gabrielacms Sim essa é a cultura instalada la, se eles não querem jogar normalmente, não são pontos a mais que vai mudar isso, ou você de fato obriga eles a jogarem ou não vão jogar. Tipo essa ideia de um dia sem nominate seria daora mas tipo teria que ser so os mapas medianos pra cima e aquelas besteiras que eles jogam todo dia de fora.

**Comment by hcjordao** [comment]
O problema de random maps é que se cair um diddle com 10 pessoas no server tem risco so servidor ficar vazio uma boa parte do tempo até mudar.

Sobre o mute na votação não vejo problemas tbm.

Acho interessante mudar o layout da votação. @quasemago se desse para separar o layout da votação por módulos seria interessante: Random, Module, Players Maps

- 1 -> Random Map (Seria interessante o random map filtrar os mapas em que o numero atual de jogadores nao passe o )
- 2 - 3 -> Algum modulo que o povo queira inserir exemplo weekly maps, new maps, buffed maps, themed event maps.
- 4 - 9 -> Mapas da gurizada

**Comment by lucaslinha** [comment]
essa ideia de separar poderia ser boa, eeeeentretanto tem a possibilidade de ser um tiro no pé para justamente o que voces querem, que é fazer os jogadores jogar mapas poucos jogados, conhecendo bem a cabeça deles, eles vão passar longe de uma determinada seção por ser "dificil" demais.

**Comment by hcjordao** [comment]
É não deu muito certo isso aqui e mesmo que eu faça de novo não vejo dando muito certo. A não ser que faça todo um sisteminha que avise quais mapas estão no Weekly e que isso seja frequentemente avisado ao jogador da existencia deles e tal. Como não é prioridade no momento e não vejo dando certo irei fechar o issue. Mas thanks for the test, já sabemos agora.
