### ISSUE TITLE
2 skins de humano invisiveis no ze_castlevania_p1_7

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#7]
Belmont e Alucard invisiveis quando o ct picka.

**Comment by quasemago** [comment]
Resultante de um update da valve, irei depois testar um hotfix: https://github.com/Mapeadores/Plugins/blob/master/src/dzspriterendermode_fix.sp

**Comment by hcjordao** [comment]
Fix incoming when? Melhor remover os mapas desse issue e do #8 do nominate ate o fix vir?

**Comment by lucaslinha** [comment]
To comitando na minha branch o fix, em breve sai.

**Comment by hcjordao** [comment]
Mapa removido do nominate até fix.

**Comment by hcjordao** [comment]
Mapa foi adicionado no nominate e aparentemente fixado. Da proxima vez @lucaslinha faça um comentario pra fechar o issue 😪. Issue fechado.
