### ISSUE TITLE
Problemas no sm @all 

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#70]
Isso é um problema muito antigo relatado por varios players e eu não lembro de nenhum fix por parte disso sendo feito, a não ser que não tenha sido relatado. Pelo que algumas pessoas falaram, no 1 round funciona de boa, mas a partir do new round ja começa a zoar tudo, ele muta ate administração e você precisa dar !su a cada novo round tmb.

**Comment by hcjordao** [comment]
Como funciona a adicao dos usuarios no sm @quasemago ?

**Comment by quasemago** [comment]
Estamos usando a versão do antiteal, mas irei testar outra antes de pensar em fazer um rework do plugin.

**Comment by quasemago** [comment]
Está sendo testado uma nova versão, que em um rápido teste que realizei com outros jogadores parece estar funcionando corretamente.

**Comment by quasemago** [comment]
Nova versão funcionando perfeitamente. Além do problema do **@all** ser sanado, os mutes do round anteriores continuam diferente da versão anterior que resetava.
