### ISSUE TITLE
Bug - ze_doorhug_and_solo_v5_2_csgo

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#72]
- Não dá para atirar no ZM no spawn. 
Eu nunca joguei até o fim desse mapa mas me lembro que no começo tinha que segurar o zm no spawn até liberar o caminho. Depois que deram o report, eu entrei no servidor e realmente  o zm não estava tomando kb no spawn, ele só toma dano de he/molotov. 
- Vários props do mapa estavam invisíveis. 

Estava vendo e esse mapa entrou no nominate dia 07/06 e até então não tinha tido esse tipo de report. Acho que teria que jogar ele de novo para ver se ocorre o mesmo problema. Dai reportem aqui se o problema se repetir ou se o mapa rodar de boa.

**Comment by hcjordao** [comment]
Se eu não me engano tem uma parede que filtra o dano no spawn, a ideia do mapa é o zm tirando a galinha ter pouca vida e tu conseguir matar os zms facilmente. Ai um dos 4 spawns do mapa é contaminado por zumbi e é a vida, é assim mesmo. Só tem que ajustar os settings do Zumbi para ele parar de dar regen de vida tao rapido

**Comment by hcjordao** [comment]
Potencialmente fixado, fiz alteração via stripper do spawn coco do doorhug, vejam se não ta broken para humano.

https://github.com/quasemago/zrageconfigs/pull/71

**Comment by hcjordao** [comment]
Visto que não houve mais reclamações por mais de 25 dias irei fechar o issue se isso ainda estiver ocorrendo reabrir por favor.
