### ISSUE TITLE
Auto retry.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#73]
Não tenho ideia se é simples fazer, mas ele da uma mão imensa pra quem é novo e não tem ideia de como se digita um simples comando no chat, sem contar que diminui trabalho da administração também.

Basicamente é o que o nome diz, quando vc entra no mapa, 1 seg apos, você recebe um retry automatico evitando assim precisar recarregar mapas ou jogadores digitarem comandos para poder ver particulas.

**Comment by gabrielacms** [comment]
Seria uma boa, ajudaria muito no dia-a-dia e nos eventos também. 
Tem esse plugin aqui que a descrição dele é exatamente essa ai > forçar o retry para verem as partículas. Mas não sei se funciona. 
https://forums.alliedmods.net/showpost.php?p=2642315&postcount=4

**Comment by quasemago** [comment]
Ponto negativo desse plugin citado pela @gabrielacms é que até quem já tem o mapa vai ser forçado com um retry.

Creio que seja possível verificar se o jogador possui ou não o mapa durante a entrada numa forward mais cedo (antes mesmo dele entrar in-game). Irei dar uma olhada nisso mais tarde.

**Comment by alminha021** [comment]
o load apos vc ja ter entrado eh sempre 100x mais rapido que o primeiro
da pra testar.

**Comment by lucaslinha** [comment]
Sim como o alma falou, o 2 load é bem mais rapido em relação ao primeiro, então não seria um incomodo tão grande assim.

**Comment by hcjordao** [comment]
É entao unico ponto negativo é que ocorreria para todos os jogadores. Unica forma de saber se o cara jogou um mapa ou nao é manter uma flag do mapa com o jogador, e ai force restart se necessário. 

O que da pra fazer é um input do ademir online para abrir um menu para todos os jogadores no server falando que o jogo dele será reiniciado automaticamente explicando o motivo do retry e em 15 segundos. O cara tem a opção de aceitar (reinicia na hora), desativar (fecha o menu e nao da retry), e esperar ( o cara tava away do server ai reinicia de qualquer forma)

**Comment by hcjordao** [comment]
É entao unico ponto negativo é que ocorreria para todos os jogadores. Unica forma de saber se o cara jogou um mapa ou nao é manter uma flag do mapa com o jogador, e ai force restart se necessário. 

Uma outra sugestão: O que da pra fazer é um input do ademir online para abrir um menu para todos os jogadores no server falando que o jogo dele será reiniciado automaticamente explicando o motivo do retry e em 15 segundos. O cara tem a opção de aceitar (reinicia na hora), desativar (fecha o menu e nao da retry), e esperar ( o cara tava away do server ai reinicia de qualquer forma)

**Comment by lucaslinha** [comment]
Nah o objetivo disso é facilitar a vida da administração e não dificultar, junto com os jogadores tambem, mapas de particula não rola apenas quando tem adm online não.

**Comment by gabrielacms** [comment]
Eu estava vasculhando algumas coisas aqui e achei um outro plugin de retry. Esse aqui aparentemente é mais bem feito e completo do que esse outro que enviei. 
https://github.com/darkerz7/CSGO-Plugins/tree/master/Auto_Retry

Esse ai possui database. Segundo o autor, ele vai verificar se o cara já jogou o mapa (pelo DB) e se não tiver jogado, vai forçar o retry. Mas antes de forçar, o usuário vai receber uma mensagem de que baixou mapa novo e que vai dar retry dps de X segundos. 
Esse ai tb possui comando para resetar o database. -> sm_retryclear

**Comment by lucaslinha** [comment]
Nice so falta saber quando agr.

**Comment by quasemago** [comment]
Primeiro terei que modificar o plugin citado pela @gabrielacms visto que ele não utiliza query via thread (o ideal).

**Comment by quasemago** [comment]
Está sem teste uma versão que verifica se o jogador já jogou ao mapa ou não (informação salva em nosso banco de dados). 

Infelizmente não consegui achar uma maneira de verificar se o jogador possui o arquivo, e quanto a verificar se ele acabou de baixar não é possível se utilizado FastDL (https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/engine/download.cpp#L516), esse método só funciona nos downloads tradicionais usando netchannel (https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/src_main/engine/net_chan.cpp#L306).

**Comment by lucaslinha** [comment]
Tira o delay e as mensagens, so confunde quem ja tem o mapa baixado e toma auto retry, deixa o minimo possivel que eu acho que é 1 segundo, como o alma ja falou antes, o 2 loading é bem mais rapido.

**Comment by alminha021** [comment]
Como comentei:
 - O segundo loading eh muito rapido
 - Batatas nao sabem o que é materia/ particula, entao o ideal eh que eles nem percebam o autoretry para nao fazerem perguntas
- com 5 segundo , eu entrei , escolhi time, andei , abri o console, e tava terminando de escrever um comando, eh MUITO TEMPO
- Para veterano, quanto mais rápido entrar e reconectar = MELHOR
- certeza que pode acabar bugando os mapa
- se o cara entra perto da infecçao e vira o unici mother , se ele tomar autoretry acaba o round.

Conclusao:
 - Coloca 1 segundo ai, o mais rápido eh melhor, eh um plugin que nao precisa ficar informando a galera, veterano quer jogar logo, e novato sabe nem o que eh materia, se for rapido eles nem sentem.

**Comment by quasemago** [comment]
Já ajustei para 1 segundo sem mensagem.

**Comment by quasemago** [comment]
Tudo funcionando perfeitamente, issue encerrado!
