### ISSUE TITLE
TTT - Blacklist DTT não mostra o admin que colocou

### ISSUE THREAD

**Issue by lhsatsuma** [quasemago/zrageservers#74]
Ao colocar um jogador na BlackList de DTT, ele até aparece o admin que colocou. Mas ao desconectar e conectar ele some e fica como "Desconhecido".
Pelo visto, está pegando o ID da sessão atual.

![image](https://user-images.githubusercontent.com/44283104/74611977-a686c280-50df-11ea-9323-6e4edc902b0f.png)

![image](https://user-images.githubusercontent.com/44283104/74611989-ba322900-50df-11ea-9122-991088a0856d.png)

**Comment by hcjordao** [comment]
Nao deve estar salvando na cfg. o ID do ademir, so ta salvando o nome. Tem que fazer um update no modulo de blacklist

**Comment by quasemago** [comment]
Era apenas um "typo" na leitura do cookie que salva o steamid do admin. Também reformulei para mostrar apenas o SteamId do admin visto que o mesmo pode trocar o nick a qualquer momento.

**Comment by quasemago** [comment]
Blacklist foi atualizada e agora também salva o "motivo". Sistema de storage foi alterado de clientprefs (sqlite) para MySQL.
