### ISSUE TITLE
Volta do batata mode.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#77]
Como eu ja tinha conversado com o @hcjordao , eu pedi a volta o batata mode, situação do sv é tão triste em que não conseguem passar um simples por_island, sem contar os bullying de boludo falando que brasileiro não passa nem um simples mapa.  

Basicamente as mudanças são inicialmente para testes, mas eu ja testei uma parte disso no server e não ficou tão mal.

- Obviamente a cfg atual vai ser a tryhard 
- A ordem de listagem de armas do !guns precisa ser alterada (armas que exigem um minimo de qi para ser usadas não devem ficar na 1 pagina e sim nas ultimas e as mais faceis de se usar na 1.) 
- ratio 1/8 
- staminarecovery 60 / tagging 1 
- Mother 310 / Son 305 vel. 
- Munição subs 100. 
- aumentar a vida dos cts para uns 125/150, mas so terá efeito em alguns poucos mapas.

**Comment by gabrielacms** [comment]
Posso estar falando merda mas eu acho que o servidor já está na config batata antiga, não? Me lembro que tínhamos combinado de que ela iria ficar 24/7 no sv. Mas talvez não nessas configs que você acabou de passar.

**Comment by alminha021** [comment]
acho que ja ta tambem na config batata ativa.
Acho que ate ja esta muito facil de jogar.
Quando o time quer obviamente passa os mapas.
Por isso tao especialista em laser island , minecraft adventure , portal story , se colocar todo dias , vai ter os mesmos caras jogando e levando o time pra vitoria.
Agora mapa que nao jogam, tenho certeza que jogam sem vontade e pedindo rtv, eu mesmo nao gosto de jogar serio qnd nao eh evento ou mapa hard, so fico observando e ajudando as vezes e tryhardando de zm always.

Nao vejo problema na config, problema ainda eh a falta de vontade de jogar outros mapas.

boludo nem conta , jogam de smoke e um kb todo zoado, se colocar ff eles passam ja que sempre jogam , ate pq a maioria dos mother sao tudo batata que nao fazem nem questao de ganhar, agora coloca um mapa fora do escopo deles, eh triste tbm. Tanto eh que vao jogar de evento shroom forest, 2 mapa que vc faz 6 - 0 e um que nem precisa de good ending.

**Comment by kobe-hcjordao** [comment]
A proposta do infused é tornar a config atual a nova tryhard e fazer uma nova config batata.

Eu sinceramente não me importo de modificar, server já está bem casual e infelizmente that's the way to go. Sobre as configs que o infused sugeriu acho as mais pertinenentes seriam:

- Infecção 1/8,
- Alterar a ordem das armas no guns -> SMGs ocupando toda a lista inicial

Talvez redução do preço de rebuy para as armas.

**Comment by gabrielacms** [comment]
Huum entendi, acabei lendo rápido e não prestei atenção nesse detalhe. Bom de fato tem vários mapas fáceis ai que estão apanhando bastante para passar. Por mim tudo bem. Antes eu ficava meio puta quando se discutia sobre diminuir a dificuldade do servidor mas agora eu não me importo muito. O pessoal conseguindo jogar é o que importa.

- de acordo com colocar smg na 1 pag
- de acordo com a diminuição do preço. Mas principalmente da negev. Mesmo defendendo,dependendo das quantidade de coisa que você compra, o preço da negev ferra um pouco.

**Comment by lucaslinha** [comment]
A config atual não é de maneira alguma batata, como ja disse antes, as granadas serão op no momento que usarem elas, o povo que joga la so saber andar e apertar o botão esquerdo do mouse, logo deixar o hold e o retreat mais facil deixa a cfg mais facil.

**Comment by alminha021** [comment]
Acho que o jogo nunca esteve tão facil, sinceramente a parte mais dificil de jogar nas ultimas semanas foi o lag do tirith , de resto foi tudo muito facil, todos eventos e tryhard , teve evento que zerei de faca, eso atirei no ultimo hold, teve tryhard q joguei de usp e tava facil.

se os caras nao estao passando um mapa eh por falta de call e vontade mesmo. infecçao 1 pra 8? na pratica eh mais ou menos assim que funciona, de 6 que vira uns 2 quita.

Enfim sou contra tudo, menos a smg na primeira pagina, isso seria interessante. Fora isso , sempre tenho a opçao de jogar de usp e ficar away de mother, ja que ninguem eh obrigado a jogar com um zm todo aleijado. 
Se forem pra deixar facil , eh so colocar o bhop vanilla , ja que eh uma parada que nao faz diferença pra ct e bem op pros zm que morrem de ct e vem pular de zm.

**Comment by kobe-hcjordao** [comment]
Levar em consideração tryhard como base é errado, o certo seria considerar um dia qualquer como seu ponto de referencia

**Comment by kobe-hcjordao** [comment]
Tryhard tem os caras que sabem jogar ja e defendem por 5-6. Ai fica bem mais facil. Alem do que os caras conhecem o mapa ai dependendo do mapa fica muito favoravel para o CT

**Comment by lucaslinha** [comment]
desconsidere tudo sobre rebuy e granada, nada disso é utilizado por essa galera.

**Comment by alminha021** [comment]
de base a gente tem ai os emsmo mapas sendo jogado , como ja falei 2x , problema eh mapa q os caras que dao call nao querem dar call e jogam sem vontade pedindo rtv.
cansado de zera laser island, minecraft, rpd , crazyescape, portalstory,minastiret , lotmount domm, lotd nao sei o que , greencity, naruto Todo santo dia.
Enfim, podem fazer o que quiserem, por mim ta ok do jeito que ta, mas se 10 cara ruim conseguem baixar o nivel, ok, melhor que nao perco meu tempo e esforço tentando ganhar.

**Comment by gabrielacms** [comment]
Eu penso isso tb. Se voce conseguir zerar Rush B só de faca no dia-a-dia, dai sim faria sentido não alterar. Levar em consideração uma gameplay em dias que o pessoal está tryhardando para decidir algo que vai afetar a jogabilidade durante a semana é errado. 
@lucaslinha em quais mapas, por exemplo, essa alteração de vida iria acontecer? Acho que só nisso ai que não estou tão de acordo.

**Comment by alminha021** [comment]
jogamos rush b na semana seguinte ao evento, chegou no final 10x mais rapido que no tryhard. so perdemos no hold final. Como falei, depois que jogaram uma vez fica muito mais facil, mapa que nao jogam tem q morrer no respawn tbm.

**Comment by kobe-hcjordao** [comment]
Acho que eu ja mencionei antes, mas eu ja passei da fase onde a gameplay tem que ser dificil para passar. Como qualquer jogo tu joga primeiro no modo facil depois da unlock no médio, depois no hard e por fim no ultimate.

Me deu uma ideia de cfg dinamica dependendo do numero de vezes que o mapa foi zerado na ultima semana. Ao inves de setar todos os mapas, as cfgs são incrementais de acordo com essa porcentagem. Foi jogado 100% de win rate no mapa numero de vezes de mapa jogado 30 vezes na ultima duas semanas. -> Força o uma cfg tryhard. 0% de win rate 0 vezes o mapa jogado buff enorme de pontos e cfg batata e por assim vai indo. 25% de winrate 10 vezes o mapa jogado Buff leve de pontos e cfg normal.

**Comment by kobe-hcjordao** [comment]
Convencer o @quasemago a fazer isso agora. kekeke

**Comment by kobe-hcjordao** [comment]
Agora convencer o @quasemago a fazer isso kekeke outros 500

**Comment by lucaslinha** [comment]
@gabrielacms principalmente mapas com npc e traps com dano. 
Bom comecei com essa ideia pq essa cfg atual não é verdadeiramente batata, os recursos dela são voltados pra isso, mas não adianta no momento que esses recursos não são usados.

**Comment by alminha021** [comment]
Acho que todo mundo ja passou da fase de jogar no hard, tanto eh que a config ativa eh a batata hj, tanto na semana qnt nos eventos.
Se querem deixar facil o que esta ja esta facil, tem que fazer os caras que dao call começarem a dar call em outros mapas entao, mudar config so ta desmerecendo o teamplay , e facilitando 1 cara carregar 20 nas costas, qnd esse 1 cara nao estiver, vai vltar a ser a emsma coisa.
"a mas nos tryhard e ventos a config vai ser mais tryhard q a da semana" quando colocaram config batata e tryhard no server, vieram com essa tbm, nao deu 1 semana e os eventos/tryhard ja estavam com config batata tbm. Entao nao acredito que isso sera so para alguns mapas , nao dou 1 ems pra ta todos os mapas com a config proposta.

Enfim , pra facilitar sem destruir o templay , o que ach q pode ser feito.
 - libera o !lider pra geral com um minimo de tempo no server definido.
 - o lider recebe uma bonificaçao extra buffada de pontos ( pontos bons pro cara ter vontade de ser lider)
 - a pessoa que nomeou o mapa tem prioridade em ser o lider caso ocorra confusao de muitos quererem ser lider , caso nao tenham nomeado , o primeiro a pedir tem prioridade, ou antes da infecçao começar eles digita !lider e o lider eh sorteado dentre os que escreveram.
- assim como ocorre com o eban , a staff tem um comando pra colocar na blacklist por um bom tempo, 1 mes, 2 semans etc , porem agora com debitaçao de pontos , perdeer uns +500 pontos caso o cara pegue o lider pra bagunçar ou farmar com amigos.
- desabilita a ajuda nesse bhop, como falei , so ajuda zm. O que um cara faz de ct bunnando vc pode fazer andando.

Enfim, nao ligo para o que decidirem, vou jogar menos mesmo, so deixei minha opniao.

**Comment by alminha021** [comment]
e nao esqueçam que jogar de zm eh um lixo atualmente, colcoando menos zm e mais ct atirando em vc so vai aumentar o numero de quit por parte dos zm, ninguem gosta de ficar preso nos canto tomando bala, e pegando fogo a cada 3 segundos, brasileiro gosta eh de beijar a porta sem fazer nada e andar pelo mapa conversando.
Se querem facilitar tanto assim, pelo menos achem um equilibrio ai:
zm devagar + cts buffados com mais balas = mais zm iniciais.

Pq pra mim esta totalmente desbalanceado tanto buff em ct e nerf em zm e reduzir mais ainda o numero de zm

**Comment by lucaslinha** [comment]
Bom adianta nada falar sem ver na pratica, por isso solicitei um teste, nem que seja pelo menos 1 dia, concorda em fazer isso @hcjordao ?

**Comment by hcjordao** [comment]
Eu to esperando entrarem em um mid ground para realizar os testes. Concordo com o que o alma falou periodo de teste vai virar permanente. Então acho que antes de querer inserir qualquer coisa. Todos os admins tenham que ter um mid ground para definirmos ok isso aqui ta bom o suficiente para levarmos pelo server.

**Comment by lucaslinha** [comment]
Permanente ? So se você quiser ne ? não entendo qual a dificuldade de mudar alguns arquivos por um dia e dar revert no outro. Entendo que o tempo pra quem cuida do server hoje em dia é pouco, mas não acho que tirar 5/10 min pra fazer isso va matar alguem.

**Comment by hcjordao** [comment]
Nao tem dificuldade nenhuma eu só quero deixar bem alinhado para depois as reclamações de mudanças sejam menores só isso e que todos estejam cientes. É bem mais facil deixar como está do que reverter só isso. Mas se ngm tiver mais nada a adicionar eu faço as mudanças. Vou adicionar no repositório também os arquivos de batata e tryhard.

**Comment by quasemago** [comment]
Na minha opinião já está tudo super facilitado, e caso necessário faça algum nerf diretamente na cfg do mapa.

**Comment by danielhidalgojunior** [comment]
Níveis de dificuldade do sv com base na pontuação geral do time online
Nego com pontuação boa, config hard
Pontuação bosta, config batata
Já exclui a necessidade de trabalho manual

**Comment by lucaslinha** [comment]
que pontuação ? a do rank ? se for é fora de questão, rank não é e nunca foi parametro de habilidade dos jogadores.

**Comment by danielhidalgojunior** [comment]
não vejo problema em criar um novo indicador para medir a qualidade do jogador.

Óbvio que não teria como usar apenas o rank para criar esse indicador. Existem várias outras variáveis de cada jogador flutuando por aí que podemos usar no cálculo, como:

* média de dano total por mapa jogado
* MVP em eventos (podemos começar a atribuir isso via registro dos jogadores)
* Ebans e punições em geral
* Frequência no servidor
* Quantidade de tempo jogado no mapa atual
* Quantidade de vitórias no mapa atual

A lista é grande, e não é difícil de coletar essas informações e muito menos de armazená-las.

E aos que se preocupam com espaço em disco pra guardar isso, não vejo motivo, pois levando em conta a simplicidade dessas informações, levaria milhões de registros para consumir uns 500mb.

**Comment by hcjordao** [comment]
Por questões de praticidade. Ter uma análise sobre indivíduos é muito complicado pq olha quantas variáveis tu teria que verificar para gerar um output que diria se um time é bom ou não e tal, isso é muito complexo e para deixar isso bom teria que ser trabalhado multiplas vezes em cima para ficar decente que não é o nosso objetivo.

Por isso sugeri fazer uma analise sobre cada mapa, pq o numero de mapas é finito, com quanto que jogadores sempre tem novos jogadores entrando e tal. Como funcionaria? Bem simples só ter no banco de dados 3 campos: nome do mapa, número de vezes em que o mapa foi jogado em algum periodo de tempo base, e número de vezes que o mapa foi zerado. A gnt vai ter uma porcentagem e seta as configurações em cima dessa porcentagem.

Exemplo:

Mapa | Jogados (3 semanas) | Zerados | Porcentagem | Config Atual
--- | --- | --- | --- | --- 
ze_lotr_mines_of_moria_p2 | 15 | 14 | 94% | Extreme
ze_ponchermonkey_shooter_v3_5_csgo | 1 | 0 | 0% | Super Batata
ze_tesv_skyrim_v5_6 | 13 | 4 | 30% | Batata 
ze_shroomforest2_p6 | 12 | 6 | 50% | Padrao
ze_surf_froyo_lite_v2_3  | 18 | 14 | 77% | Hard


Possiveis Configs: Extreme, Hard, Padrao, Batata, Super Batata.

Ai só teria que bolar 5 configs que sejam de acordo com o que foi definido. O numero de configs quantas e com qual porcentagem nós definimos. Para eventos usamos a padrão ou a hard sei lá. Acho bem mais simples do que analisar a skill individual de um player que é meio hard e de se medir com números, teria que gerar status que nem faz nos jogos de esporte kkkkk

**Comment by lucaslinha** [comment]
Esse metodo é bem falso positivo ne, um mapa pode ter sido zerado 5 vezes antes e a config ser hard, mas o time atual pode ser cheio de batatas, estatistica de mapa não define o time. Na real isso é trampo demais pra pouca coisa e muita complicação.

**Comment by alminha021** [comment]
Maneira mais facil eh um comando mesmo.
Config vai ser a que esta atualmente , mas quando 50% + 1 do time escreve  um comando como !easy ou !batata , a config eh mudada para uma mais facil , a batata, nao sei se precisa carregar o mapa pra essas config surtirem efeito, ideal eh que so seja permitido no inicio, antes de liberar o rtv caso seja preciso carregar o mapa denovo.

!easy ou !batata, entao: 
 - infecçao 1 / 8
 - Mother 310 / Son 305 vel.
 - staminarecovery 60 / tagging 1
 
Como acho que precisa equilibrar a balança , se o !easy/!batata estiver ativo, temos tambem :
 - ranking desativado na !easy !batata
OU
- pontos nerfados (20% dos pontos atuais)

Assim , sera um comando para aqueles que querem conhecer mapa , jogando ao mesmo tempo.

**Comment by lucaslinha** [comment]
Não da para fazer isso pq ela so carrega no proximo mapa.

**Comment by hcjordao** [comment]
Isso vale para both ways de ser falso positivo. Exemplo um mapa não é jogado a muito tempo e a config reseta para super batata e o mapa fica extremamente fácil. Do mesmo jeito como você disse que um mapa que é muito jogado e ocorre de ter somente batata online se torna bem mais dificil. 

Só que se tu parar para pensar dependendo de como é configurado uma situação ou outra é bem dificil de ocorrer, tudo depende da configuração aquela ali é um exemplo alem do que depende de como é configurado cada uma das .cfgs, exemplo modo hard para o modo extreme pode ser simplesmente um rebuy a menos de granada tlg não precisa viajar na maionese nas configs de tipo completamente impossivel de zerar ou humanos extremamente ops. Além do que podemos dar pontos extras ou menos pontos dependendo da configuração atual do mapa. Podemos além disso adicionar um booleano no db que diz se um mapa foi zerado a X meses no server e se não tiver sido da um boost enorme de pontos para os jogadores, etc etc.

Mas concordo que esses casos podem ocorrer mas não difere muito de qualquer outro mapa um pouco mais difícil que caia no servidor onde o time seja completamente batata vão passar perrengue de qlqr maneira. O único motivo dessa sugestão é não ter que ficar setando manualmente uma config global ou ter que editar configs especiais para cada mapa como o @quasemago falou.

**Comment by lucaslinha** [comment]
Por Exemplo : Decida a dificuldade de cfg do prox mapa "ze_boatescape"  
1. Padrão 
2. Facil (Rank - 30 %)
3. Batata (Rank Desativado)

**Comment by hcjordao** [comment]
A minha sugestão é deixar o mais modularizado possível para tipo se quiser alterar não ter que fazer edits em arquivos individuais para mudar a configuração. Pode apenas ser 2 grupos de configuração batata e tryhard como era antes mas agora tu tem uns números a mais para se basear e tomar suas decisões. Se quisesse deixar 100% batata era só editar no arquivo e boom its done.

**Comment by hcjordao** [comment]
> Por Exemplo : Decida a dificuldade de cfg do prox mapa "ze_boatescape"
> 
> 1. Padrão
> 2. Facil (Rank - 30 %)
> 3. Batata (Rank Desativado)

Quanto mais poder de decisão dar em cima da mão do jogador pior. Vocês vão acabar ouvindo gente falando a joga só no modo facil bla bla bla pq tem algo e vao passar raiva, pq tem time bom e colocaram o bagulho ta batata.

**Comment by lucaslinha** [comment]
Foda se quem reclamar, nego da rtv em mapa pq ? pq sabe que com a cfg atual não consegue carregar 15 peso morto, pelo menos em uma cfg batata ele teria uma chance disso.

**Comment by lucaslinha** [comment]
Para pra pensar pq os caras so jogam surf todo dia, no surf eles so dependem deles mesmos pra garantir a vitoria, vc dar a possibilidade do ser escolhido uma cfg em que um carregue todo mundo nas costas pode ter a chance de novos mapas serem jogados.

**Comment by kobe-hcjordao** [comment]
A única diferença é que um seria por "trás dos panos" e a outra seria com os caras escolhendo. Por mim  nesse ponto da escolha tanto faz.

**Comment by lucaslinha** [comment]
É simples e facil de fazer, não vai precisar muito tempo e muito desgaste diferente das estatisticas.

**Comment by lucaslinha** [comment]
Bom creio que essa é a ideia mais sensata ate agora baseado nas condições atuais do server, queria poder criar as cfgs mas não tem quase nada no git para isso, @kobe-hcjordao estarei esperando você para isso.

**Comment by gabrielacms** [comment]
Acho que nessa altura do campeonato já que pelo visto as coisas já estão decididas minha opinião não iria afetar mt mas enfim, olhando essa sugestão de voto para o pessoal escolher a dificuldade é legal só que o pessoal do sv vai saber qual vai ser a diferença entre o Padrão, Fácil e Batata? E outra não sei se esse "Rank desativado" é só um exemplo mas se for real isso ai para mim só faz sentido desativar rank se não houver nenhuma chance do CT perder. E até onde sei essas alterações vai facilitar mas não vai garantir vitória dos caras.

**Comment by quasemago** [comment]
Sábado eu farei algo referente a isso. Irei criar um sistema de cfg alternativas diretamente no ZR.

@lucaslinha quando estiver pronto postarei no git certinho.

**Comment by lucaslinha** [comment]
@gabrielacms Para eles saberem o que muda, eu pensei naquela sugestão que eu dei a um tempo atras usando aquele menu de texto com as infos da atual cfg, assim que eles entram no server, o menu aparece. 
Ja para a cfg batata eu pensei em uma cfg voltada para ser usada em um mapa totalmente desconhecido pelos jogadores atuais, para que eles ao menos sintam uma pequena vontade de tentar desbravar o mapa ao inves de so da rtv, uma cfg ct side total, entao acho que faria sentido não ter recompensa de pontos.

**Comment by quasemago** [comment]
Recurso foi adicionado ao servidor e se encontra em testes. Mais detalhes no repositório privado de configs.

**Comment by hcjordao** [comment]
Isso está ativo ou deu ruim? Entrei hoje e não vi votação de ativação do modo batata/etc

**Comment by hcjordao** [comment]
A fase de teste tem uma deadline?

**Comment by lucaslinha** [comment]
> A fase de teste tem uma deadline?

Não foi finalizado ainda, falta o recurso de whitelist, pois estavam votando em todo mapa aparentemente.

**Comment by quasemago** [comment]
Visto que que votação acontece após o nextmap ser definido, é possível fazer uma whitelist/blacklist para não acontecer a votação em determinados mapas.

**Comment by lucaslinha** [comment]
Se for atraves de comando acho melhor quando checar o mapa dentro da lista aparecer uma mensagem: O próximo mapa possui uma dificuldade mediana ou superior, considera o mapa muito dificil para o time atual ? utilize o comando !vtd

**Comment by quasemago** [comment]
Inviável, a maioria dos players não lê o chat. Fiz a whitelist para liberar a votação apenas em determinados mapas, estarei atualizando o repositório privado.

**Comment by danielhidalgojunior** [comment]
Meio tarde mas, automatizar o processo seria bem mais simples e daria muito menos dor de cabeça para os admins. O processo automático poderia dar a config atual base e através de um override via comando permitir que os players escolham.

É só começar a usar poder do DB e um pouco de planejamento.

**Comment by hcjordao** [comment]
Bem joguei ontem pela primeira vez no servidor o modo batata no mapa frostdrake. Ai vão minhas impressões da feature:

1. Não vi esses dias nenhuma movimentação do servidor com interesse de jogar nesse modo de configuração. Jogadores que são novatos não conseguem entender um pouco como funciona isso e jogadores que já jogam no servidor passam longe disso dai.

2. Realmente ficou bem fácil jogar o mapa, com aquele time conseguiu passar a parte do elevador e chegar no hold de um minuto do mapa, mas isso pq tinha um jogador veterano jogando usando granada e re buy pra conseguir segurar o zm, com 150 balas numa smg fica muito de boas pra farmar e conseguir recomprar outra. Resumindo, só fez quem conhece os mapas ter que carregar muito mais os novatos, não necessariamente promoveu a ideia dos jogadores de conhecer o mapa, no fim do dia maioria daquele povo não conheceu nada o mapa.

3. A falta de Rank é completamente um turn-off pro servidor. Se for pra incentivar os jogadores a jogarem mapas novos eu prefiro dar aqueles overbuffs que davamos antigamente nos mapas de dar 500 pontos zerando aquele mapa (e começar a dar ponto pra quem lidera em mapa pq isso que faz a diferença), entretanto fazemos a decisão de não dar pontuação de rank em evento para não ter os caras que somente jogam no evento e depois nunca mais e ainda conseguem ficar top 1 no Rank do servidor.

4. Se for pra deixar o modo super buff de CT prefiro com o sistema de RPG que os boludos usam ou automatizar como eu disse mas mantendo o Rank.

**Comment by lucaslinha** [comment]
1. Isso é normal, jogador novato nunca entende os features novos do server, ja os regulares que passam longe geralmente são os que jogam o mesmo slender, crash e surf todo dia, não se arriscam em um mapa diferente em uma config normal nunca, logo pra mim não faz diferença eles quererem jogar ou não. 

2. Sim alguns mapas com holds simples ainda é possivel passar sem call alguma, como no taboo carnation que chegaram no ultimo hold sem ngm falando no voip, fazer o que acontece.  

3. Sinceramente jogador novato não sabe o que é rank, logo eles não vão ligar pra uma coisa que não conhecem e geralmente os que ligam são esses regulares que tu citou que passam longe dessa config, os que jogam os mesmo mapas todos os dias pra garantir seu farm. 

4. Sinceramente o rpg é mais dificil do que essa config, eu so consigo ver regulares se beneficiando disso, ja que você precisa ter binds, conhecimento de menu e etc ...

**Comment by hcjordao** [comment]
> * Isso é normal, jogador novato nunca entende os features novos do server, ja os regulares que passam longe geralmente são os que jogam o mesmo slender, crash e surf todo dia, não se arriscam em um mapa diferente em uma config normal nunca, logo pra mim não faz diferença eles quererem jogar ou não.
> *

Ta mas se não for pra beneficiar os novatos que não vão saber quando a ativar a featura qual o proposito da configuração, ao meu ver a existência depende se o os novatos vão de fato estar se divertindo jogando um mapa e isso acontece já independente de vitória ou não. Se for pelo bem de conhecer um mapa apenas isso so vai vir do cara se interessando por conta própria e quando isso acontecer o cara pode muito bem explorar fora do server os mapas

**Comment by lucaslinha** [comment]
> Ta mas se não for pra beneficiar os novatos que não vão saber quando a ativar a featura qual o proposito da configuração, ao meu ver a existência depende se o os novatos vão de fato estar se divertindo jogando um mapa e isso acontece já independente de vitória ou não. Se for pelo bem de conhecer um mapa apenas isso so vai vir do cara se interessando por conta própria e quando isso acontecer o cara pode muito bem explorar fora do server os mapas

O próposito são 2, quando alguma pessoa quiser conhecer/treinar um mapa desconhecido seja para um evento ou so para conhecer e evitar o cancer do rtv que você deve ter conhecimento sobre isso eu presumo, cai um mapa 4 5 estrelas e quando libera o rtv não pensam 2 vezes em sair do mapa pq estão morrendo demais e acreditam que é impossivel de passar, isso acaba resultando em um cd precoce de mapas ja que vai rodar mais mapas em pouco tempo(assim liberando aqueles outros que uma galerinha ai gosta de farmar) e os jogadores deixam de experienciar um mapa so pq acreditam ser impossivel para o time presente em questão.

**Comment by hcjordao** [comment]
Entendi, mas bem vamos lá sobre seus 3 propósitos.

1. Não vejo incentivo nenhum de um novato buscar conhecimento de um mapa. Como eu disse quem quer conhecer um mapa pode muito bem ir no offline, e a existência da configuração não ta corroborando com isso.

2. Isso vai existir sempre, junto com o motivo um isso não mudou ontem mesmo frostdrake aconteceu a mesma coisa. Sobre cd precoce eu sugiro criar um grupo de mapas chamados overplayed onde se um dele for jogado todos os outros entram em cooldown. E ai vamos adicionando e removendo esses mapas a medida do possível.

3. Acho que esse é o mais pertinente para a existência da configuração batata mas mesmo assim ninguém quer jogar na config batata pq não da pontos. Uma sugestão minha seria overbuffar novamente os pontos de mapas bons e deixar transparente no nominate com o total de pontos do mapa, remover aquilo de novo pq também ninguém liga se o mapa é novo ou não, quem se interessa é veterano que ta presente no discord pra saber. Pois ninguém quer jogar por aprender, povo quer jogar pra ganhar seu pontinho do rank.

**Comment by lucaslinha** [comment]
> Entendi, mas bem vamos lá sobre seus 3 propósitos.
> 
> 1. Não vejo incentivo nenhum de um novato buscar conhecimento de um mapa. Como eu disse quem quer conhecer um mapa pode muito bem ir no offline, e a existência da configuração não ta corroborando com isso.
> 2. Isso vai existir sempre, junto com o motivo um isso não mudou ontem mesmo frostdrake aconteceu a mesma coisa. Sobre cd precoce eu sugiro criar um grupo de mapas chamados overplayed onde se um dele for jogado todos os outros entram em cooldown. E ai vamos adicionando e removendo esses mapas a medida do possível.
> 3. Acho que esse é o mais pertinente para a existência da configuração batata mas mesmo assim ninguém quer jogar na config batata pq não da pontos. Uma sugestão minha seria overbuffar novamente os pontos de mapas bons e deixar transparente no nominate com o total de pontos do mapa, remover aquilo de novo pq também ninguém liga se o mapa é novo ou não, quem se interessa é veterano que ta presente no discord pra saber. Pois ninguém quer jogar por aprender, povo quer jogar pra ganhar seu pontinho do rank.
1. Novato nunca vai buscar conhecimento de mapa, novato so quer entrar pra jogar o modo e ter sua experiencia do mesmo e não tomar taca todo round e falar mapa lixo spamando rtv no chat. 

2. Sempre vai existir mesmo com isso, mas pela minha experiencia durante todos os mapas que joguei com essa config, o numero de gente chorando pra trocar mapa foi menor. 

3. Não, galera quer ganhar ponto da maneira facil, ngm ta disposto a sofrer em mapa pra ganhar ponto, cultura do so zera em evento ta ai para provar isso.

**Comment by hcjordao** [comment]
Batata mode já existe atualmente não vejo a necessidade desse issue ainda existir :)
