### ISSUE TITLE
Introdução de mapgroups ao Mapchooser

### ISSUE THREAD

**Issue by quasemago** [quasemago/zrageservers#78]
Isso foi sugerido in-game e achei bem interessante. 

De início pensei apenas em atrelar o countdown de um mapa ao grupo dele, por exemplo, caso o mapa "X" seja jogado todo o grupo dele irá entrar em countdown (obviamente irá ter uma cvar para controlar isso).

Também pensei na hipótese de limitar o nominate pelos grupos. Exemplo de config:
```
"Groups"
{
	"1" // cosmo
	{
		"_max" "1"
		"Maps"
		{
			"ze_ffvii_cosmo_canyon_v1_1_csgo" {}
			"ze_ffvii_cosmo_canyon_v5k_fix" {}
		}
	}
	"2" // mako
	{
		"_max" "1"
		"Maps"
		{
			"ze_FFVII_Mako_Reactor_v5_3_v5" {}
			"ze_FFVII_Mako_Reactor_V6_b09k2" {}
		}
	}
	"3" // westersand
	{
		"_max" "1"
		"Maps"
		{
			"ze_ffxii_westersand_v2d_ps2" {}
			"ze_FFXII_Westersand_v7_z9" {}
			"ze_ffxii_westersand_v8zeta1_b5k" {}
		}
	}
}
```
No exemplo acima, só poderia ser nomeado 1 mapa de cada grupo (definido pela key **"_max"**), isso será muito útil para evitar dos jogadores nomearem 3 versões do mesmo mapa. E caso o countdown herdado citado no inicio esteja ativo, todo o grupo irá ficar em countdown.

**Comment by lucaslinha** [comment]
Isso tem apenas objetivo de cd ? Unico map group que me vem a cabeça é surf, o resto se quer é tocado no server.

**Comment by gabrielacms** [comment]
Eu gostei. Isso ajudaria bastante na rotação de mapas. Isso se encaixaria com surf (principalmente), mapas do lord of rings. Por enquanto me lembro desses. Eu acho que de início, poderia aplicar só em mapas do mesmo estilo (surf). Mapa que possui mais de uma versão do mesmo no nominate raramente é jogado dessa maneira. E ao invés de ser só 1 mapa para ativar o cooldown, colocar uns 2 mapas para ativar.

**Comment by quasemago** [comment]
Fiz algumas alterações. Modelo atual da config:
```
"Groups"
{
	"1" // cosmo
	{
		"_maxInVote" "1"
		"_inheritance" "1"
		"Maps"
		{
			"ze_ffvii_cosmo_canyon_v1_1_csgo" {}
			"ze_ffvii_cosmo_canyon_v5k_fix" {}
		}
	}
	"2" // mako
	{
		"_maxNominate" "1"
		"_inheritance" "1"
		"Maps"
		{
			"ze_FFVII_Mako_Reactor_v5_3_v5" {}
			"ze_FFVII_Mako_Reactor_V6_b09k2" {}
		}
	}
	"3" // westersand
	{
		"_maxNominate" "1"
		"Maps"
		{
			"ze_ffxii_westersand_v2d_ps2" {}
			"ze_FFXII_Westersand_v7_z9" {}
			"ze_ffxii_westersand_v8zeta1_b5k" {}
		}
	}
}
```
Explicação dos parâmetros:
- **_maxInVote**: Define a quantidade de mapas do grupo que podem entrar para a votação.
- **_maxNominate:** Define a quantidade de mapas do grupo que podem ser nomeados.
- **_inheritance:** Define se o grupo todo irá herdar o countdown quando algum mapa ser jogado. (ps: não irá ser atualizado os mapas que já estejam em countdown).

No exemplo acima apenas uma das versões do "cosmo" irá entrar na votação, enquanto nos demais grupos apenas 1 pode ser nomeado mas ainda existe a chance dos outros mapas entrarem na votação aleatoriamente.

O recurso **_maxInVote** não vai estar ativo de inicio, preciso fazer mais alguns testes. Mas os demais já estão operacionais.

**Comment by quasemago** [comment]
Foi realizado uma otimização geral em todos os plugins que gerenciam os mapas (mapchooser, nominate, nextmap, etc). 

Sistema de grupos funcionando perfeitamente, com exceção do feature **_maxInVote** que devo implementar outra hora. Manterei o issue aberto até finalizar totalmente.

**Comment by hcjordao** [comment]
Qual a diferença do map in vote e max nominate? Não seriam a mesma coisa basicamente? 

Esse inheritance tbm não é meio redundante? Se um grupo já foi criado para ele creio eu que a ideia é inserir todos no cooldown. 

Acho que seria interessante inserir uma outra validação que seria quantos mapas desses podem ser jogados se fosse criado grupos grandes. Exemplo: Um grupo de mapas final fantasy: só podem ser jogados 2/3, depois todos entram em cooldown da votação. A validação ocorreria se o numero limite de mapas estão na lista de cooldown.

Fora essas duvidas achei bem interessante, outros servers como GFL tbm usam isso para ajudar a rotacionar nos mapas. 

Sugestões de outros grupos: FF Group, Luffaren Big Maps (Santassination, Eternal Grove, Best Korea, Diddle), Cube Mappin (Gris, Grau, Deadcore, HSC)

**Comment by hcjordao** [comment]
@quasemago

**Comment by quasemago** [comment]
Esta bem explicado a diferença do funcionamento das opções.

O countdown herdado acho válido deixar caso não queira adicionar o grupo inteiro em cd. Também ja existe uma cvar para definir quantos mapas do grupo devem ser jogados no dia para o grupo herdar o cd (atualmente em 2).

**Comment by hcjordao** [comment]
Está explicado mas não vi diferença nessas opções por isso fica a duvida ai. Tu tem um limite X de de mapas que podem ser nomeados (_maxInNominate), como esses mapas estão na votação tbm? Ja foi filtrado antes kakakakakaak a nao ser que a gambi ta louca no source 🤣 

_inheritance: Se foi definido um grupo no arquivo, obviamente que queremos que herde o cd.

**Comment by quasemago** [comment]
Ue, tu pode nomear 1 mapa FF e entrar 3 na votação aleatoriamente. Entendeu o ponto?

Apenas uma opção extra caso um dia queira usar.

**Comment by hcjordao** [comment]
Ah entendi, mas para mim mapas randomicos já deveriam ser filtrados, pq se não foge um pouco de ideia de ter grupos de mapas. Os mapas randomicos são inderidos posteriormente correto?

**Comment by hcjordao** [comment]
@quasemago uma duvida em caso de grupos muito grandes de mapa. Ao invés de setar o grupo em cooldown em apenas um mapa poder escolher número de mapas que podem ser jogados.

Exemplo: Grupo Surf
Sao 9 mapas dentro desse grupo. Ao invés de ser apenas um, poder ter a opção de um grupo maior.

**Comment by quasemago** [comment]
Ja existe isso, mas é uma cvar geral. Posso alterar o parâmetro **_inheritance** para servir para esse propósito.

Depois faço isso e atualizo o git das configs.

**Comment by quasemago** [comment]
Parâmetro **_inheritance** foi alterado, agora basta configura-lo para quantos mapas do grupo será necessário jogar para o mesmo entrar em countdown.

Git privado foi atualizado com a nova config.

**Comment by gabrielacms** [comment]
Aproveitando que está aberto ainda, se possível remover o mapa Castlevania do mapgroup. Assim como o Fapescape, as duas versões que de Castlevania que estão no servidor são BEM diferentes uma da outra, sendo assim, não faz sentido bloquear o nominate dos dois mapas ao mesmo tempo ou até mesmo colocar um em cooldown quando o outro é jogado

**Comment by hcjordao** [comment]
Criei um pr no zconfigs para remover o castlevania. Fapescape não faz parte do arquivo

**Comment by gabrielacms** [comment]
Sim, eu sei, eu só citei ele como exemplo de mapas que possuem mesmo nome mas são completamente diferentes um do outro

**Comment by lucaslinha** [comment]
So queria destacar também que não entendi pq isengard e minas tirith estao no grupo de lotr sendo que eles nunca são jogados, fazendo isso é que nunca serão jogados mesmo.

**Comment by quasemago** [comment]
Alterações feitas:
- Grupo do castlevania removido.
- Removido os mapas isengard e minas tirith do grupo LOTR.

**Comment by quasemago** [comment]
Issue fechado, ele será reaberto quando for conveniente.
