### ISSUE TITLE
Sobre o som dos tiros.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#79]
Isso é totalmente irritante para quem joga com isso ativado, se tiver gente que gosta de ouvir os 300 tiros ao mesmo tempo eu duvido que passe dos 5% no server, mas com certeza não há nada mais irritante do que jogar com companheiro de time surdo devido a isso, isso definitivamente é o pior.

Ja que acham que desabilitar isso confunde cabeça das pessoas(não sei onde isso confunde), pelo menos da opção do cara desligar durante a entrada dele e isso sem poder fechar o menu antes dele escolher uma opção.

**Comment by quasemago** [comment]
@hcjordao Algo a dizer sobre isso? Infused já sugeriu algumas vezes deixar o stopsound ativado de padrão para novos players, mas pensei que isso pode confundir os batatas.

**Comment by alminha021** [comment]
Sigo a mesma logica do !music
"eh mais facil ensinar alguem a ligar o som dos tiros, do que ensinar um pobre coitado que nao esta escutando nada devido ao tiroteio"
Spu a favor de desabilitar o dom dos tiros por padrao tbm

**Comment by quasemago** [comment]
Som dos tiros desativado de padrão para novos players. Veremos como fica.

**Comment by hcjordao** [comment]
Eu prefiro desativado já pq qlqr coisa o cara pode perguntar ou ele pode ver naquelas mensagens de texto sobre a ativação/desativação dos sons de tiro. Já ter desativado é bem mais benéfico ao meu ver.

**Comment by quasemago** [comment]
Parece que ninguém reclamou, tem mais algo a acrescentar? @hcjordao @lucaslinha
