### ISSUE TITLE
Skin de zm Slenderman Invisivel no ze_slender_escape_rc2

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#8]
Skin do slenderman invisivel quando o zm picka.

**Comment by quasemago** [comment]
Provavelmente o mesmo problema do #7

**Comment by hcjordao** [comment]
Mapa removido do nominate até fix.

**Comment by lucaslinha** [comment]
Ja foi resolvido, aguardando fechamento do issue.
