### ISSUE TITLE
Possivel bug no required.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#81]
Hoje presenciei aesthetic caindo na votação quando não tinha nem 30 pessoas on e na required precisa de 35. Precisa investigar isso dai.

**Comment by quasemago** [comment]
Fiz uma juste na logica do código, agora deve estar funcionando corretamente,

**Comment by quasemago** [comment]
@lucaslinha alguma novidade sobre isso? já faz uns dias que fiz um ajuste no código.

**Comment by lucaslinha** [comment]
Nunca mais vi algum mapa da required aparecendo assim.

**Comment by quasemago** [comment]
Caso volte a acontecer, crie outro issue.
