### ISSUE TITLE
ze_Parkour ignorando cd.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#82]
O mapa foi jogado com mais ou menos 10 horas de diferença.

EDIT: (11/04/2020). 
Causa disso é que o plugin de cd está lendo o nome do mapa de maneira errada, no maplist está escrito Parkour e no maphistory está escrito parkour.

**Comment by hcjordao** [comment]
Acho que isso é um bug a parte de mapas, ñ faz sentido ser relacionado a um mapa apenas.

**Comment by hcjordao** [comment]
Como não houve updates do issue irei fechar.

**Comment by lucaslinha** [comment]
EDIT: (11/04/2020). 
Causa disso é que o plugin de cd está lendo o nome do mapa de maneira errada, no maplist está escrito Parkour e no maphistory está escrito parkour.

**Comment by hcjordao** [comment]
Esse arquivo está disponivel no repositorio de configs?

**Comment by quasemago** [comment]
Isso pode ser fixado renomeando os mapas para tudo minusculo (server e fastdl).

**Comment by hcjordao** [comment]
Podem me passar a lista de mapas que estão bugados.

1. Vou remover do nominate em primeiro momento todos
2. Renomear os mapas no fastdl e no server
3. Colocar novamente no nominate

**Comment by lucaslinha** [comment]
Os que se sabem são:
ze_JurassicPark_Escape_p2 / ze_JurassicPark_p3 / ze_Parking_p4 / ze_Parkour_r

mas deve haver bem mais, como disse antes, o melhor a se fazer era pegar o historico do maphistory e dar um compare com o mapcycle para ver a diferença de nomes.

**Comment by hcjordao** [comment]
Esses mapas foram removidos no meio tempo pois não é apenas uma edição de texto para arrumar. É necessário fazer o reup dos mesmos com letra minúscula. Iremos fazer o reupload e tratar a transição dos arquivos com os nomes errados para o novo antes de bota-los no nominate de novo.

**Comment by hcjordao** [comment]
Fixados aparentemente 🚀 , qualquer bug relacionado favor abram issues diferentes para cada mapa 🌶️
