### ISSUE TITLE
Alteração no cmd de level.

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#83]
Precisa ser retirado o warmup da contagem de leveis para não confundir mais ainda a cabeça dos confundidos, creio eu que todos os warmups estão com a keyvalue 0, então creio que ignorando o 0 e começando do 1 resolva isso.

**Comment by hcjordao** [comment]
Já abri o PR (linkado acima) removendo o warmup dos mapas na lista atual. Se forem querer so mergear na master.

**Comment by quasemago** [comment]
Foi feito uma alteração no ZE Ranking e o mesmo irá ignorar os levels de numeração "0", ou seja, os warmup. Mas também é válido remover da configuração tais leveis.
