### ISSUE TITLE
[TTT] Inserir no sm_log detecção ao passar pela safezone

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#86]
Facilitar verificação de reports.

**Comment by hcjordao** [comment]
Depois faz esse mini ajuste no log plox @quasemago

**Comment by danielhidalgojunior** [comment]
Aproveitando o embalo, coloca o sm_kos pra aparecer no log tb

**Comment by hcjordao** [comment]
Criei um issue separado para isso @danielhidalgojunior #102

**Comment by quasemago** [comment]
Done!

`[SAFEZONE]-> [Fulano [STEAMID] (Traitor) foi detectado pela safezone]`

**Comment by lhsatsuma** [comment]
Testado e aprovado!

![image](https://user-images.githubusercontent.com/44283104/76910827-d3b8c300-688d-11ea-86f7-4bc935e07ad4.png)
