### ISSUE TITLE
Anti Edge ou Anti batatao da Ponta 

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#87]
É um recurso pra prevenir potatos que ficam na ponta serem pegos e pegarem o time em seguida, a facada de infecçao fica com um delay para infectar, assim dando a chance do time que nao tem nada a ver de atirar no dito cujo e tira lo de perto do time. Em um server gringo que joguei é 2 segundos e ao meu ver funciona bem.

**Comment by lucaslinha** [comment]
Se possivel uma convar para aumentar esse tempo, a fins da cfg batata.

**Comment by hcjordao** [comment]
Mas como o plugin detecta estar numa ponta? Pq eu vejo alguns casos que isso não deve funcionar muito bem

**Comment by lucaslinha** [comment]
Não sei se tem proteção, mas se tiver so consigo pensar em por exemplo verificar se o zm pegou mais de um ct, se um zumbi pegou 2 cts dentro de um intervalo de tempo então o anti edge não seria ativado, mas se o zumbi pegou apenas 1 ct, entao ele seria ativado.

**Comment by hcjordao** [comment]
É que tipo eu acho que faz parte do jogo, e acho que em casos de troll a adm que tem que punir. Deixar automatizado isso vai ser ruim pro zm. Eu consigo ver muito cenario que isso seja injusto. Então ao meu ver não gostaria de ver esse plugin no servidor, motivo sendo que estar na ponta é muito relativo para ser usado um plugin.

Exemplo: Buraco la no frostdrake que tem que defender 60s,

Zm entra bunando e o cara nao ta na ponta ele pode estar encostado na parade, dependendo de como o zm entra da pra pegar, ai tipo é um merito do zm que vai estar sendo destruido pelo jogo, que é bem frustrante.

**Comment by alminha021** [comment]
Pra mim faz parte do jogo tbm, seria frustante vc se esforçar de zm e o cara q morreu não poder fazer nada, eu ja fico com raiva qnd o cara morre por mérito do zm e se recusa a infectar os outros.

Se o cara morreu trolando, cabe aos reports e punição de admin.

O que pode ser mudado eh ser mais rigoroso com quem ta trolando na ponta mesmo, parar de avisar e ja começar com kick e ban leves.

**Comment by quasemago** [comment]
Precisa mapear todo mapa, isso só serviria para o ZM. Quero ver quem vai ser o doido pra mapear ponta de todo **ze_**.

**Comment by lucaslinha** [comment]
Que exemplo é esse ? nao tem como o zm pegar o cara naquele buraco sem ele estar na ponta. 
E particularmente quando me pegam na ponta eu me afasto logo do time pra nao pegar eles, admito mesmo, se eu morri na ponta foi merito meu de ser burro, não vou envolver os outros nisso.

**Comment by lucaslinha** [comment]
A ideia inicial era so para a cfg batata, então se você ainda quiser fazer no futuro @quasemago , não precisa ser de maneira geral.

**Comment by hcjordao** [comment]
Acho isso errado seu objetivo ao ser infectado não é mais pensar em humanos e sim matar os mesmos. Foi erro seu mas agora seu objetivo é infectar. Muitos de nós fazemos isso de morrer e não infectar depois de morrer.

**Comment by hcjordao** [comment]
@quasemago esse plugin faria de forma automatica, o que o @lucaslinha ta falando. Acho que nem pra ZM nem pra ZE isso deveria existir, isso era uma das minhas principais reclamações da ZmBr de remover uma das essencias basicas do game.

**Comment by lucaslinha** [comment]
Bom se vc ta reclamando tanto, deveria entrar la na Pse e ver que não é tão roubado como vc ta falando ai, 2 segundos se passam em um piscar de olhos.

**Comment by hcjordao** [comment]
Não estou reclamando estou apresentando que não acho que isso deva ser adicionado ao nosso servidor.

**Comment by lucaslinha** [comment]
E eu sei que é errado mas eu nao consigo seguir uma regra a risca que nao é etica pra mim, o time defendendo perfeitamente para apenas 1 cara bobeando estragar isso.

**Comment by lucaslinha** [comment]
Não tem problema, eu ja disse que se o ronning quiser fazer no futuro, será so para a cfg batata que é justamente a cfg voltada pra casual jogar.

**Comment by hcjordao** [comment]
Acontece mano, faz parte do jogo. Não é assim se o @quasemago quiser fazer, isso tem que ser concordado por nós. Alma e mais um admin (não vou mencionar até se decidir se pronunciar) concordaram cmg que isso é parte do game. Estou esperando ela se pronunciar futuramente, caso não for aprovado, não vai ser inserido, nem mesmo ao jogo casual.

**Comment by lpcorrea** [comment]
Bom, de minha parte acho esse plugin desnecessário em qualquer caso. Se o cara fica na ponta 1 vez azar, se ele começar a ficar muito para prejudicar o time cabe a algum Staff aplicar uma punição.

**Comment by danielhidalgojunior** [comment]
Bom, vou dar a minha opinião sobre o assunto. Essa parada aí é a o mesmo esquema das punições quando se era pego na ponta nos servidores de zm/ze da ZMBR (sharivan incomming). Por experiência própria, creio que é uma péssima ideia. É praticamente um tira gosto; Nego é pego na ponta o tempo todo, faz parte do jogo e ao meu ver dá uma certa sensação de alerta aos jogadores pois eles sabem que a qualquer momento um parceiro pode ser pego na ponta e infectar o resto. Obviamente, existem casos e casos, mas na maioria deles isso acontece por acidente e em certos momento é até engraçado.

**Comment by quasemago** [comment]
Sou contra isso, talvez no modo batata criado pelo @lucaslinha. Mas já tem tanta facilidade nessa config que daqui a pouco o humano consegue zerar com o monitor desligado.

**Comment by hcjordao** [comment]
Então, 

Assim como acho estar na ponta uma parada subjetiva para ter um plugin que faz isso automatico.

**Comment by lucaslinha** [comment]
É talvez ja tenha coisa demais, mas nunca fale que ta facil demais, pq vc pode acabar se surpreendendo.

**Comment by hcjordao** [comment]
Decisão de não implementar feature nesse primeiro momento.
