### ISSUE TITLE
Granadas Especiais para o Shop

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#88]
T compra o item e recebe uma granada. Essa granada possui um range e funciona por um tempo X. Jogadores pegos no raio da granadas vão movendo para o centro de forma devagar mas sem conseguir fugir.

**Comment by quasemago** [comment]
Demonstração do plugin: https://www.youtube.com/watch?v=Hm668e4Qn9g

**Comment by danielhidalgojunior** [comment]
não só o de gravidade, mas todos os efeitos são bem interessantes. Creio que a maioria deles podem ser incorporados no TTT e até remover alguns itens de T que caíram em desuso.

**Comment by lhsatsuma** [comment]
Acho uma boa se:
1. Realmente ele puxar mais devagar.
2. funcionar por no máximo 5 segundos.
3. Se causar dano apenas quando estiver encostado na gravity (20 hp acho ideal).

Seria interessante tbm se tivesse uma de freeze mas que funcione apenas por 2 seg (só pra poder escapar dos tiros).

**Comment by danielhidalgojunior** [comment]
uma coisa interessante que poderia adicionar a essa granada de gravidade, é que ela poderia remover as armas primarias dos jogadores no raio e fazer elas ficarem presas no centro de gravidade com um push bem mais agressivo do que o que puxa os players.

**Comment by alminha021** [comment]
o primeiro ali seria legal se desse drop na arma dos caras. o do black hole.v
o ultimo ali eh daora tbm, parece mais uma "gravidade"

**Comment by nil209** [comment]
curti o item de puxar a galera, sempre quis fazer uma players com esse tipo de item.

A minha ideia é só puxar os player sem nenhum tipo de dano e combar ele com outros itens, porem como seria muito op, o valor do item teria que ser o mais caro da loja.

20k?

**Comment by danielhidalgojunior** [comment]
O preço pode começa reduzido pra deixar o pessoal comprar e testar. Depois aumentamos se ele vai ser tão op quanto parece. Por mim começaria no 5k

**Comment by danielhidalgojunior** [comment]
@quasemago o que acha de botar o plugin das granadas no sv pra testar? admin only por enquanto

**Comment by nil209** [comment]
Ainda aguardando essa coisa linda

**Comment by quasemago** [comment]
Soon, também irei fazer a granada do fortnite que força os jogadores a dançar.

**Comment by hcjordao** [comment]
Acho mais valido criar um issue sobre features a serem implementadas que façam address a esse issue. Atualmente está largado. irei dar close no issue no momentaneo @quasemago se tu tiver trabalhando nisso tu pode criar um issue falando mais sobre a feature/features? 

Ai linkamos com esse issue.
