### ISSUE TITLE
Custom Nades 

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#89]
Dar ao top defender uma granada especial com efeitos especiais via plugin mostrado pela gabi.

Sugestões:
-  Grav nade 1: Puxa zumbis para um lugar por um tempo X
- Grav nade 2: Levanta os zumbis por um tempo X
- Static nade: Cria um campo de slow por um tempo X
- Qualquer outra sugestão.

**Comment by hcjordao** [comment]
Eu vendo o vídeo ali (https://www.youtube.com/watch?v=Hm668e4Qn9g) , a granada de explosão seria perfeita para uma failnade não acham? a granada tem 10% de chance de ser fail seria muito massa para adicionar ao plugin que falamos de special modes no ZE

**Comment by lucaslinha** [comment]
Sei que é voltado so para granada, mas acho que poderiamos aproveitar as armas do danger zone e alterar os efeitos dela. 
Por exemplo a zed utiliza a weapon_bumpmine com efeito congelante. 
E a 93x utiliza a weapon_breachcharge com efeito de dano e napalm. 
 
Não precisa ser exatamente esses efeitos, eu digo eles podem ser usados como base, é sempre bom se aproveitar de mecanicas diferentes alem da classica granada.

**Comment by hcjordao** [comment]
Acho interessante, mas acho que isso não é uma feature prioritária agora. No futuro posso abrir novamente.
