### ISSUE TITLE
Materia Redemer causa client crash quando o ct usa no ze_ut2004_convoy_r5

### ISSUE THREAD

**Issue by lucaslinha** [quasemago/zrageservers#9]
ct usa e da adeus pro server.

**Comment by hcjordao** [comment]
Acho que vou simplesmente remover esse item do mapa. Não adiciona nada a mais no mapa pros humanos, da pra jogar tranquilo sem ele.

**Comment by hcjordao** [comment]
Removido o item, esperando sync do repo com o server.

**Comment by quasemago** [comment]
Server já está sincronizado. Irei fazer um teste antes de fechar o issue.

**Comment by hcjordao** [comment]
Achei oq kicka o cliente é no butao do item, dois scripts no OnPressed para fazerem o item funfar. Não sei oq altera ali, são ambos identicos entretanto que um começa 0.1s depois. Como o item não faz tanta diferença irei so remover o mesmo e vida que segue, quem quiser tentar arrumar depois a vontade. Não sei se vale o esforço tbh.
