### ISSUE TITLE
Granadas especiais para traidores

### ISSUE THREAD

**Issue by danielhidalgojunior** [quasemago/zrageservers#90]
Seria interessante inserir algumas granadas especiais como itens para traidor.

Inicialmente, pensei numa granada com efeito de black hole, puxando todos os inocentes para um mesmo ponto por alguns segundos.

Segundo a Gabi, existe um plugin que adiciona granadas com efeitos especiais. Poderíamos reaproveitar o plugin para criar esses itens.

O que acham?

**Comment by danielhidalgojunior** [comment]
https://www.youtube.com/watch?v=Hm668e4Qn9g

**Comment by quasemago** [comment]
Já existe um issue referente a isso: #88
