### ISSUE TITLE
Se possível adicionar o tracer do líder na !hidestore

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#91]
Eu sei que o intuito do tracer é o líder mostrar onde tem que atirar etc só que esse tracer está muito forte e como sai muito tiro é um spam enorme de tracer. Mais cedo tinha algumas pessoas perguntando como desativava ou se tinha como desativar o tracer mas não tem.

**Comment by lucaslinha** [comment]
Aproveitando esse issue do tracer do lider, pelo amor de deus, o sprite dele todo bonitao e o do vip aquele palito, bota esse sprite no vip tmb.

**Comment by alminha021** [comment]
Ja eu achei o dele pior que os do vip, unica coisa legal eh o fato de mudar de cor, a grossura dele achei exagerada, o lider atira parece que ta saindo um buque de flores , achei muito poluído visualmente, pra mim deixava da grossura do tracer de vip.
MAs se forem deixar como esta, que ele seja add ao !hidestore.

**Comment by quasemago** [comment]
Bom, foi proposital deixar o sprite do tracer do lider mais "grosso" e inclusive atravessando paredes. Dessa forma os batatas não tem dificuldade de enxergar onde o lider está atirando.

Quanto a adicionar ele ao hidestore, creio que seja melhor fazer um comando independente tipo **!hideleader** (que ocultaria tanto o tracer quanto os sprites de objetivo).

**Comment by lucaslinha** [comment]
orra... esse tracer é muito bom, coloca esse tracer como opçao pra selecionar no vip, muito melhor que essa bosta de palitinho que tem la.

**Comment by quasemago** [comment]
Adicionei o comando: **!hideleader** / **!hidelider**

Irá ocultar todos sprites criado pelo lider (objetivos e tracers)

**Comment by hcjordao** [comment]
Testei e está funcional
