### ISSUE TITLE
Bug Top Defender 

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#92]
Top defender está anexedo junto com o trigger do level por algum motivo. Desacoplar isso para sempre ser funcional e não com o hook do level

**Comment by quasemago** [comment]
Não é um bug, foi implementado dessa forma propositalmente. Anyway, já alterei para mostrar o topdefender mesmo os humanos não chegando ao trigger/timer do level.

**Comment by kobe-hcjordao** [comment]
Tu alterou isso e e fez os perks de serem top defender tbm ser ativados?
