### ISSUE TITLE
TTT - Permissão de Helpers

### ISSUE THREAD

**Issue by lhsatsuma** [quasemago/zrageservers#94]
Votação democrática:

1. Helpers deveriam poder ver o T em cima dos traidores quando mortos (acho isso de grande utilidade ao invés de ficar esperando o cara dar um tiro pra aparecer no log ou até msm saber se o cara AFK é traidor).

2. Aumentar limite de punishs: atualmente 3 não faz muito sentido, visto q muitas vezes no mesmo mapa o cara comete vários RDM e só temos permissão pra colocar até 3 rounds.

3. Permissão para beacon: Se tem dois caras vivos e eles não conseguem se encontrar, é díficil mandar via zsay aonde eles tao pra poder ajudar e etc...

**Comment by hcjordao** [comment]
1. Não me incomodo de dar visibilidade para Helper do TTT ver o T. Eu até achava que tava assim.

2. Pra mim é padrão a limitação de poderes do Helper. Até um Admin (Fuzi e Spawn) ambos concordarem em colocar alguém para mod. Deixar em status de Helper.

3. Não me incomodo tbm em acesso ao beacon.

**Comment by Tardigrada-TTT** [comment]
1. Concordo com o BIG

2. Também concordo, visto que os jogadores já sabem dessa limitação e usam isso até mesmo como modo de provocação sabendo que terão pouco tempo de punish (apenas uma  vez aconteceu comigo).

3. Não tinha pensado nisso, mas concordo totalmente

**Comment by danielhidalgojunior** [comment]
Concordo com a visibilidade de T quando morto.

Beacon tbm é de boa. 

Sobre o limite de punição, creio que deve ficar como está, senão logo não haverá distinção entre helper e mod.

E basta pedir para algum mod/admin aplicar a punição caso seja algo grave ou reincidente

**Comment by lhsatsuma** [comment]
Ok entendido a questão do aumento dos punishs...

Já q ninguém mais vai comentar aqui, podem liberar o beacon e a visibilidade de T?

**Comment by quasemago** [comment]
- Adicionado.
- Na verdade são 4 rounds.
- Adicionado.
