### ISSUE TITLE
Tag automatica

### ISSUE THREAD

**Issue by hcjordao** [quasemago/zrageservers#97]
Fazer a gerencia da entrega de tags automaticamente. Cada mapa tem a quantidade necessárias para upar sua tag. Acho isso o maior incentivo que um jogador tem pra jogar mapas, pois sabemos 100% que os caras amam tags. Dar a oportunidade pro jogador ganhar fora de evento seria muito bom.

Exemplo:
Skyrim -> Elite -> Necessário zerar 4 vezes. 
Aesthetic -> Elite -> Necessário zerar 1 vez.
Boatescape -> Elite -> Necessário zerar 30 vezes.
Por ai vai.

Tava falando com o fanzack e o alma aqui e seria muito de boas de fazer isso, em questão logica, seria so um pouquinho demorado pra fazer a implementação devido duas coisas. 
1. Criar os hooks dos mapas, pra fazer a validação e incrementação do banco de dados e linkar direitinho ao entrar no server.
2. Criar as tags de todos os mapas. 250 mapas seriam 250*5 = 1250 tags para serem criadas.

**Comment by lucaslinha** [comment]
Vai parecer critica, mas isso é muito trabalho para pouco interesse dos jogadores, eles vão investir nos mapas mais faceis de se conseguir a tag e não de uma forma geral.

**Comment by lucaslinha** [comment]
Como eu ja venho batendo em uma mesma tecla a muito tempo, ngm joga um mapa sabendo que o time não tem condições de passar, logo vão escolher um mapa em que eles consigam se virar e carregar o resto do time, ou seja os mesmos sempre. Não muda a o que ja acontece no server.

**Comment by hcjordao** [comment]
Só precisa ter critica e botar mapas faceis com barreiras grandes de passar

Boatescape Elite -> 100 vitorias; Boatescape Veteran 250 Vitorias; Boatescape Pro -> 500 vitorias; Boatescape Legend -> 1000 vitórias; Boatescape God -> 2000 Vitórias

Aesthetic Elite -> 1 Vitoria; ... Aesthetic Veteran -> 2 Vitórias

Skyrim Elite -> 5 Vitorias; Skyrim Veteran -> 15 vitórias; Skyrim Pro -> 30 vitórias; Skyrim Legend -> 70 vitórias.

Gris Elite -> 3 Vitórias; Gris Veteran -> 10 Vitórias.

**Comment by hcjordao** [comment]
Com isso aumentamos ainda mais o CD dos mapas. E todo mapa que o cara vence ele ta progredindo pra uma tag.

**Comment by danielhidalgojunior** [comment]
Da pra automatizar a geração de tags Tb, basta criar os níveis de tag e salvar o nome padrão de cada mapa no registro do mapa em si

**Comment by danielhidalgojunior** [comment]
Além de ser benéfico para os jogadores que vão poder correr atrás das suas tags por conta própria, seria bom pra staff já q n teria q ficar botando tag pra muito nego todo evento

**Comment by lucaslinha** [comment]
Caso isso vá para frente, seria possivel deixar esse ganho de tag so durante a semana ? Precisa eliminar essa cultura do "Esse mapa é de evento, passa não."

**Comment by lucaslinha** [comment]
Creio que deixar a semana com recompensas atrativas seria uma boa tentativa disso, os jogadores tem que começar a se acostumar a jogar com time lixo e tentar carregar eles do que apenas depender de time de evento.

**Comment by danielhidalgojunior** [comment]
como é uma funcionalidade no estágio conceitual, creio que podemos pensar em como integrar os eventos para não interferir na dinâmica atual em vez que apenas desativar a rotina no fim de semana.

**Comment by lucaslinha** [comment]
> como é uma funcionalidade no estágio conceitual, creio que podemos pensar em como integrar os eventos para não interferir na dinâmica atual em vez que apenas desativar a rotina no fim de semana.

Não é desativar, os eventos e tryhards do fds vão continuar funcionando, separar isso é uma fora de fazer eles criarem independecia de esperar time bom pra se esforçar, deixarem de serem uns fracos acomodados.

**Comment by hcjordao** [comment]
Não temos planejamento então de fazer essa feature. Então irei fecha-la nesse momento devido falta de prioridade.
