### ISSUE TITLE
[Sugestão] Melhorar os itens da store

### ISSUE THREAD

**Issue by gabrielacms** [quasemago/zrageservers#98]
Bom, eu já tinha comentado isso uma vez mas acho que não viram direito. Minha sugestão é melhorar totalmente essa store no servidor. Deixar essa store atrativa para o jogador. Tirando a granad e pet, acho que um player normal não consegue comprar mais nada nela. O resto é coisa de evento e coisa para vip. 
Para não colocar muita coisa diferente que tem no sv, pega aqueles itens mais sem graça que tem para o vip e taca tudo na store para o pleb.
- Skin
- Coloca aura também 
- Facas do zknifes 
- Taunts 
Mas TUDO isso sendo limitado e não permanente. Igual era antigamente. Comprar por 1 semana por exemplo e também não sendo um preço muito caro, por ser algo temporário. 
Nossa store atualmente está praticamente voltada para recompensas de evento e itens para vip. Se desse para colocar mais umas coisinhas ai para jogador normal poder usar tb seria legal.

**Comment by hcjordao** [comment]
Conversei bastante com a gabi alma e fanzack e posso dizer que da pra por muita coisa massa que nao ocupa tanto espaço que uma skin ocupa:

- Sons de entrada no server
- Sons para serem tocados no round com limite por jogador e limite maximo tocado dentro de 1 minuto
- Sprays
- Auras
- Pet, aparentemente tem um monte do pokemon pra por.
- Facas zKnifes.
- Caso ocupe muito espaço removermos os vips deluxe e colocarmos skins que são trocadas mensalmente para serem compradas pela store com preços caros para dar essa impressão de exclusiva.

**Comment by quasemago** [comment]
- Não acho uma boa ideia os sons.
- Não concordo em remover o VIP Deluxe, temos muitos VIPs que gostam de ter a skin exclusiva e ajudar o servidor (alguns com 12 meses comprados).
- De resto podemos discutir.

**Comment by danielhidalgojunior** [comment]
Curti a ideias dos sons, acho que vale a pena testar.

**Comment by lucaslinha** [comment]
Dolar não para de subir, retirar vip deluxe é matar o financeiro do server, eu ate tava pensando se vcs não aumentariam o preço dele dnv. 

Absolutamente nenhum server usa som de entrada, o que usam são os sons de chat em que você digita a palavra e da trigger no som, mas nao sei se é boa ideia.

**Comment by danielhidalgojunior** [comment]
Seria engraçado e ao meu ver não custa tentar

**Comment by hcjordao** [comment]
Podemos adicionar as coisas sem remover o Vip Deluxe. E ai bolarmos algo que não envolva skins no Vip Deluxe como sprays e musica ao entrar no server. Skin podem sugerir e alteramos mensalmente para comprar por tempo ali na store. E como a gabi disse tudo temporario nada permanente pro povo usar aquela store de mierda. O que é sem graça bota pra pleb usar, ate mesmo o ws e o knife bota pra pleb que esteja com a tag da ZRAGE/@ZRAGE.

Skins:
---
- Deixar algumas para o Pro (umas 3)
- Manter ainda a skin do Vip Deluxe exclusiva
- Mover o resto para timed based como era antes mas por um preço salgado para o povo usar esses creditos

Sounds:
---
- Massa afu, podemos remover essas musicas de fim de round e colocar sons para serem tocados no meio do round.
- Vip pra cima podem usar. Entretanto tem limite de 3 por rounds.
- Limite de X sons tocados por minuto, se ultrapassar muta os sons por 2 min.
- Sons curtos e engraçados, nada de bandoleira e tal, tem que ser curtinho tipo no maximo 3 segundos.
- Comando para desabilitar esses sons em eventos.
- Vip deluxe poderia ganhar um som ao entrar no servidor de max 1s sem ser muito alto.

ZKnifes / Custom Weapons:
---
- Feature do Vip pra cima, acesso as knifes e custom guns do server. Achava bem massa aquilo ali pra jogar.

Sprays:
---
- Vender no store custom sprays do narutinho, etc etc, povo vai amar. Time based tbm pro povo gastar esses creditos.

Emote:
---
- Emotes em cima da cabeça.

Creditos:
---
- Vip Normal ganha um bonus de credito
- Vip Pro ganha mais ainda
- Vip Deluxe ganha ainda mais

Nominate:
---
- Remover gastar credito por nominate

Hide:
---
- Vei eu acho o seguinte o cara paga pelo vip para mostrar pro povo as skins e etc. Para mim o hide deveria ser no maximo uns 100 de distancia e sem hidestore. Tu consegue fazer que tudo seja no_draw pelo client side. Podemos fazer o sacrificio e montar um pasta no nosso fastdl que o cara baixe um .zip com tudo no_draw e mostrar como da pra fazer isso no server.

**Comment by gabrielacms** [comment]
@hcjordao 
Hide - 
Ou poderíamos fazer diferente. As skins atuais do sv não tem como mais mas quem sabe as futuras já serem adicionadas tanto no servidor quanto no fastdl já modificadas com o recurso da transparência. De longe ficando normal mas de perto ficando invisível.

Emote -
Sou bem suspeita a falar já que já dei essa sugestão várias vezes kkk mas enfim, uma das melhores coisas do discord ao meu ver são os emojis, pessoal usa demais. E ver isso no servidor seria também. Eles não pesam muito, não vai afetar em nada. Mas esses ai por mim seria permanente a compra. 

Ws/Knife/Zknife 
Sobre o uso do !ws e !knife por mim o que decidirem, estarei de acordo.
Já o zknife, por mim colocava todas os itens na store e a pessoa podendo comprar por tempo. 

Obviamente que todos os itens da store seriam desbloqueados para os vips

**Comment by quasemago** [comment]
@hcjordao 
- Hide:
Não, pois ninguém é obrigado a jogar com 300 auras explodindo na sua cara. E modificação client-side está fora de cogitação, batata não sabe nem desligar musica vai saber editar coisa na pasta dele.

- Sounds:
Continuo contra som de entrada.

- Nominate gastando crédito:
Funciona bem em muitos servidores, inclusive eu estava pensando em fazer uma customização para definir os preços individuais. Por exemplo: são 135 créditos para nomear Westersand e apenas 75 para nomear Pirates.

- !ws, !knife:
Já estão liberados para todos os jogadores que estarem no grupo (não precisa de tag atualmente). Porém o knife são apenas algumas facas e não todas, fazendo que o jogador se interessa pelo VIP caso ele queira usar uma butterfly por exemplo.

**Comment by alminha021** [comment]
**HIDE E HIDESTORE**
Quanto ao hide , nao tenho problema com o atual. Ajuda os batata de pc batata
Problema pra mim eh o hidestore. Vieram com ideia ai de colocar o tracer pra sumir no hidestore, legal pra qm nao gosta de ver, mas agora nao tem um meio termo. Eu usava bastante os tracer dos outros pra saber onde estavam atirando etc.. Entao colocando td pra esconder com o hidestore , pra mim muita feature do vip eh inutil, ja que ninguem vai ver.
entao:
 > hidestore "editavel"
- A pessoa escolhe o que ela quer esconder.
- abre o menu com as opçoes ( esconder tudo, esconder somente auras, esconder somente tracers)

**emote & SPRAY**
SIM , QUERO.

**PET**
Nao to vendo muita gente de pet, e a maioria dos vips nao usam ao meu ver, entao libera pra geral nessa store novos pets.
- de preferencia de pokemon, tem varios pets de pokemon por ai que ja vi em outros server
- de preferencia que dure 1 mes.

** aquelas facas estilo desentupidor**
- joga na store
- de preferencia 1 mes

**sound**
se for entrar , som de no maximo 2 segundos
- automatico ao entrar no server acho que nao precisa, se o cara quiser ele reproduz o som dele ao entrar

**Comment by hcjordao** [comment]
@gabrielacms 
---
> Hide -
> Ou poderíamos fazer diferente. As skins atuais do sv não tem como mais mas quem sabe as futuras já serem adicionadas tanto no servidor quanto no fastdl já modificadas com o recurso da transparência. De longe ficando normal mas de perto ficando invisível.
> 
> Emote -
> Sou bem suspeita a falar já que já dei essa sugestão várias vezes kkk mas enfim, uma das melhores coisas do discord ao meu ver são os emojis, pessoal usa demais. E ver isso no servidor seria também. Eles não pesam muito, não vai afetar em nada. Mas esses ai por mim seria permanente a compra.

Acho justo ser permanente para vip como é o emote no tab.

> Obviamente que todos os itens da store seriam desbloqueados para os vips 

Acho que depende muito do item. Tipo skin move pro store por preço mesmo, e faz uma rotação maior das skins.

@quasemago 
---
> 
> * Hide:
>   Não, pois ninguém é obrigado a jogar com 300 auras explodindo na sua cara. E modificação client-side está fora de cogitação, batata não sabe nem desligar musica vai saber editar coisa na pasta dele.

Concordo que ninguém é obrigado a jogar com isso na cara. Por isso mesmo o jogador que não quer ver pode ir pra lá e alterar as pastas ele mesmo. Eu posso falar pq meu PC é bem merda. Mas tipo o povo compra as paradas para serem vistas no servidor e não podem. Estabelece um default bem curto como era antes. No máximo até 300.

Hide normal -> Até 300
Hidestore -> Filtrar auras e tracers somente. Pet, emotes ficam fora disso.

> * Sounds:
>   Continuo contra som de entrada.

Acho bem massa que vai atrair gente a comprar vip deluxe, tinha conversado com o fanzack gabi e alma. O som de entrada pode ser uma lista default que upamos na store e esses sons em específicos não são altos, fazemos uma redução deles pra não atrapalhar. 

> * Nominate gastando crédito:
>   Funciona bem em muitos servidores, inclusive eu estava pensando em fazer uma customização para definir os preços individuais. Por exemplo: são 135 créditos para nomear Westersand e apenas 75 para nomear Pirates.

Eu desgoto dessa opção acho que cada um devia poder nominar as paradas que quiser sem se preocupar. Atualmente é bom pois não tem muita coisa para comprar na store.

> * !ws, !knife:
>   Já estão liberados para todos os jogadores que estarem no grupo (não precisa de tag atualmente). Porém o knife são apenas algumas facas e não todas, fazendo que o jogador se interessa pelo VIP caso ele queira usar uma butterfly por exemplo.

Fazer oq eu falei. knife e ws para todos e zknife para vip ou por compra para store.

@alminha021 
> **HIDE E HIDESTORE**
> Quanto ao hide , nao tenho problema com o atual. Ajuda os batata de pc batata
> Problema pra mim eh o hidestore. Vieram com ideia ai de colocar o tracer pra sumir no hidestore, legal pra qm nao gosta de ver, mas agora nao tem um meio termo. Eu usava bastante os tracer dos outros pra saber onde estavam atirando etc.. Entao colocando td pra esconder com o hidestore pra mim muita feature do vip fica inutil, ja que ninguem vai ver.
> entao:
> 
> > hidestore "editavel"
> 
> * A pessoa escolhe o que ela quer esconder.
> * abre o menu com as opçoes ( esconder tudo, esconder somente auras, esconder somente tracers)

Concordo cntg que a feature do vip fica inutil pq ngm vai ver. Seria interessante um menu de escolha do que filtrar 

> **emote & SPRAY**
> SIM , QUERO.

Si manito. Upamos imagens default e o cara compra pelo store por duração de um mes. Tem que ser caro. No caso de emote o cara pode comprar não sendo vip e se for vip recebe de graça.

> **PET**
> Nao to vendo muita gente de pet, e a maioria dos vips nao usam ao meu ver, entao libera pra geral nessa store novos pets.
> 
> * de preferencia de pokemon, tem varios pets de pokemon por ai que ja vi em outros server
> * de preferencia que dure 1 mes.

Yup seria massa mais pets. Acho que pet como um todo teria alguns default de vip. E o resto só comprando mesmo. Pode ser compra bem cara por credito que é permanente nesse caso.

> **aquelas facas estilo desentupidor**
> 
> * joga na store
> * de preferencia 1 mes

Yup concordo.

> **sound**
> se for entrar , som de no maximo 2 segundos
> 
> * automatico ao entrar no server acho que nao precisa, se o cara quiser ele reproduz o som dele ao entrar

Sim bem curto e baixo.

**Comment by quasemago** [comment]
@hcjordao releia o meu tópico do hide, deixei bem claro que a maioria dos players não vão saber fazer tal customização client-side.

**Comment by kobe-hcjordao** [comment]
Só acho meio zuado ter as paradas do vip sendo que isso não é visivel para alguns jogadores. Reduzir o limite do hide para 300 então ou menos.

**Comment by quasemago** [comment]
Retirei o **!hidestore** dos pets. Quanto ao limite do **!hide** aumentei pois estava muito ruim nos eventos com drop de fps e usar em 900 melhorou consideravelmente para mim, acredito que isso tenha beneficiado outros players também.

**Comment by kobe-hcjordao** [comment]
É um trade off de melhoria do pc do cara e os itens customs do server.

**Comment by alminha021** [comment]
!hidestore editavel for the win.

**Menu !hidestore**
> - esconder/desesconder  tudo
> - esconder/desesconder rastros e auras
> - esconder/desesconder  tracers
>- esconder/desesconder  pets

**Comment by quasemago** [comment]
:residentsleeper:

**Comment by lucaslinha** [comment]
Sobre item de pleb, eu prefiro sistema de tempo como nos velhos tempos de stamm, alem de valorizar quem ta sempre presente, tem a chance de criar novos sem vida e aumentar o numero de regulares o que pode aumentar nem que seja um pouco o nivel do server, ja que é lotado de casual dependente de evento pra vencer literalmente qualquer coisa.

**Comment by kobe-hcjordao** [comment]
stamm is ded just accept it, não faz sentido dar back track a um sistema que a gnt não usa para mais nada. Tem o DB que fala a quanto tempo o cara ta no server jogando, mas prefiro usar o sistema de credito para nao adicionar mais uma dependencia ao store

**Comment by danielhidalgojunior** [comment]
> ## Hide:
> * Vei eu acho o seguinte o cara paga pelo vip para mostrar pro povo as skins e etc. Para mim o hide deveria ser no maximo uns 100 de distancia e sem hidestore. Tu consegue fazer que tudo seja no_draw pelo client side. Podemos fazer o sacrificio e montar um pasta no nosso fastdl que o cara baixe um .zip com tudo no_draw e mostrar como da pra fazer isso no server.

@hcjordao 

Nisso eu sou contra. É visualmente cansativo aquele monte de skin flutuando na sua tela, sem contar o lag que o pessoal teria que aguentar. Tudo bem que dá pra corrigir clientside, mas a maioria do povo não sabe como fazer isso e duvido que vão correr atrás. E novamente os novatos seriam os mais prejudicados.

**Comment by kobe-hcjordao** [comment]
famoso pau no cu dos prejudicados 🤣 , brincadeira a parte. Reduz entao, 900 ta muito zoado, o cara paga e não pode mostrar a skin. Ronning usa um isRonning para não esconder a skin dele, a mesma coisa para logica de quem paga para isso. 

Reduz de 900 p/ 300 e adiciona no arquivo da skin o filtro de invisibilidade a distancia. Dois toques para fazer.

**Comment by lucaslinha** [comment]
> stamm is ded just accept it, não faz sentido dar back track a um sistema que a gnt não usa para mais nada. Tem o DB que fala a quanto tempo o cara ta no server jogando, mas prefiro usar o sistema de credito para nao adicionar mais uma dependencia ao store

Não faz sentido como ? ronning mesmo ja tinha preparado um sistema de battle pass baseado em tempo a um tempo atras que tava ate pronto, so que não foi pro server. "não faz sentido dar back track a um sistema que a gnt não usa para mais nada." Porra descreveu bem o atual sistema de creditos do server, uma coisa que ngm sabe nem pra que serve.

**Comment by danielhidalgojunior** [comment]
aguardo ansioso pelos sons de entrada no sv.

https://www.myinstants.com/instant/ai-pai-para/

**Comment by kobe-hcjordao** [comment]
> Não faz sentido como ? ronning mesmo ja tinha preparado um sistema de battle pass baseado em tempo a um tempo atras que tava ate pronto, so que não foi pro server. "não faz sentido dar back track a um sistema que a gnt não usa para mais nada." Porra descreveu bem o atual sistema de creditos do server, uma coisa que ngm sabe nem pra que serve.

Credito já é um sistema de medida de tempo no server. Só usar direito pra comprar coisa. Não sabe usar pq não tem muita coisa para comprar la dentro, a maioria das paradas é de vip já liberado. Muda a logica para vips ganharem mais creditos e move as coisas para dentro da loja.

**Comment by lucaslinha** [comment]
GUC servidor alemão ja faz isso a um bom tempo e atrai bastante gente. Basicamente é um merge de ideia do antigo sistema de tempo com o atual de creditos 
> O jogador vai upando sua tag conforme vai alcançando um certo numero de créditos. 
> A tag é automatica igual ao antigo sistema de rank ( O jogador pode desequipar se desejar).
> No momento do seu up, poderia ter uma mensagem e o som como acontecia no sistema antigo.
> Em niveis mais altos a tag terá também cor de nome e cor de mensagem personalizado.

**Comment by kobe-hcjordao** [comment]
Mas isso dai nao daria conflito com as cores de vip? Isso de up de tag se fizessemos a automatização das tags e salvar no db quantas vezes um jogador zera os mapas daria facilmente para criar tags de novato até veterano baseado no numero de mapas distintios zerados do server

**Comment by lucaslinha** [comment]
> Mas isso dai nao daria conflito com as cores de vip? Isso de up de tag se fizessemos a automatização das tags e salvar no db quantas vezes um jogador zera os mapas daria facilmente para criar tags de novato até veterano baseado no numero de mapas distintios zerados do server

Nah plmdds, a quantidade de mapas zerados é baixissima ate mesmo contado evento, o processo de up seria mais do que lento.

**Comment by kobe-hcjordao** [comment]
Claro que não só add leveis baixos. Além do que vira e mexe já zeram os mapas newbs

**Comment by kobe-hcjordao** [comment]
Por tempo não faz sentido algum, cara não vai ser veterano com 7000 minutos de game se o cara nao zerou um mapa vai continuar sendo batatão

**Comment by lucaslinha** [comment]
No final das contas da no mesmo, ou o cara so joga level facil pra farmar ou foi carregado por alguem em um mapa dificil, essa rank não significaria que ele é bom.

**Comment by lucaslinha** [comment]
Mas no caso dos creditos não teria falso positivo em relação a pontuação errada ou mapa matando todos os zms e dando ponto de graça pro cara

**Comment by kobe-hcjordao** [comment]
Por isso eu falei distintos. Não farmaria mapa zerado pois seriam os distintos que ele zerou, logo zerar o mesmo mapa over and over não mudaria o rank dele. Não tem como separar o jogador pois o modo gira em torno do time portanto sempre vai ter carregado.

**Comment by lucaslinha** [comment]
E como seria distribuido a pontuação ?

**Comment by quasemago** [comment]
Estou achando que essa conversa de vocês fugiu o escopo do issue.

**Comment by lucaslinha** [comment]
Verdade, efim minha sugestao usa os creditos logo tem relação com o store e creio que é bem mais simples de executar.

**Comment by hcjordao** [comment]
Fugiu um pouco mas acontece.

> Verdade, efim minha sugestao usa os creditos logo tem relação com o store e creio que é bem mais simples de executar.

Só acho que é meio nada haver tentar medir o conhecimento de um jogador com creditos. Já existe os webhooks de vencer o mapa. Só pegar isso e linkar com um DB estruturado.

Ao vencer um mapa faz um fetch no DB pela steam id do jogador, salva a id dos vencedores, pega o id do mapa pegando o nome do mapa. Adiciona a vitoria do mapa na tabela de vitorias geral para cada jogador. Depois só fazer um filtro no banco de dados para ver se com esse incremento ele liberou uma tag, se ele liberar uma tag mostra uma msgzinha no chat para geral ver Fulano avançou para nova Tag. Pronto. 

Unica coisa que teria que pensar é se vai salvar as tags do jogador ou vai fazer um fetch na lista de vitorias para ver se um jogador tem os pré requisitos para colocar a tag.

**Comment by lucaslinha** [comment]
Não é pra medir o conhecimento de um jogador é so pra indicar a quanto tempo ele joga no server e o seu metodo exige mapeamento dos leveis faceis aos medios aos dificeis, boa sorte fazendo isso ae.

**Comment by hcjordao** [comment]
todos os mapas teriam o mesmo peso, seria por quantidade apenas.

**Comment by lucaslinha** [comment]
> todos os mapas teriam o mesmo peso, seria por quantidade apenas.

Começou ruim, depois ficou bom, agora parece que piorou.

**Comment by hcjordao** [comment]
Muito trabalho como vc mesmo disse de por peso em mapa. Seria mais uma coisa para balancear sem saco para fazer isso. Para mim essa ideia de dar veteran por credito/tempo mesmo problema que o anterior que vai gerar um povo cancer se achando bom sendo batata, therefore acho uma pessima ideia.

**Comment by alminha021** [comment]
Sei la, começou com store terminou com qualidade dos jogadores.
Vamo focar em dar uma utilidade a store, coloca td q foi sugerido, atrai os cara a ficar online pra juntar e comprar algo.
Habilidade nao a pra medir com tempo de server e com mapas zerados, pra isso ja uso meu sistema, que eh bem simples:
 - eu vejo um cara jogando,se ele me chamou atençao eh pq ta jogando bem, fora isso ou eh roroso ou eh mais um beija porta que pula 2 lasers no final sem ajudar nos hold e se acha bom.
Enfim , nao da pra medir habilidade do cara por tmepo nem por mapa zerado, so funcionaria se existisse um algoritmo que analisa tudo dele, dano, k/d , vitorias / derrotas, dificuldade do mapa etc. isso eh outro topico. 
MAS , se querem fazer isso, nao vejo problema de ter os 2.
a ideia do haru se junta ao esquema de entregar tag automatica de MAPA , ja a que o infused falou , eh so colocar tag pra vender por um alto valor , qnd o cara comprar aparece no chat, ou ate mesmo uma parte da store so eh liberada com o "rank" do cara.
Apos ele juntar 10k ele "upa" de level e libera uma tag para comprar na store. 
1k - [Novato]
10k [elite]
50k [veteran]
100k [ Pro]
200k [ GOD ]

**Comment by hcjordao** [comment]
Com a remoção das auras e tracers. Não poderiamos pensar em coisas que foram faladas aqui para inserirmos coisas que não comeria tanto de processamento do servidor? Sprites, sons, emotes, zknifes e pets seriam bem mais otimizados do que essas auras

**Comment by lucaslinha** [comment]
> Com a remoção das auras e tracers. Não poderiamos pensar em coisas que foram faladas aqui para inserirmos coisas que não comeria tanto de processamento do servidor? Sprites, sons, emotes, zknifes e pets seriam bem mais otimizados do que essas auras

Unica coisa que utiliza som que eu acho viável seria comandos de radio ja que eles ajudam a alertar as pessoas a recuar, defender e mesmo assim precisaria de um cd generoso. De resto eu concordo em colocar por compra temporaria.

**Comment by lucaslinha** [comment]
Bom creio que isso aqui nem precise da mão do ronning pra fazer, afinal ja teve esse recurso antes. A store ja suporta tempo, custo de creditos etc ... Falta so a galera se reunir e formatar o txt da store.
