### ISSUE TITLE
TTT - Problemas com DTT

### ISSUE THREAD

**Issue by lhsatsuma** [quasemago/zrageservers#99]
Muita gente ta virando detetive mesmo nunca ter jogado como DTT ou ter digitado !dtt no chat.
Esse problema já acontecia um tempo atrás e agora voltou.

**Comment by quasemago** [comment]
Talvez o cara tenha definido usando comando de forma oculta (/dtt). Está tudo correto no código.

**Comment by lhsatsuma** [comment]
Aonde q é salvo a opção de !dtt?

Tem um player chamado "King?" q nunca tinha digitado !dtt e ele acabou virando...

Até mesmo o @hcjordao virou dtt agora a pouco e acho que ele não tinha setado pra virar.

**Comment by quasemago** [comment]
É salvo no clientprefs do jogador (banco de dados SQLite).

**Comment by lhsatsuma** [comment]
Vcs resetaram nas ultimas semanas?
Pq é a unica explicação q eu consigo achar no momento.

Pode ser q como não tem registro, ele não considera q não é pra virar DTT

**Comment by quasemago** [comment]
Valor padrão é desativado, logo se não tem registro para o jogador, ele não vai virar DTT.

**Comment by lhsatsuma** [comment]
De acordo com o Geraldo, ele virou DTT e não tinha digitado !dtt

Parece que é um bang aleatório... As vezes o round não tem nenhum DTT, ai o proximo ele seleciona aleatoriamente alguem pra virar DTT

**Comment by lhsatsuma** [comment]
E ta bem frequente esse troço, tipo a cada 2 rounds um player aleatorio vira DTT.

**Comment by hcjordao** [comment]
Sim ocorreu comigo esses dias, não digitei nada sobre ser dtt e virei

**Comment by quasemago** [comment]
Foram feito algumas alterações, favor testarem!

**Comment by quasemago** [comment]
Caso o problema volte a acontecer, crie novamente outro issue.
